import pandas as pd
import ast  # Use ast for safer evaluation of strings to dictionaries

# Step 1: Load your DataFrame from the Excel file
file_path = 'chennai_cars.xlsx'  # Your Excel file name
df = pd.read_excel(file_path)

# Step 2: Initialize an empty list to hold the structured data
unwound_data = []

# Step 3: Loop through each row of the DataFrame
for index, row in df.iterrows():
    # Initialize a dictionary for the current row
    combined_data = {}
    
    # Specify the columns containing dictionaries
    dict_columns = ['new_car_detail', 'new_car_overview', 'new_car_feature', 'new_car_specs']
    
    # Step 4: Extract and merge dictionaries from the specified columns
    for col in dict_columns:
        try:
            # Safely convert the string representation of the dictionary to an actual dictionary
            dict_value = ast.literal_eval(row[col])  
            if isinstance(dict_value, dict):
                combined_data.update(dict_value)  # Merge the extracted dictionary
        except Exception as e:
            print(f"Error parsing row {index}, column {col}: {e}")

    # Append the combined data for the current row to the unwound data list
    unwound_data.append(combined_data)

# Step 5: Create a DataFrame from the unwound data
unwound_df = pd.DataFrame(unwound_data)

# Optional: Display the unwound DataFrame
print(unwound_df)

# Save the unwound DataFrame to a new Excel file if needed
unwound_df.to_excel('unwound_chennai_cars.xlsx', index=False)

In [9]:
unwound_df.head()

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,price,priceActual,priceSaving,priceFixedText,trendingText,heading,top,bottomData,data,commonIcon
0,0,Petrol,SUV,"20,000",Automatic,1,1st Owner,Kia,Kia Sonet,2022,...,₹ 11.50 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...,Specifications,"[{'key': 'Engine', 'value': '998 CC'}, {'key':...",None,"[{'heading': 'Engine and Transmission', 'subHe...",
1,0,Petrol,Minivans,"20,687",Manual,1,1st Owner,Maruti,Maruti Eeco,2015,...,₹ 4.15 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...,Specifications,"[{'key': 'Mileage', 'value': '15.37 kmpl'}, {'...",None,"[{'heading': 'Engine and Transmission', 'subHe...",
2,0,Petrol,SUV,"30,000",Manual,1,1st Owner,Nissan,Nissan Magnite,2021,...,₹ 7.50 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...,Specifications,"[{'key': 'Mileage', 'value': '20 kmpl'}, {'key...",None,"[{'heading': 'Engine and Transmission', 'subHe...",
3,0,Petrol,Hatchback,"59,247",Manual,1,1st Owner,Hyundai,Hyundai i10,2015,...,₹ 3.98 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...,Specifications,"[{'key': 'Mileage', 'value': '19.81 kmpl'}, {'...",None,"[{'heading': 'Engine and Transmission', 'subHe...",
4,0,Petrol,Hatchback,"50,000",Manual,1,1st Owner,Honda,Honda Jazz,2015,...,₹ 5.50 Lakh,,,None,{'imgUrl': 'https://stimg.cardekho.com/used-ca...,Specifications,"[{'key': 'Mileage', 'value': '18.7 kmpl'}, {'k...",None,"[{'heading': 'Engine and Transmission', 'subHe...",

In [10]:
unwound_df.columns

Index(['it', 'ft', 'bt', 'km', 'transmission', 'ownerNo', 'owner', 'oem',
       'model', 'modelYear', 'centralVariantId', 'variantName', 'price',
       'priceActual', 'priceSaving', 'priceFixedText', 'trendingText',
       'heading', 'top', 'bottomData', 'data', 'commonIcon'],
      dtype='object')

In [34]:
import pandas as pd

# Step 1: Read the Excel file
df = pd.read_excel("chennai_cars.xlsx")

# Step 2: Initialize an empty list to hold structured data
structured_data = []

# Step 3: Loop through each row of the DataFrame
for index, row in df.iterrows():
    row_data = {}
    
    # Convert the string representation of the dictionary to an actual dictionary
    try:
        dict_value = eval(row['new_car_detail'])  # Replace eval with ast.literal_eval for safer evaluation
        if isinstance(dict_value, dict):
            row_data = dict_value
    except Exception as e:
        print(f"Error parsing row {index}: {e}")
        row_data = None

    # Append the row dictionary to the structured data list
    structured_data.append(row_data)

# Step 4: Create a DataFrame from the list of dictionaries in 'new_car_detail'
unwound_df = pd.json_normalize(structured_data)

# Optional: Display the unwound DataFrame
print(unwound_df)

# Save the unwound DataFrame to a new Excel file
#unwound_df.to_excel('unwound_new_car_detail.xlsx', index=False)

      it      ft         bt      km transmission  ownerNo      owner  \
0      0  Petrol        SUV  20,000    Automatic        1  1st Owner
1      0  Petrol   Minivans  20,687       Manual        1  1st Owner
2      0  Petrol        SUV  30,000       Manual        1  1st Owner
3      0  Petrol  Hatchback  59,247       Manual        1  1st Owner
4      0  Petrol  Hatchback  50,000       Manual        1  1st Owner
...   ..     ...        ...     ...          ...      ...        ...
1414   0  Petrol  Hatchback  42,891    Automatic        1  1st Owner
1415   0  Diesel        SUV  59,100       Manual        1  1st Owner
1416   0  Petrol        SUV  55,913    Automatic        1  1st Owner
1417   0  Diesel        SUV  65,000    Automatic        1  1st Owner
1418   0  Diesel      Sedan  60,000    Automatic        1  1st Owner

             oem              model  modelYear  centralVariantId  \
0            Kia          Kia Sonet       2022              8654
1         Maruti        Maruti Eeco       2015              4025
2         Nissan     Nissan Magnite       2021              8135
3        Hyundai        Hyundai i10       2015              1579
4          Honda         Honda Jazz       2015              1341
...          ...                ...        ...               ...
1414      Maruti       Maruti Swift       2018              6190
1415     Renault     Renault Duster       2018              5050
1416        Tata         Tata Nexon       2018              6364
1417  Volkswagen  Volkswagen Tiguan       2017              5849
1418         BMW    BMW 3 Series GT       2019              6630

                        variantName         price priceActual priceSaving  \
0     Turbo DCT Anniversary Edition  ₹ 11.50 Lakh
1            7 Seater Standard BSIV   ₹ 4.15 Lakh
2             Turbo XV Premium BSVI   ₹ 7.50 Lakh
3                       Sportz 1.1L   ₹ 3.98 Lakh
4                     1.2 VX i VTEC   ₹ 5.50 Lakh
...                             ...           ...         ...         ...
1414                        AMT VXI   ₹ 6.20 Lakh
1415                85PS Diesel RxZ   ₹ 8.90 Lakh
1416          1.2 Revotron XZA Plus   ₹ 8.01 Lakh
1417               2.0 TDI Highline  ₹ 20.50 Lakh
1418                          Sport  ₹ 35.75 Lakh

     priceFixedText                                trendingText.imgUrl  \
0              None  https://stimg.cardekho.com/used-cars/common/ic...
1              None  https://stimg.cardekho.com/used-cars/common/ic...
2              None  https://stimg.cardekho.com/used-cars/common/ic...
3              None  https://stimg.cardekho.com/used-cars/common/ic...
4              None  https://stimg.cardekho.com/used-cars/common/ic...
...             ...                                                ...
1414           None  https://stimg.cardekho.com/used-cars/common/ic...
1415           None  https://stimg.cardekho.com/used-cars/common/ic...
1416           None  https://stimg.cardekho.com/used-cars/common/ic...
1417           None  https://stimg.cardekho.com/used-cars/common/ic...
1418           None  https://stimg.cardekho.com/used-cars/common/ic...

     trendingText.heading                    trendingText.desc
0           Trending Car!  High chances of sale in next 6 days
1           Trending Car!  High chances of sale in next 6 days
2           Trending Car!  High chances of sale in next 6 days
3           Trending Car!  High chances of sale in next 6 days
4           Trending Car!  High chances of sale in next 6 days
...                   ...                                  ...
1414        Trending Car!  High chances of sale in next 6 days
1415        Trending Car!  High chances of sale in next 6 days
1416        Trending Car!  High chances of sale in next 6 days
1417        Trending Car!  High chances of sale in next 6 days
1418        Trending Car!  High chances of sale in next 6 days

[1419 rows x 19 columns]

In [35]:
import pandas as pd

# Step 1: Read the Excel file
df = pd.read_excel("chennai_cars.xlsx")

# Step 2: Initialize an empty list to hold structured data
structured_data = []

# Step 3: Loop through each row of the DataFrame
for index, row in df.iterrows():
    row_data = {}
    
    # Convert the string representation of the dictionary to an actual dictionary
    try:
        dict_value = eval(row['new_car_overview'])  # Replace eval with ast.literal_eval for safer evaluation
        if isinstance(dict_value, dict):
            row_data = dict_value
    except Exception as e:
        print(f"Error parsing row {index}: {e}")
        row_data = None

    # Append the row dictionary to the structured data list
    structured_data.append(row_data)

# Step 4: Create a DataFrame from the list of dictionaries in 'new_car_detail'
unwound_df1 = pd.json_normalize(structured_data)

# Optional: Display the unwound DataFrame
print(unwound_df1)

# Save the unwound DataFrame to a new Excel file
#unwound_df.to_excel('unwound_new_car_detail.xlsx', index=False)

           heading                                                top  \
0     Car overview  [{'key': 'Registration Year', 'value': '2022',...
1     Car overview  [{'key': 'Registration Year', 'value': 'Feb 20...
2     Car overview  [{'key': 'Registration Year', 'value': '2021',...
3     Car overview  [{'key': 'Registration Year', 'value': 'May 20...
4     Car overview  [{'key': 'Registration Year', 'value': '2015',...
...            ...                                                ...
1414  Car overview  [{'key': 'Registration Year', 'value': 'Jun 20...
1415  Car overview  [{'key': 'Registration Year', 'value': 'Feb 20...
1416  Car overview  [{'key': 'Registration Year', 'value': 'Aug 20...
1417  Car overview  [{'key': 'Registration Year', 'value': 'Aug 20...
1418  Car overview  [{'key': 'Registration Year', 'value': 'Oct 20...

     bottomData
0          None
1          None
2          None
3          None
4          None
...         ...
1414       None
1415       None
1416       None
1417       None
1418       None

[1419 rows x 3 columns]

In [36]:
import pandas as pd

# Step 1: Read the Excel file
df = pd.read_excel("chennai_cars.xlsx")

# Step 2: Initialize an empty list to hold structured data
structured_data = []

# Step 3: Loop through each row of the DataFrame
for index, row in df.iterrows():
    row_data = {}
    
    # Convert the string representation of the dictionary to an actual dictionary
    try:
        dict_value = eval(row['new_car_feature'])  # Replace eval with ast.literal_eval for safer evaluation
        if isinstance(dict_value, dict):
            row_data = dict_value
    except Exception as e:
        print(f"Error parsing row {index}: {e}")
        row_data = None

    # Append the row dictionary to the structured data list
    structured_data.append(row_data)

# Step 4: Create a DataFrame from the list of dictionaries in 'new_car_detail'
unwound_df2 = pd.json_normalize(structured_data)

# Optional: Display the unwound DataFrame
print(unwound_df2)

# Save the unwound DataFrame to a new Excel file
#unwound_df.to_excel('unwound_new_car_detail.xlsx', index=False)

       heading                                                top  \
0     Features  [{'value': 'Power Steering'}, {'value': 'Power...
1     Features  [{'value': 'Low Fuel Warning Light'}, {'value'...
2     Features  [{'value': 'Power Steering'}, {'value': 'Power...
3     Features  [{'value': 'Power Steering'}, {'value': 'Power...
4     Features  [{'value': 'Power Steering'}, {'value': 'Power...
...        ...                                                ...
1414  Features  [{'value': 'Power Steering'}, {'value': 'Power...
1415  Features  [{'value': 'Power Steering'}, {'value': 'Power...
1416  Features  [{'value': 'Power Steering'}, {'value': 'Power...
1417  Features  [{'value': 'Power Steering'}, {'value': 'Power...
1418  Features  [{'value': 'Power Steering'}, {'value': 'Power...

                                                   data  \
0     [{'heading': 'Comfort & Convenience', 'subHead...
1     [{'heading': 'Comfort & Convenience', 'subHead...
2     [{'heading': 'Comfort & Convenience', 'subHead...
3     [{'heading': 'Comfort & Convenience', 'subHead...
4     [{'heading': 'Comfort & Convenience', 'subHead...
...                                                 ...
1414  [{'heading': 'Comfort & Convenience', 'subHead...
1415  [{'heading': 'Comfort & Convenience', 'subHead...
1416  [{'heading': 'Comfort & Convenience', 'subHead...
1417  [{'heading': 'Comfort & Convenience', 'subHead...
1418  [{'heading': 'Comfort & Convenience', 'subHead...

                                             commonIcon
0     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
2     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
3     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
4     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
...                                                 ...
1414  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1415  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1416  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1417  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1418  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg

[1419 rows x 4 columns]

In [37]:
import pandas as pd

# Step 1: Read the Excel file
df = pd.read_excel("chennai_cars.xlsx")

# Step 2: Initialize an empty list to hold structured data
structured_data = []

# Step 3: Loop through each row of the DataFrame
for index, row in df.iterrows():
    row_data = {}
    
    # Convert the string representation of the dictionary to an actual dictionary
    try:
        dict_value = eval(row['new_car_specs'])  # Replace eval with ast.literal_eval for safer evaluation
        if isinstance(dict_value, dict):
            row_data = dict_value
    except Exception as e:
        print(f"Error parsing row {index}: {e}")
        row_data = None

    # Append the row dictionary to the structured data list
    structured_data.append(row_data)

# Step 4: Create a DataFrame from the list of dictionaries in 'new_car_detail'
unwound_df3 = pd.json_normalize(structured_data)

# Optional: Display the unwound DataFrame
print(unwound_df3)

# Save the unwound DataFrame to a new Excel file
#unwound_df.to_excel('unwound_new_car_detail.xlsx', index=False)

             heading                                                top  \
0     Specifications  [{'key': 'Engine', 'value': '998 CC'}, {'key':...
1     Specifications  [{'key': 'Mileage', 'value': '15.37 kmpl'}, {'...
2     Specifications  [{'key': 'Mileage', 'value': '20 kmpl'}, {'key...
3     Specifications  [{'key': 'Mileage', 'value': '19.81 kmpl'}, {'...
4     Specifications  [{'key': 'Mileage', 'value': '18.7 kmpl'}, {'k...
...              ...                                                ...
1414  Specifications  [{'key': 'Mileage', 'value': '22 kmpl'}, {'key...
1415  Specifications  [{'key': 'Mileage', 'value': '19.87 kmpl'}, {'...
1416  Specifications  [{'key': 'Mileage', 'value': '17 kmpl'}, {'key...
1417  Specifications  [{'key': 'Mileage', 'value': '16.65 kmpl'}, {'...
1418  Specifications  [{'key': 'Mileage', 'value': '21.76 kmpl'}, {'...

                                                   data commonIcon
0     [{'heading': 'Engine and Transmission', 'subHe...
1     [{'heading': 'Engine and Transmission', 'subHe...
2     [{'heading': 'Engine and Transmission', 'subHe...
3     [{'heading': 'Engine and Transmission', 'subHe...
4     [{'heading': 'Engine and Transmission', 'subHe...
...                                                 ...        ...
1414  [{'heading': 'Engine and Transmission', 'subHe...
1415  [{'heading': 'Engine and Transmission', 'subHe...
1416  [{'heading': 'Engine and Transmission', 'subHe...
1417  [{'heading': 'Engine and Transmission', 'subHe...
1418  [{'heading': 'Engine and Transmission', 'subHe...

[1419 rows x 4 columns]

In [40]:
import pandas as pd

# Assume df1, df2, df3, and df4 are your four DataFrames

# Concatenate the DataFrames column-wise
combined_df = pd.concat([unwound_df, unwound_df1, unwound_df2, unwound_df3], axis=1)

# Optional: Display the combined DataFrame
print(combined_df)

# Save the combined DataFrame to a new Excel file if needed
combined_df.to_excel('combined_data_column_wise.xlsx', index=False)

      it      ft         bt      km transmission  ownerNo      owner  \
0      0  Petrol        SUV  20,000    Automatic        1  1st Owner
1      0  Petrol   Minivans  20,687       Manual        1  1st Owner
2      0  Petrol        SUV  30,000       Manual        1  1st Owner
3      0  Petrol  Hatchback  59,247       Manual        1  1st Owner
4      0  Petrol  Hatchback  50,000       Manual        1  1st Owner
...   ..     ...        ...     ...          ...      ...        ...
1414   0  Petrol  Hatchback  42,891    Automatic        1  1st Owner
1415   0  Diesel        SUV  59,100       Manual        1  1st Owner
1416   0  Petrol        SUV  55,913    Automatic        1  1st Owner
1417   0  Diesel        SUV  65,000    Automatic        1  1st Owner
1418   0  Diesel      Sedan  60,000    Automatic        1  1st Owner

             oem              model  modelYear  ...  \
0            Kia          Kia Sonet       2022  ...
1         Maruti        Maruti Eeco       2015  ...
2         Nissan     Nissan Magnite       2021  ...
3        Hyundai        Hyundai i10       2015  ...
4          Honda         Honda Jazz       2015  ...
...          ...                ...        ...  ...
1414      Maruti       Maruti Swift       2018  ...
1415     Renault     Renault Duster       2018  ...
1416        Tata         Tata Nexon       2018  ...
1417  Volkswagen  Volkswagen Tiguan       2017  ...
1418         BMW    BMW 3 Series GT       2019  ...

                                                    top bottomData   heading  \
0     [{'key': 'Registration Year', 'value': '2022',...       None  Features
1     [{'key': 'Registration Year', 'value': 'Feb 20...       None  Features
2     [{'key': 'Registration Year', 'value': '2021',...       None  Features
3     [{'key': 'Registration Year', 'value': 'May 20...       None  Features
4     [{'key': 'Registration Year', 'value': '2015',...       None  Features
...                                                 ...        ...       ...
1414  [{'key': 'Registration Year', 'value': 'Jun 20...       None  Features
1415  [{'key': 'Registration Year', 'value': 'Feb 20...       None  Features
1416  [{'key': 'Registration Year', 'value': 'Aug 20...       None  Features
1417  [{'key': 'Registration Year', 'value': 'Aug 20...       None  Features
1418  [{'key': 'Registration Year', 'value': 'Oct 20...       None  Features

                                                    top  \
0     [{'value': 'Power Steering'}, {'value': 'Power...
1     [{'value': 'Low Fuel Warning Light'}, {'value'...
2     [{'value': 'Power Steering'}, {'value': 'Power...
3     [{'value': 'Power Steering'}, {'value': 'Power...
4     [{'value': 'Power Steering'}, {'value': 'Power...
...                                                 ...
1414  [{'value': 'Power Steering'}, {'value': 'Power...
1415  [{'value': 'Power Steering'}, {'value': 'Power...
1416  [{'value': 'Power Steering'}, {'value': 'Power...
1417  [{'value': 'Power Steering'}, {'value': 'Power...
1418  [{'value': 'Power Steering'}, {'value': 'Power...

                                                   data  \
0     [{'heading': 'Comfort & Convenience', 'subHead...
1     [{'heading': 'Comfort & Convenience', 'subHead...
2     [{'heading': 'Comfort & Convenience', 'subHead...
3     [{'heading': 'Comfort & Convenience', 'subHead...
4     [{'heading': 'Comfort & Convenience', 'subHead...
...                                                 ...
1414  [{'heading': 'Comfort & Convenience', 'subHead...
1415  [{'heading': 'Comfort & Convenience', 'subHead...
1416  [{'heading': 'Comfort & Convenience', 'subHead...
1417  [{'heading': 'Comfort & Convenience', 'subHead...
1418  [{'heading': 'Comfort & Convenience', 'subHead...

                                             commonIcon         heading  \
0     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
1     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
2     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
3     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
4     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
...                                                 ...             ...
1414  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
1415  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
1416  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
1417  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
1418  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications

                                                    top  \
0     [{'key': 'Engine', 'value': '998 CC'}, {'key':...
1     [{'key': 'Mileage', 'value': '15.37 kmpl'}, {'...
2     [{'key': 'Mileage', 'value': '20 kmpl'}, {'key...
3     [{'key': 'Mileage', 'value': '19.81 kmpl'}, {'...
4     [{'key': 'Mileage', 'value': '18.7 kmpl'}, {'k...
...                                                 ...
1414  [{'key': 'Mileage', 'value': '22 kmpl'}, {'key...
1415  [{'key': 'Mileage', 'value': '19.87 kmpl'}, {'...
1416  [{'key': 'Mileage', 'value': '17 kmpl'}, {'key...
1417  [{'key': 'Mileage', 'value': '16.65 kmpl'}, {'...
1418  [{'key': 'Mileage', 'value': '21.76 kmpl'}, {'...

                                                   data commonIcon
0     [{'heading': 'Engine and Transmission', 'subHe...
1     [{'heading': 'Engine and Transmission', 'subHe...
2     [{'heading': 'Engine and Transmission', 'subHe...
3     [{'heading': 'Engine and Transmission', 'subHe...
4     [{'heading': 'Engine and Transmission', 'subHe...
...                                                 ...        ...
1414  [{'heading': 'Engine and Transmission', 'subHe...
1415  [{'heading': 'Engine and Transmission', 'subHe...
1416  [{'heading': 'Engine and Transmission', 'subHe...
1417  [{'heading': 'Engine and Transmission', 'subHe...
1418  [{'heading': 'Engine and Transmission', 'subHe...

[1419 rows x 30 columns]

In [41]:
combined_df.columns

Index(['it', 'ft', 'bt', 'km', 'transmission', 'ownerNo', 'owner', 'oem',
       'model', 'modelYear', 'centralVariantId', 'variantName', 'price',
       'priceActual', 'priceSaving', 'priceFixedText', 'trendingText.imgUrl',
       'trendingText.heading', 'trendingText.desc', 'heading', 'top',
       'bottomData', 'heading', 'top', 'data', 'commonIcon', 'heading', 'top',
       'data', 'commonIcon'],
      dtype='object')

In [42]:
import pandas as pd

# Example DataFrame with repeating columns (for demonstration purposes)
# combined_df = pd.DataFrame(...)  # Assume this is your existing DataFrame

# Step 1: Get the current column names
original_columns = combined_df.columns

# Step 2: Create a new list to hold unique column names
new_columns = []
column_count = {}

# Step 3: Loop through original columns and create unique names
for col in original_columns:
    if col in column_count:
        column_count[col] += 1
        new_columns.append(f"{col}_{column_count[col]}")  # Append count as suffix
    else:
        column_count[col] = 1
        new_columns.append(col)  # Keep original name for the first occurrence

# Step 4: Assign the new column names to the DataFrame
combined_df.columns = new_columns

# Optional: Display the updated DataFrame columns
print(combined_df.columns)

Index(['it', 'ft', 'bt', 'km', 'transmission', 'ownerNo', 'owner', 'oem',
       'model', 'modelYear', 'centralVariantId', 'variantName', 'price',
       'priceActual', 'priceSaving', 'priceFixedText', 'trendingText.imgUrl',
       'trendingText.heading', 'trendingText.desc', 'heading', 'top',
       'bottomData', 'heading_2', 'top_2', 'data', 'commonIcon', 'heading_3',
       'top_3', 'data_2', 'commonIcon_2'],
      dtype='object')

In [44]:
combined_df.head(1)

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,top,bottomData,heading_2,top_2,data,commonIcon,heading_3,top_3,data_2,commonIcon_2
0,0,Petrol,SUV,"20,000",Automatic,1,1st Owner,Kia,Kia Sonet,2022,...,"[{'key': 'Registration Year', 'value': '2022',...",None,Features,"[{'value': 'Power Steering'}, {'value': 'Power...","[{'heading': 'Comfort & Convenience', 'subHead...",https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg,Specifications,"[{'key': 'Engine', 'value': '998 CC'}, {'key':...","[{'heading': 'Engine and Transmission', 'subHe...",

In [65]:
import pandas as pd

# Function to extract and convert 'top1' into a DataFrame
def extract_top_to_dataframe(main_df):
    rows = []  # To hold the extracted data
    
    # Loop through each row in the main DataFrame
    for _, row in main_df.iterrows():
        top3_data = row['top_3']  # Access the list directly
        
        # Check if the top1_data is a list
        if isinstance(top3_data, list):
            # Create a dictionary from the extracted key-value pairs
            row_dict = {item['key']: item['value'] for item in top3_data if 'key' in item and 'value' in item}
            rows.append(row_dict)  # Add the dictionary to the rows list
        else:
            print(f"Unexpected format for row: {row}. Expected a list but got {type(top3_data)}")
    
    # Create a new DataFrame from the rows list
    top3_df = pd.DataFrame(rows)
    return top3_df

# Extracting the DataFrame from 'top1'
top3_df = extract_top_to_dataframe(combined_df)

# Display the new DataFrame
print(top3_df)

       Engine  Max Power   Torque Wheel Size Seats     Mileage
0      998 CC  118.36bhp    172nm         16     5         NaN
1     1196 CC      73bhp    101Nm        NaN     7  15.37 kmpl
2      999 CC   98.63bhp    160Nm         16     5     20 kmpl
3     1086 CC   68.05bhp  99.04Nm        NaN     5  19.81 kmpl
4     1199 CC    88.7bhp    110Nm         15     5   18.7 kmpl
...       ...        ...      ...        ...   ...         ...
1414  1197 CC   81.80bhp    113Nm        NaN     5     22 kmpl
1415  1461 CC    83.8bhp    200Nm         16     5  19.87 kmpl
1416  1198 CC   108.5bhp    170Nm         16     5     17 kmpl
1417  1968 CC     141bhp    340Nm         18     5  16.65 kmpl
1418  1995 CC     188bhp    400Nm         18     5  21.76 kmpl

[1419 rows x 6 columns]

In [66]:
import pandas as pd

# Assuming combined_df is your existing DataFrame with a column named 'top_2'
# combined_df = ...  # Your existing DataFrame

def extract_list_of_dicts_to_dataframe(main_df, column_name):
    # Initialize a list to store the extracted data
    extracted_data = []

    for index, row in main_df.iterrows():
        # Check if the cell is a list and not empty
        if isinstance(row[column_name], list) and row[column_name]:
            # Create a dictionary from the extracted values
            row_dict = {item['value']: True for item in row[column_name]}
        else:
            row_dict = {}

        extracted_data.append(row_dict)

    # Create a DataFrame from the extracted data
    extracted_df = pd.DataFrame(extracted_data)

    return extracted_df

# Extract DataFrame for top_2
top_2_df = extract_list_of_dicts_to_dataframe(combined_df, 'top_2')

# Display the DataFrame
print("DataFrame for top_2:")
print(top_2_df)

DataFrame for top_2:
     Power Steering Power Windows Front Air Conditioner Heater  \
0              True                True            True   True
1               NaN                 NaN             NaN   True
2              True                True            True   True
3              True                True            True   True
4              True                True            True   True
...             ...                 ...             ...    ...
1414           True                True            True   True
1415           True                True            True   True
1416           True                True            True   True
1417           True                True            True   True
1418           True                True            True   True

     Adjustable Head Lights Fog Lights Front Anti Lock Braking System  \
0                      True             True                     True
1                      True              NaN                     True
2                      True             True                     True
3                      True             True                      NaN
4                      True             True                     True
...                     ...              ...                      ...
1414                   True              NaN                     True
1415                   True             True                     True
1416                   True             True                     True
1417                   True             True                     True
1418                   True             True                     True

     Brake Assist Radio Low Fuel Warning Light  ... Glove Compartment  \
0            True  True                    NaN  ...               NaN
1             NaN   NaN                   True  ...               NaN
2            True  True                    NaN  ...               NaN
3             NaN   NaN                    NaN  ...               NaN
4             NaN   NaN                    NaN  ...               NaN
...           ...   ...                    ...  ...               ...
1414         True   NaN                    NaN  ...               NaN
1415         True   NaN                    NaN  ...               NaN
1416          NaN  True                    NaN  ...               NaN
1417         True   NaN                    NaN  ...               NaN
1418         True   NaN                    NaN  ...               NaN

     Audio System Remote Control Remote Fuel Lid Opener Wheel Covers  \
0                            NaN                    NaN          NaN
1                            NaN                    NaN          NaN
2                            NaN                    NaN          NaN
3                            NaN                    NaN          NaN
4                            NaN                    NaN          NaN
...                          ...                    ...          ...
1414                         NaN                    NaN          NaN
1415                         NaN                    NaN          NaN
1416                         NaN                    NaN          NaN
1417                         NaN                    NaN          NaN
1418                         NaN                    NaN          NaN

     Rear Window Defogger Rear Seat Headrest Cd Changer Adjustable Seats  \
0                     NaN                NaN        NaN              NaN
1                     NaN                NaN        NaN              NaN
2                     NaN                NaN        NaN              NaN
3                     NaN                NaN        NaN              NaN
4                     NaN                NaN        NaN              NaN
...                   ...                ...        ...              ...
1414                  NaN                NaN        NaN              NaN
1415                  NaN                NaN        NaN              NaN
1416                  NaN                NaN        NaN              NaN
1417                  NaN                NaN        NaN              NaN
1418                  NaN                NaN        NaN              NaN

     Tyre Pressure Monitor Touch Screen
0                      NaN          NaN
1                      NaN          NaN
2                      NaN          NaN
3                      NaN          NaN
4                      NaN          NaN
...                    ...          ...
1414                   NaN          NaN
1415                   NaN          NaN
1416                   NaN          NaN
1417                   NaN          NaN
1418                   NaN          NaN

[1419 rows x 50 columns]

In [67]:
import pandas as pd

# Function to extract and convert 'top1' into a DataFrame
def extract_top_to_dataframe(main_df):
    rows = []  # To hold the extracted data
    
    # Loop through each row in the main DataFrame
    for _, row in main_df.iterrows():
        top_data = row['top']  # Access the list directly
        
        # Check if the top1_data is a list
        if isinstance(top_data, list):
            # Create a dictionary from the extracted key-value pairs
            row_dict = {item['key']: item['value'] for item in top_data if 'key' in item and 'value' in item}
            rows.append(row_dict)  # Add the dictionary to the rows list
        else:
            print(f"Unexpected format for row: {row}. Expected a list but got {type(top_data)}")
    
    # Create a new DataFrame from the rows list
    top_df = pd.DataFrame(rows)
    return top_df

# Extracting the DataFrame from 'top1'
top_df = extract_top_to_dataframe(combined_df)

# Display the new DataFrame
print(top_df)

     Registration Year     Insurance Validity Fuel Type    Seats  Kms Driven  \
0                 2022  Third Party insurance    Petrol  5 Seats  20,000 Kms
1             Feb 2015          Comprehensive    Petrol  7 Seats  20,687 Kms
2                 2021  Third Party insurance    Petrol  5 Seats  30,000 Kms
3             May 2015          Comprehensive    Petrol  5 Seats  59,247 Kms
4                 2015  Third Party insurance    Petrol  5 Seats  50,000 Kms
...                ...                    ...       ...      ...         ...
1414          Jun 2018  Third Party insurance    Petrol  5 Seats  42,891 Kms
1415          Feb 2019  Third Party insurance    Diesel  5 Seats  59,100 Kms
1416          Aug 2018          Not Available    Petrol  5 Seats  55,913 Kms
1417          Aug 2017          Comprehensive    Diesel  5 Seats  65,000 Kms
1418          Oct 2019          Comprehensive    Diesel  5 Seats  60,000 Kms

       RTO    Ownership Engine Displacement Transmission  Year of Manufacture
0     TN02  First Owner              998 cc    Automatic                 2022
1     TN04  First Owner             1196 cc       Manual                 2015
2     TN22  First Owner              999 cc       Manual                 2021
3     TN11  First Owner             1086 cc       Manual                 2015
4     KA03  First Owner             1199 cc       Manual                 2015
...    ...          ...                 ...          ...                  ...
1414  TN09  First Owner             1197 cc    Automatic                 2018
1415  TN11  First Owner             1461 cc       Manual                 2018
1416  TN11  First Owner             1198 cc    Automatic                 2018
1417  TN22  First Owner             1968 cc    Automatic                 2017
1418  TN87  First Owner             1995 cc    Automatic                 2019

[1419 rows x 10 columns]

In [70]:
# Inspect the 'data' column in combined_df
print(combined_df['data'].head(5))  # Display the first 5 rows of the 'data' column

0    [{'heading': 'Comfort & Convenience', 'subHead...
1    [{'heading': 'Comfort & Convenience', 'subHead...
2    [{'heading': 'Comfort & Convenience', 'subHead...
3    [{'heading': 'Comfort & Convenience', 'subHead...
4    [{'heading': 'Comfort & Convenience', 'subHead...
Name: data, dtype: object

In [73]:
import pandas as pd

def extract_data_to_dataframe(main_df, column_name):
    # Create a list to hold the rows for the new DataFrame
    data_rows = []
    
    # Iterate over each row in the main DataFrame
    for index, row in main_df.iterrows():
        # Check if the cell is a list and contains dictionaries
        if isinstance(row[column_name], list) and row[column_name]:
            # Extract the 'list' field from the first dictionary in the row
            list_values = row[column_name][0].get('list', [])
            # Create a dictionary to hold values for this row
            row_dict = {item['value']: True for item in list_values}
            # Append the dictionary to the rows list
            data_rows.append(row_dict)
        else:
            # If there's no data, append an empty dictionary
            data_rows.append({})

    # Create a DataFrame from the list of dictionaries
    data_df = pd.DataFrame(data_rows)

    return data_df

# Extract DataFrame for the 'data' column
data_df = extract_data_to_dataframe(combined_df, 'data')

# Display the DataFrame
print("DataFrame for data:")
print(data_df)

DataFrame for data:
     Power Steering Power Windows Front Power Windows Rear  \
0              True                True               True
1               NaN                 NaN                NaN
2              True                True               True
3              True                True               True
4              True                True               True
...             ...                 ...                ...
1414           True                True               True
1415           True                True               True
1416           True                True               True
1417           True                True               True
1418           True                True               True

     Low Fuel Warning Light Accessory Power Outlet Trunk Light  \
0                      True                   True        True
1                      True                   True         NaN
2                      True                   True        True
3                      True                    NaN         NaN
4                      True                   True        True
...                     ...                    ...         ...
1414                   True                   True         NaN
1415                   True                   True        True
1416                   True                   True         NaN
1417                   True                   True        True
1418                   True                   True        True

     Rear Reading Lamp Rear Seat Headrest Rear Seat Centre Arm Rest  \
0                 True               True                      True
1                  NaN               True                       NaN
2                 True               True                      True
3                  NaN               True                       NaN
4                  NaN               True                       NaN
...                ...                ...                       ...
1414               NaN               True                       NaN
1415              True               True                      True
1416               NaN               True                      True
1417              True               True                      True
1418              True               True                      True

     Cup Holders Rear  ... Remote Climate Control Find My Car Location  \
0                True  ...                    NaN                  NaN
1                 NaN  ...                    NaN                  NaN
2                True  ...                    NaN                  NaN
3                 NaN  ...                    NaN                  NaN
4                True  ...                    NaN                  NaN
...               ...  ...                    ...                  ...
1414              NaN  ...                    NaN                  NaN
1415             True  ...                    NaN                  NaN
1416             True  ...                    NaN                  NaN
1417             True  ...                    NaN                  NaN
1418             True  ...                    NaN                  NaN

     Real Time Vehicle Tracking Power Boot Hands Free Tailgate  \
0                           NaN        NaN                 NaN
1                           NaN        NaN                 NaN
2                           NaN        NaN                 NaN
3                           NaN        NaN                 NaN
4                           NaN        NaN                 NaN
...                         ...        ...                 ...
1414                        NaN        NaN                 NaN
1415                        NaN        NaN                 NaN
1416                        NaN        NaN                 NaN
1417                        NaN        NaN                 NaN
1418                        NaN        NaN                 NaN

     Steering Mounted Tripmeter Remote Horn Light Control  \
0                           NaN                       NaN
1                           NaN                       NaN
2                           NaN                       NaN
3                           NaN                       NaN
4                           NaN                       NaN
...                         ...                       ...
1414                        NaN                       NaN
1415                        NaN                       NaN
1416                        NaN                       NaN
1417                        NaN                       NaN
1418                        NaN                       NaN

     Active Noise Cancellation Power Folding3rd Row Seat Smart Key Band
0                          NaN                       NaN            NaN
1                          NaN                       NaN            NaN
2                          NaN                       NaN            NaN
3                          NaN                       NaN            NaN
4                          NaN                       NaN            NaN
...                        ...                       ...            ...
1414                       NaN                       NaN            NaN
1415                       NaN                       NaN            NaN
1416                       NaN                       NaN            NaN
1417                       NaN                       NaN            NaN
1418                       NaN                       NaN            NaN

[1419 rows x 44 columns]

In [75]:
import pandas as pd

def extract_data2_to_dataframe(main_df, column_name):
    # Create a list to hold the rows for the new DataFrame
    data_rows = []
    
    # Iterate over each row in the main DataFrame
    for index, row in main_df.iterrows():
        # Check if the cell is a list and contains dictionaries
        if isinstance(row[column_name], list) and row[column_name]:
            # Create a dictionary to hold values for this row
            row_dict = {}
            for section in row[column_name]:
                # Extract the 'list' field from each section
                for item in section.get('list', []):
                    # Use the 'key' as the column name and 'value' as the value
                    row_dict[item['key']] = item['value']
            # Append the dictionary to the rows list
            data_rows.append(row_dict)
        else:
            # If there's no data, append an empty dictionary
            data_rows.append({})

    # Create a DataFrame from the list of dictionaries
    data2_df = pd.DataFrame(data_rows)

    return data2_df

# Extract DataFrame for the 'data_2' column
data2_df = extract_data2_to_dataframe(combined_df, 'data_2')

# Display the DataFrame
print("DataFrame for data_2:")
print(data2_df)

DataFrame for data_2:
       Color                               Engine Type Displacement  \
0      Black                  Smartstream G1.0 T - GDi          998
1       Grey                            In-Line Engine         1196
2     Others                     HRA0 1.0 TURBO PETROL          999
3     Silver                              IRDE2 Engine         1086
4     Others                      i-VTEC Petrol Engine         1199
...      ...                                       ...          ...
1414    Blue                               VTVT Engine         1197
1415  Orange                     dCi THP Diesel Engine         1461
1416   White         Revotron 1.2L Turbocharged engine         1198
1417    Grey              Common Rail Direct Injection         1968
1418   White  TwinPower Turbo 4-Cylinder Diesel Engine         1995

              Max Power          Max Torque  No of Cylinder  \
0     118.36bhp@6000rpm  172nm@1500-4000rpm             3.0
1         73bhp@6000rpm       101Nm@3000rpm             4.0
2      98.63bhp@5000rpm  160Nm@2800-3600rpm             3.0
3      68.05bhp@5500rpm     99.04Nm@4500rpm             4.0
4       88.7bhp@6000rpm       110Nm@4800rpm             4.0
...                 ...                 ...             ...
1414   81.80bhp@6000rpm       113Nm@4200rpm             4.0
1415    83.8bhp@3750rpm       200Nm@1750rpm             4.0
1416   108.5bhp@5000rpm  170Nm@1750-4000rpm             3.0
1417     141bhp@4000rpm  340Nm@1750-2750rpm             4.0
1418     188bhp@4000rpm  400Nm@1750-2500rpm             4.0

      Values per Cylinder Fuel Suppy System Turbo Charger  Length  ...  \
0                     4.0               GDi           Yes  3995mm  ...
1                     4.0              MPFi            No  3675mm  ...
2                     4.0              MPFi           Yes  3994mm  ...
3                     3.0              MPFI            No  3585mm  ...
4                     4.0          PGM - Fi            No  3955mm  ...
...                   ...               ...           ...     ...  ...
1414                  4.0              MPFi            No  3840mm  ...
1415                  4.0              CRDi           Yes  4315mm  ...
1416                  4.0              MPFI           Yes  3994mm  ...
1417                  4.0              CRDI           Yes  4486mm  ...
1418                  4.0              CRDi           Yes  4824mm  ...

     Compression Ratio Super Charger Front Tread Rear Tread Gross Weight  \
0                  NaN           NaN         NaN        NaN          NaN
1                9.9:1            No      1280mm     1290mm       1540kg
2                  NaN            No         NaN        NaN          NaN
3                  NaN            No      1400mm     1385mm          NaN
4                  NaN            No         NaN        NaN          NaN
...                ...           ...         ...        ...          ...
1414               NaN            No      1530mm     1530mm       1315kg
1415               NaN            No      1560mm     1567mm       1777kg
1416               NaN            No     1540 mm    1530 mm          NaN
1417               NaN            No      1578mm     1568mm       2250kg
1418               NaN            No     1541 mm    1581 mm          NaN

     Turning Radius    Top Speed  Acceleration  BoreX Stroke  \
0               NaN          NaN           NaN           NaN
1        4.5 metres     145 Kmph  15.7 Seconds           NaN
2               5.0          NaN          11.7   72.2 x 81.3
3        4.7 metres     165 Kmph  14.3 Seconds           NaN
4        5.1 meters     172 Kmph  13.7 Seconds           NaN
...             ...          ...           ...           ...
1414     4.8 Meters          NaN           NaN           NaN
1415     5.2 metres     156 Kmph  13.9 Seconds           NaN
1416           5.1m  154.19 kmph           NaN       77x85.8
1417     5.75meters          NaN           NaN  74.5 x 81 mm
1418     5.5 metres     226 Kmph   7.7 Seconds           NaN

     Ground Clearance Unladen
0                         NaN
1                         NaN
2                         NaN
3                         NaN
4                         NaN
...                       ...
1414                      NaN
1415                      NaN
1416                   209 mm
1417                      NaN
1418                      NaN

[1419 rows x 35 columns]

In [76]:
import pandas as pd

# Assuming combined_df, top_df, top3_df, data2_df, top_2_df, data_df are already defined

# Concatenate the DataFrames column-wise
final_df_chennai = pd.concat([combined_df, top_df, top3_df, data2_df, top_2_df, data_df], axis=1)

# Display the final DataFrame
print("Final DataFrame (final_df_chennai):")
print(final_df_chennai)

Final DataFrame (final_df_chennai):
      it      ft         bt      km transmission  ownerNo      owner  \
0      0  Petrol        SUV  20,000    Automatic        1  1st Owner
1      0  Petrol   Minivans  20,687       Manual        1  1st Owner
2      0  Petrol        SUV  30,000       Manual        1  1st Owner
3      0  Petrol  Hatchback  59,247       Manual        1  1st Owner
4      0  Petrol  Hatchback  50,000       Manual        1  1st Owner
...   ..     ...        ...     ...          ...      ...        ...
1414   0  Petrol  Hatchback  42,891    Automatic        1  1st Owner
1415   0  Diesel        SUV  59,100       Manual        1  1st Owner
1416   0  Petrol        SUV  55,913    Automatic        1  1st Owner
1417   0  Diesel        SUV  65,000    Automatic        1  1st Owner
1418   0  Diesel      Sedan  60,000    Automatic        1  1st Owner

             oem              model  modelYear  ...  Remote Climate Control  \
0            Kia          Kia Sonet       2022  ...                     NaN
1         Maruti        Maruti Eeco       2015  ...                     NaN
2         Nissan     Nissan Magnite       2021  ...                     NaN
3        Hyundai        Hyundai i10       2015  ...                     NaN
4          Honda         Honda Jazz       2015  ...                     NaN
...          ...                ...        ...  ...                     ...
1414      Maruti       Maruti Swift       2018  ...                     NaN
1415     Renault     Renault Duster       2018  ...                     NaN
1416        Tata         Tata Nexon       2018  ...                     NaN
1417  Volkswagen  Volkswagen Tiguan       2017  ...                     NaN
1418         BMW    BMW 3 Series GT       2019  ...                     NaN

     Find My Car Location Real Time Vehicle Tracking Power Boot  \
0                     NaN                        NaN        NaN
1                     NaN                        NaN        NaN
2                     NaN                        NaN        NaN
3                     NaN                        NaN        NaN
4                     NaN                        NaN        NaN
...                   ...                        ...        ...
1414                  NaN                        NaN        NaN
1415                  NaN                        NaN        NaN
1416                  NaN                        NaN        NaN
1417                  NaN                        NaN        NaN
1418                  NaN                        NaN        NaN

     Hands Free Tailgate Steering Mounted Tripmeter Remote Horn Light Control  \
0                    NaN                        NaN                       NaN
1                    NaN                        NaN                       NaN
2                    NaN                        NaN                       NaN
3                    NaN                        NaN                       NaN
4                    NaN                        NaN                       NaN
...                  ...                        ...                       ...
1414                 NaN                        NaN                       NaN
1415                 NaN                        NaN                       NaN
1416                 NaN                        NaN                       NaN
1417                 NaN                        NaN                       NaN
1418                 NaN                        NaN                       NaN

     Active Noise Cancellation Power Folding3rd Row Seat Smart Key Band
0                          NaN                       NaN            NaN
1                          NaN                       NaN            NaN
2                          NaN                       NaN            NaN
3                          NaN                       NaN            NaN
4                          NaN                       NaN            NaN
...                        ...                       ...            ...
1414                       NaN                       NaN            NaN
1415                       NaN                       NaN            NaN
1416                       NaN                       NaN            NaN
1417                       NaN                       NaN            NaN
1418                       NaN                       NaN            NaN

[1419 rows x 175 columns]

In [77]:
# Assuming final_df_chennai is already defined

# Specify the file name
file_name = "final_df_chennai.xlsx"

# Save the DataFrame to an Excel file
final_df_chennai.to_excel(file_name, index=False)

print(f"DataFrame has been saved to {file_name}")

DataFrame has been saved to final_df_chennai.xlsx

In [78]:
########################################################################################################################################################

## Banglore :

In [79]:
import pandas as pd
import ast  # Use ast for safer evaluation of strings to dictionaries

# Step 1: Load your DataFrame from the Excel file
file_path = 'bangalore_cars.xlsx'  # Your Excel file name
df = pd.read_excel(file_path)

# Step 2: Initialize an empty list to hold the structured data
unwound_data = []

# Step 3: Loop through each row of the DataFrame
for index, row in df.iterrows():
    # Initialize a dictionary for the current row
    combined_data = {}
    
    # Specify the columns containing dictionaries
    dict_columns = ['new_car_detail', 'new_car_overview', 'new_car_feature', 'new_car_specs']
    
    # Step 4: Extract and merge dictionaries from the specified columns
    for col in dict_columns:
        try:
            # Safely convert the string representation of the dictionary to an actual dictionary
            dict_value = ast.literal_eval(row[col])  
            if isinstance(dict_value, dict):
                combined_data.update(dict_value)  # Merge the extracted dictionary
        except Exception as e:
            print(f"Error parsing row {index}, column {col}: {e}")

    # Append the combined data for the current row to the unwound data list
    unwound_data.append(combined_data)

# Step 5: Create a DataFrame from the unwound data
unwound_df = pd.DataFrame(unwound_data)

# Optional: Display the unwound DataFrame
print(unwound_df)

# Save the unwound DataFrame to a new Excel file if needed
unwound_df.to_excel('unwound_bangalore_cars.xlsx', index=False)

      it      ft         bt        km transmission  ownerNo      owner  \
0      0  Petrol  Hatchback  1,20,000       Manual        3  3rd Owner
1      0  Petrol        SUV    32,706       Manual        2  2nd Owner
2      0  Petrol  Hatchback    11,949       Manual        1  1st Owner
3      0  Petrol      Sedan    17,794       Manual        1  1st Owner
4      0  Diesel        SUV    60,000       Manual        1  1st Owner
...   ..     ...        ...       ...          ...      ...        ...
1476   0  Diesel        SUV  1,56,039       Manual        2  2nd Owner
1477   0  Petrol      Sedan    56,000       Manual        2  2nd Owner
1478   0  Petrol  Hatchback    42,000       Manual        2  2nd Owner
1479   0  Diesel  Hatchback    93,003       Manual        1  1st Owner
1480   0  Petrol  Hatchback    36,000    Automatic        2  2nd Owner

          oem               model  modelYear  ...         price priceActual  \
0      Maruti      Maruti Celerio       2015  ...      ₹ 4 Lakh
1        Ford       Ford Ecosport       2018  ...   ₹ 8.11 Lakh
2        Tata          Tata Tiago       2018  ...   ₹ 5.85 Lakh
3     Hyundai       Hyundai Xcent       2014  ...   ₹ 4.62 Lakh
4      Maruti  Maruti SX4 S Cross       2015  ...   ₹ 7.90 Lakh
...       ...                 ...        ...  ...           ...         ...
1476   Toyota     Toyota Fortuner       2012  ...  ₹ 16.49 Lakh
1477   Maruti          Maruti SX4       2008  ...   ₹ 3.30 Lakh
1478    Honda          Honda Brio       2014  ...   ₹ 4.25 Lakh
1479  Hyundai         Hyundai i20       2018  ...   ₹ 7.50 Lakh
1480  Hyundai   Hyundai Grand i10       2017  ...   ₹ 6.75 Lakh

     priceSaving priceFixedText  \
0                          None
1                          None
2                          None
3                          None
4                          None
...          ...            ...
1476                       None
1477                       None
1478                       None
1479                       None
1480                       None

                                           trendingText         heading  \
0     {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
1     {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
2     {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
3     {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
4     {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
...                                                 ...             ...
1476  {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
1477  {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
1478  {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
1479  {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
1480  {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications

                                                    top bottomData  \
0     [{'key': 'Mileage', 'value': '23.1 kmpl'}, {'k...       None
1     [{'key': 'Mileage', 'value': '17 kmpl'}, {'key...       None
2     [{'key': 'Mileage', 'value': '23.84 kmpl'}, {'...       None
3     [{'key': 'Mileage', 'value': '19.1 kmpl'}, {'k...       None
4     [{'key': 'Mileage', 'value': '23.65 kmpl'}, {'...       None
...                                                 ...        ...
1476  [{'key': 'Mileage', 'value': '12.55 kmpl'}, {'...       None
1477  [{'key': 'Mileage', 'value': '15 kmpl'}, {'key...       None
1478  [{'key': 'Mileage', 'value': '19.4 kmpl'}, {'k...       None
1479  [{'key': 'Mileage', 'value': '22.54 kmpl'}, {'...       None
1480  [{'key': 'Mileage', 'value': '18.9 kmpl'}, {'k...       None

                                                   data commonIcon
0     [{'heading': 'Engine and Transmission', 'subHe...
1     [{'heading': 'Engine and Transmission', 'subHe...
2     [{'heading': 'Engine and Transmission', 'subHe...
3     [{'heading': 'Engine and Transmission', 'subHe...
4     [{'heading': 'Engine and Transmission', 'subHe...
...                                                 ...        ...
1476  [{'heading': 'Engine and Transmission', 'subHe...
1477  [{'heading': 'Engine and Transmission', 'subHe...
1478  [{'heading': 'Engine and Transmission', 'subHe...
1479  [{'heading': 'Engine and Transmission', 'subHe...
1480  [{'heading': 'Engine and Transmission', 'subHe...

[1481 rows x 22 columns]

In [80]:
import pandas as pd

# Step 1: Read the Excel file
df = pd.read_excel("bangalore_cars.xlsx")

# Step 2: Initialize an empty list to hold structured data
structured_data = []

# Step 3: Loop through each row of the DataFrame
for index, row in df.iterrows():
    row_data = {}
    
    # Convert the string representation of the dictionary to an actual dictionary
    try:
        dict_value = eval(row['new_car_detail'])  # Replace eval with ast.literal_eval for safer evaluation
        if isinstance(dict_value, dict):
            row_data = dict_value
    except Exception as e:
        print(f"Error parsing row {index}: {e}")
        row_data = None

    # Append the row dictionary to the structured data list
    structured_data.append(row_data)

# Step 4: Create a DataFrame from the list of dictionaries in 'new_car_detail'
unwound_df = pd.json_normalize(structured_data)

# Optional: Display the unwound DataFrame
print(unwound_df)

# Save the unwound DataFrame to a new Excel file
#unwound_df.to_excel('unwound_new_car_detail.xlsx', index=False)

      it      ft         bt        km transmission  ownerNo      owner  \
0      0  Petrol  Hatchback  1,20,000       Manual        3  3rd Owner
1      0  Petrol        SUV    32,706       Manual        2  2nd Owner
2      0  Petrol  Hatchback    11,949       Manual        1  1st Owner
3      0  Petrol      Sedan    17,794       Manual        1  1st Owner
4      0  Diesel        SUV    60,000       Manual        1  1st Owner
...   ..     ...        ...       ...          ...      ...        ...
1476   0  Diesel        SUV  1,56,039       Manual        2  2nd Owner
1477   0  Petrol      Sedan    56,000       Manual        2  2nd Owner
1478   0  Petrol  Hatchback    42,000       Manual        2  2nd Owner
1479   0  Diesel  Hatchback    93,003       Manual        1  1st Owner
1480   0  Petrol  Hatchback    36,000    Automatic        2  2nd Owner

          oem               model  modelYear  centralVariantId  \
0      Maruti      Maruti Celerio       2015              3979
1        Ford       Ford Ecosport       2018              6087
2        Tata          Tata Tiago       2018              2983
3     Hyundai       Hyundai Xcent       2014              1867
4      Maruti  Maruti SX4 S Cross       2015              4277
...       ...                 ...        ...               ...
1476   Toyota     Toyota Fortuner       2012              2253
1477   Maruti          Maruti SX4       2008              4257
1478    Honda          Honda Brio       2014              1188
1479  Hyundai         Hyundai i20       2018              5695
1480  Hyundai   Hyundai Grand i10       2017              1523

                   variantName         price priceActual priceSaving  \
0                          VXI      ₹ 4 Lakh
1     1.5 Petrol Titanium BSIV   ₹ 8.11 Lakh
2              1.2 Revotron XZ   ₹ 5.85 Lakh
3           1.2 Kappa S Option   ₹ 4.62 Lakh
4                DDiS 200 Zeta   ₹ 7.90 Lakh
...                        ...           ...         ...         ...
1476                    4x4 MT  ₹ 16.49 Lakh
1477                 Zxi BSIII   ₹ 3.30 Lakh
1478                      S MT   ₹ 4.25 Lakh
1479        1.4 Asta Dual Tone   ₹ 7.50 Lakh
1480            Asta Option AT   ₹ 6.75 Lakh

     priceFixedText                                trendingText.imgUrl  \
0              None  https://stimg.cardekho.com/used-cars/common/ic...
1              None  https://stimg.cardekho.com/used-cars/common/ic...
2              None  https://stimg.cardekho.com/used-cars/common/ic...
3              None  https://stimg.cardekho.com/used-cars/common/ic...
4              None  https://stimg.cardekho.com/used-cars/common/ic...
...             ...                                                ...
1476           None  https://stimg.cardekho.com/used-cars/common/ic...
1477           None  https://stimg.cardekho.com/used-cars/common/ic...
1478           None  https://stimg.cardekho.com/used-cars/common/ic...
1479           None  https://stimg.cardekho.com/used-cars/common/ic...
1480           None  https://stimg.cardekho.com/used-cars/common/ic...

     trendingText.heading                    trendingText.desc
0           Trending Car!  High chances of sale in next 6 days
1           Trending Car!  High chances of sale in next 6 days
2           Trending Car!  High chances of sale in next 6 days
3           Trending Car!  High chances of sale in next 6 days
4           Trending Car!  High chances of sale in next 6 days
...                   ...                                  ...
1476        Trending Car!  High chances of sale in next 6 days
1477        Trending Car!  High chances of sale in next 6 days
1478        Trending Car!  High chances of sale in next 6 days
1479        Trending Car!  High chances of sale in next 6 days
1480        Trending Car!  High chances of sale in next 6 days

[1481 rows x 19 columns]

In [81]:
import pandas as pd

# Step 1: Read the Excel file
df = pd.read_excel("bangalore_cars.xlsx")

# Step 2: Initialize an empty list to hold structured data
structured_data = []

# Step 3: Loop through each row of the DataFrame
for index, row in df.iterrows():
    row_data = {}
    
    # Convert the string representation of the dictionary to an actual dictionary
    try:
        dict_value = eval(row['new_car_overview'])  # Replace eval with ast.literal_eval for safer evaluation
        if isinstance(dict_value, dict):
            row_data = dict_value
    except Exception as e:
        print(f"Error parsing row {index}: {e}")
        row_data = None

    # Append the row dictionary to the structured data list
    structured_data.append(row_data)

# Step 4: Create a DataFrame from the list of dictionaries in 'new_car_detail'
unwound_df1 = pd.json_normalize(structured_data)

# Optional: Display the unwound DataFrame
print(unwound_df1)

# Save the unwound DataFrame to a new Excel file
#unwound_df.to_excel('unwound_new_car_detail.xlsx', index=False)

           heading                                                top  \
0     Car overview  [{'key': 'Registration Year', 'value': '2015',...
1     Car overview  [{'key': 'Registration Year', 'value': 'Feb 20...
2     Car overview  [{'key': 'Registration Year', 'value': 'Sept 2...
3     Car overview  [{'key': 'Registration Year', 'value': 'Dec 20...
4     Car overview  [{'key': 'Registration Year', 'value': '2015',...
...            ...                                                ...
1476  Car overview  [{'key': 'Registration Year', 'value': 'May 20...
1477  Car overview  [{'key': 'Registration Year', 'value': 'Jun 20...
1478  Car overview  [{'key': 'Registration Year', 'value': 'Sept 2...
1479  Car overview  [{'key': 'Registration Year', 'value': 'Dec 20...
1480  Car overview  [{'key': 'Registration Year', 'value': 'May 20...

     bottomData
0          None
1          None
2          None
3          None
4          None
...         ...
1476       None
1477       None
1478       None
1479       None
1480       None

[1481 rows x 3 columns]

In [109]:
import pandas as pd

# Step 1: Read the Excel file
df = pd.read_excel("bangalore_cars.xlsx")

# Step 2: Initialize an empty list to hold structured data
structured_data = []

# Step 3: Loop through each row of the DataFrame
for index, row in df.iterrows():
    row_data = {}
    
    # Convert the string representation of the dictionary to an actual dictionary
    try:
        dict_value = eval(row['new_car_feature'])  # Replace eval with ast.literal_eval for safer evaluation
        if isinstance(dict_value, dict):
            row_data = dict_value
    except Exception as e:
        print(f"Error parsing row {index}: {e}")
        row_data = None

    # Append the row dictionary to the structured data list
    structured_data.append(row_data)

# Step 4: Create a DataFrame from the list of dictionaries in 'new_car_detail'
unwound_df2 = pd.json_normalize(structured_data)

# Optional: Display the unwound DataFrame
print(unwound_df2)

# Save the unwound DataFrame to a new Excel file
#unwound_df.to_excel('unwound_new_car_detail.xlsx', index=False)

       heading                                                top  \
0     Features  [{'value': 'Power Steering'}, {'value': 'Power...
1     Features  [{'value': 'Power Steering'}, {'value': 'Power...
2     Features  [{'value': 'Power Steering'}, {'value': 'Power...
3     Features  [{'value': 'Power Steering'}, {'value': 'Power...
4     Features  [{'value': 'Power Steering'}, {'value': 'Power...
...        ...                                                ...
1476  Features  [{'value': 'Power Steering'}, {'value': 'Power...
1477  Features  [{'value': 'Power Steering'}, {'value': 'Power...
1478  Features  [{'value': 'Power Steering'}, {'value': 'Power...
1479  Features  [{'value': 'Power Steering'}, {'value': 'Power...
1480  Features  [{'value': 'Power Steering'}, {'value': 'Power...

                                                   data  \
0     [{'heading': 'Comfort & Convenience', 'subHead...
1     [{'heading': 'Comfort & Convenience', 'subHead...
2     [{'heading': 'Comfort & Convenience', 'subHead...
3     [{'heading': 'Comfort & Convenience', 'subHead...
4     [{'heading': 'Comfort & Convenience', 'subHead...
...                                                 ...
1476  [{'heading': 'Comfort & Convenience', 'subHead...
1477  [{'heading': 'Comfort & Convenience', 'subHead...
1478  [{'heading': 'Comfort & Convenience', 'subHead...
1479  [{'heading': 'Comfort & Convenience', 'subHead...
1480  [{'heading': 'Comfort & Convenience', 'subHead...

                                             commonIcon
0     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
2     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
3     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
4     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
...                                                 ...
1476  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1477  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1478  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1479  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1480  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg

[1481 rows x 4 columns]

In [110]:
import pandas as pd

# Step 1: Read the Excel file
df = pd.read_excel("bangalore_cars.xlsx")

# Step 2: Initialize an empty list to hold structured data
structured_data = []

# Step 3: Loop through each row of the DataFrame
for index, row in df.iterrows():
    row_data = {}
    
    # Convert the string representation of the dictionary to an actual dictionary
    try:
        dict_value = eval(row['new_car_specs'])  # Replace eval with ast.literal_eval for safer evaluation
        if isinstance(dict_value, dict):
            row_data = dict_value
    except Exception as e:
        print(f"Error parsing row {index}: {e}")
        row_data = None

    # Append the row dictionary to the structured data list
    structured_data.append(row_data)

# Step 4: Create a DataFrame from the list of dictionaries in 'new_car_detail'
unwound_df3 = pd.json_normalize(structured_data)

# Optional: Display the unwound DataFrame
print(unwound_df3)

# Save the unwound DataFrame to a new Excel file
#unwound_df.to_excel('unwound_new_car_detail.xlsx', index=False)

             heading                                                top  \
0     Specifications  [{'key': 'Mileage', 'value': '23.1 kmpl'}, {'k...
1     Specifications  [{'key': 'Mileage', 'value': '17 kmpl'}, {'key...
2     Specifications  [{'key': 'Mileage', 'value': '23.84 kmpl'}, {'...
3     Specifications  [{'key': 'Mileage', 'value': '19.1 kmpl'}, {'k...
4     Specifications  [{'key': 'Mileage', 'value': '23.65 kmpl'}, {'...
...              ...                                                ...
1476  Specifications  [{'key': 'Mileage', 'value': '12.55 kmpl'}, {'...
1477  Specifications  [{'key': 'Mileage', 'value': '15 kmpl'}, {'key...
1478  Specifications  [{'key': 'Mileage', 'value': '19.4 kmpl'}, {'k...
1479  Specifications  [{'key': 'Mileage', 'value': '22.54 kmpl'}, {'...
1480  Specifications  [{'key': 'Mileage', 'value': '18.9 kmpl'}, {'k...

                                                   data commonIcon
0     [{'heading': 'Engine and Transmission', 'subHe...
1     [{'heading': 'Engine and Transmission', 'subHe...
2     [{'heading': 'Engine and Transmission', 'subHe...
3     [{'heading': 'Engine and Transmission', 'subHe...
4     [{'heading': 'Engine and Transmission', 'subHe...
...                                                 ...        ...
1476  [{'heading': 'Engine and Transmission', 'subHe...
1477  [{'heading': 'Engine and Transmission', 'subHe...
1478  [{'heading': 'Engine and Transmission', 'subHe...
1479  [{'heading': 'Engine and Transmission', 'subHe...
1480  [{'heading': 'Engine and Transmission', 'subHe...

[1481 rows x 4 columns]

In [111]:
import pandas as pd

# Assume df1, df2, df3, and df4 are your four DataFrames

# Concatenate the DataFrames column-wise
combined_df = pd.concat([unwound_df, unwound_df1, unwound_df2, unwound_df3], axis=1)

# Optional: Display the combined DataFrame
print(combined_df)

# Save the combined DataFrame to a new Excel file if needed
combined_df.to_excel('combined_data_column_wise_bangalore.xlsx', index=False)

      it      ft         bt        km transmission  ownerNo      owner  \
0      0  Petrol  Hatchback  1,20,000       Manual        3  3rd Owner
1      0  Petrol        SUV    32,706       Manual        2  2nd Owner
2      0  Petrol  Hatchback    11,949       Manual        1  1st Owner
3      0  Petrol      Sedan    17,794       Manual        1  1st Owner
4      0  Diesel        SUV    60,000       Manual        1  1st Owner
...   ..     ...        ...       ...          ...      ...        ...
1476   0  Diesel        SUV  1,56,039       Manual        2  2nd Owner
1477   0  Petrol      Sedan    56,000       Manual        2  2nd Owner
1478   0  Petrol  Hatchback    42,000       Manual        2  2nd Owner
1479   0  Diesel  Hatchback    93,003       Manual        1  1st Owner
1480   0  Petrol  Hatchback    36,000    Automatic        2  2nd Owner

          oem               model  modelYear  ...  \
0      Maruti      Maruti Celerio       2015  ...
1        Ford       Ford Ecosport       2018  ...
2        Tata          Tata Tiago       2018  ...
3     Hyundai       Hyundai Xcent       2014  ...
4      Maruti  Maruti SX4 S Cross       2015  ...
...       ...                 ...        ...  ...
1476   Toyota     Toyota Fortuner       2012  ...
1477   Maruti          Maruti SX4       2008  ...
1478    Honda          Honda Brio       2014  ...
1479  Hyundai         Hyundai i20       2018  ...
1480  Hyundai   Hyundai Grand i10       2017  ...

                                                    top bottomData   heading  \
0     [{'key': 'Registration Year', 'value': '2015',...       None  Features
1     [{'key': 'Registration Year', 'value': 'Feb 20...       None  Features
2     [{'key': 'Registration Year', 'value': 'Sept 2...       None  Features
3     [{'key': 'Registration Year', 'value': 'Dec 20...       None  Features
4     [{'key': 'Registration Year', 'value': '2015',...       None  Features
...                                                 ...        ...       ...
1476  [{'key': 'Registration Year', 'value': 'May 20...       None  Features
1477  [{'key': 'Registration Year', 'value': 'Jun 20...       None  Features
1478  [{'key': 'Registration Year', 'value': 'Sept 2...       None  Features
1479  [{'key': 'Registration Year', 'value': 'Dec 20...       None  Features
1480  [{'key': 'Registration Year', 'value': 'May 20...       None  Features

                                                    top  \
0     [{'value': 'Power Steering'}, {'value': 'Power...
1     [{'value': 'Power Steering'}, {'value': 'Power...
2     [{'value': 'Power Steering'}, {'value': 'Power...
3     [{'value': 'Power Steering'}, {'value': 'Power...
4     [{'value': 'Power Steering'}, {'value': 'Power...
...                                                 ...
1476  [{'value': 'Power Steering'}, {'value': 'Power...
1477  [{'value': 'Power Steering'}, {'value': 'Power...
1478  [{'value': 'Power Steering'}, {'value': 'Power...
1479  [{'value': 'Power Steering'}, {'value': 'Power...
1480  [{'value': 'Power Steering'}, {'value': 'Power...

                                                   data  \
0     [{'heading': 'Comfort & Convenience', 'subHead...
1     [{'heading': 'Comfort & Convenience', 'subHead...
2     [{'heading': 'Comfort & Convenience', 'subHead...
3     [{'heading': 'Comfort & Convenience', 'subHead...
4     [{'heading': 'Comfort & Convenience', 'subHead...
...                                                 ...
1476  [{'heading': 'Comfort & Convenience', 'subHead...
1477  [{'heading': 'Comfort & Convenience', 'subHead...
1478  [{'heading': 'Comfort & Convenience', 'subHead...
1479  [{'heading': 'Comfort & Convenience', 'subHead...
1480  [{'heading': 'Comfort & Convenience', 'subHead...

                                             commonIcon         heading  \
0     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
1     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
2     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
3     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
4     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
...                                                 ...             ...
1476  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
1477  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
1478  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
1479  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
1480  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications

                                                    top  \
0     [{'key': 'Mileage', 'value': '23.1 kmpl'}, {'k...
1     [{'key': 'Mileage', 'value': '17 kmpl'}, {'key...
2     [{'key': 'Mileage', 'value': '23.84 kmpl'}, {'...
3     [{'key': 'Mileage', 'value': '19.1 kmpl'}, {'k...
4     [{'key': 'Mileage', 'value': '23.65 kmpl'}, {'...
...                                                 ...
1476  [{'key': 'Mileage', 'value': '12.55 kmpl'}, {'...
1477  [{'key': 'Mileage', 'value': '15 kmpl'}, {'key...
1478  [{'key': 'Mileage', 'value': '19.4 kmpl'}, {'k...
1479  [{'key': 'Mileage', 'value': '22.54 kmpl'}, {'...
1480  [{'key': 'Mileage', 'value': '18.9 kmpl'}, {'k...

                                                   data commonIcon
0     [{'heading': 'Engine and Transmission', 'subHe...
1     [{'heading': 'Engine and Transmission', 'subHe...
2     [{'heading': 'Engine and Transmission', 'subHe...
3     [{'heading': 'Engine and Transmission', 'subHe...
4     [{'heading': 'Engine and Transmission', 'subHe...
...                                                 ...        ...
1476  [{'heading': 'Engine and Transmission', 'subHe...
1477  [{'heading': 'Engine and Transmission', 'subHe...
1478  [{'heading': 'Engine and Transmission', 'subHe...
1479  [{'heading': 'Engine and Transmission', 'subHe...
1480  [{'heading': 'Engine and Transmission', 'subHe...

[1481 rows x 30 columns]

In [112]:
import pandas as pd

# Example DataFrame with repeating columns (for demonstration purposes)
# combined_df = pd.DataFrame(...)  # Assume this is your existing DataFrame

# Step 1: Get the current column names
original_columns = combined_df.columns

# Step 2: Create a new list to hold unique column names
new_columns = []
column_count = {}

# Step 3: Loop through original columns and create unique names
for col in original_columns:
    if col in column_count:
        column_count[col] += 1
        new_columns.append(f"{col}_{column_count[col]}")  # Append count as suffix
    else:
        column_count[col] = 1
        new_columns.append(col)  # Keep original name for the first occurrence

# Step 4: Assign the new column names to the DataFrame
combined_df.columns = new_columns

# Optional: Display the updated DataFrame columns
print(combined_df.columns)

Index(['it', 'ft', 'bt', 'km', 'transmission', 'ownerNo', 'owner', 'oem',
       'model', 'modelYear', 'centralVariantId', 'variantName', 'price',
       'priceActual', 'priceSaving', 'priceFixedText', 'trendingText.imgUrl',
       'trendingText.heading', 'trendingText.desc', 'heading', 'top',
       'bottomData', 'heading_2', 'top_2', 'data', 'commonIcon', 'heading_3',
       'top_3', 'data_2', 'commonIcon_2'],
      dtype='object')

In [113]:
import pandas as pd

# Function to extract and convert 'top1' into a DataFrame
def extract_top_to_dataframe(main_df):
    rows = []  # To hold the extracted data
    
    # Loop through each row in the main DataFrame
    for _, row in main_df.iterrows():
        top3_data = row['top_3']  # Access the list directly
        
        # Check if the top1_data is a list
        if isinstance(top3_data, list):
            # Create a dictionary from the extracted key-value pairs
            row_dict = {item['key']: item['value'] for item in top3_data if 'key' in item and 'value' in item}
            rows.append(row_dict)  # Add the dictionary to the rows list
        else:
            print(f"Unexpected format for row: {row}. Expected a list but got {type(top3_data)}")
    
    # Create a new DataFrame from the rows list
    top3_df = pd.DataFrame(rows)
    return top3_df

# Extracting the DataFrame from 'top1'
top3_df = extract_top_to_dataframe(combined_df)

# Display the new DataFrame
print(top3_df)

         Mileage   Engine  Max Power    Torque Seats Wheel Size
0      23.1 kmpl   998 CC   67.04bhp      90Nm     5        NaN
1        17 kmpl  1497 CC  121.31bhp     150Nm     5         16
2     23.84 kmpl  1199 CC      84bhp     114Nm     5         14
3      19.1 kmpl  1197 CC   81.86bhp  113.75Nm     5         14
4     23.65 kmpl  1248 CC    88.5bhp     200Nm     5         16
...          ...      ...        ...       ...   ...        ...
1476  12.55 kmpl  2982 CC   168.5bhp     343Nm     7         17
1477     15 kmpl  1586 CC     104.68       145     5         16
1478   19.4 kmpl  1198 CC    86.8bhp     109Nm     5        NaN
1479  22.54 kmpl  1396 CC   88.73bhp   219.7Nm     5         16
1480   18.9 kmpl  1197 CC      82bhp     114Nm     5         14

[1481 rows x 6 columns]

In [114]:
import pandas as pd

# Assuming combined_df is your existing DataFrame with a column named 'top_2'
# combined_df = ...  # Your existing DataFrame

def extract_list_of_dicts_to_dataframe(main_df, column_name):
    # Initialize a list to store the extracted data
    extracted_data = []

    for index, row in main_df.iterrows():
        # Check if the cell is a list and not empty
        if isinstance(row[column_name], list) and row[column_name]:
            # Create a dictionary from the extracted values
            row_dict = {item['value']: True for item in row[column_name]}
        else:
            row_dict = {}

        extracted_data.append(row_dict)

    # Create a DataFrame from the extracted data
    extracted_df = pd.DataFrame(extracted_data)

    return extracted_df

# Extract DataFrame for top_2
top_2_df = extract_list_of_dicts_to_dataframe(combined_df, 'top_2')

# Display the DataFrame
print("DataFrame for top_2:")
print(top_2_df)

DataFrame for top_2:
     Power Steering Power Windows Front Air Conditioner Heater  \
0              True                True            True   True
1              True                True            True   True
2              True                True            True   True
3              True                True            True   True
4              True                True            True   True
...             ...                 ...             ...    ...
1476           True                True            True   True
1477           True                True            True   True
1478           True                True            True   True
1479           True                True            True   True
1480           True                True            True   True

     Adjustable Head Lights Manually Adjustable Exterior Rear View Mirror  \
0                      True                                          True
1                      True                                           NaN
2                      True                                           NaN
3                      True                                           NaN
4                      True                                           NaN
...                     ...                                           ...
1476                   True                                           NaN
1477                    NaN                                           NaN
1478                   True                                           NaN
1479                   True                                           NaN
1480                   True                                           NaN

     Centeral Locking Child Safety Locks Fog Lights Front  \
0                True               True              NaN
1                True                NaN             True
2                True                NaN             True
3                True                NaN             True
4                True                NaN             True
...               ...                ...              ...
1476              NaN                NaN             True
1477              NaN                NaN             True
1478             True                NaN              NaN
1479             True                NaN             True
1480             True                NaN             True

     Anti Lock Braking System  ... Glove Compartment Integrated2Din Audio  \
0                         NaN  ...               NaN                  NaN
1                        True  ...               NaN                  NaN
2                        True  ...               NaN                  NaN
3                        True  ...               NaN                  NaN
4                        True  ...               NaN                  NaN
...                       ...  ...               ...                  ...
1476                     True  ...               NaN                  NaN
1477                     True  ...               NaN                  NaN
1478                      NaN  ...               NaN                  NaN
1479                     True  ...               NaN                  NaN
1480                     True  ...               NaN                  NaN

     Digital Odometer Fabric Upholstery Accessory Power Outlet  \
0                 NaN               NaN                    NaN
1                 NaN               NaN                    NaN
2                 NaN               NaN                    NaN
3                 NaN               NaN                    NaN
4                 NaN               NaN                    NaN
...               ...               ...                    ...
1476              NaN               NaN                    NaN
1477              NaN               NaN                    NaN
1478              NaN               NaN                    NaN
1479              NaN               NaN                    NaN
1480              NaN               NaN                    NaN

     Rear Seat Headrest Speakers Rear Adjustable Steering Anti Theft Alarm  \
0                   NaN           NaN                 NaN              NaN
1                   NaN           NaN                 NaN              NaN
2                   NaN           NaN                 NaN              NaN
3                   NaN           NaN                 NaN              NaN
4                   NaN           NaN                 NaN              NaN
...                 ...           ...                 ...              ...
1476                NaN           NaN                 NaN              NaN
1477                NaN           NaN                 NaN              NaN
1478                NaN           NaN                 NaN              NaN
1479                NaN           NaN                 NaN              NaN
1480                NaN           NaN                 NaN              NaN

     Number Of Speaker
0                  NaN
1                  NaN
2                  NaN
3                  NaN
4                  NaN
...                ...
1476               NaN
1477               NaN
1478               NaN
1479               NaN
1480               NaN

[1481 rows x 52 columns]

In [115]:
import pandas as pd

# Function to extract and convert 'top1' into a DataFrame
def extract_top_to_dataframe(main_df):
    rows = []  # To hold the extracted data
    
    # Loop through each row in the main DataFrame
    for _, row in main_df.iterrows():
        top_data = row['top']  # Access the list directly
        
        # Check if the top1_data is a list
        if isinstance(top_data, list):
            # Create a dictionary from the extracted key-value pairs
            row_dict = {item['key']: item['value'] for item in top_data if 'key' in item and 'value' in item}
            rows.append(row_dict)  # Add the dictionary to the rows list
        else:
            print(f"Unexpected format for row: {row}. Expected a list but got {type(top_data)}")
    
    # Create a new DataFrame from the rows list
    top_df = pd.DataFrame(rows)
    return top_df

# Extracting the DataFrame from 'top1'
top_df = extract_top_to_dataframe(combined_df)

# Display the new DataFrame
print(top_df)

     Registration Year     Insurance Validity Fuel Type    Seats  \
0                 2015  Third Party insurance    Petrol  5 Seats
1             Feb 2018          Comprehensive    Petrol  5 Seats
2            Sept 2018          Comprehensive    Petrol  5 Seats
3             Dec 2014          Comprehensive    Petrol  5 Seats
4                 2015  Third Party insurance    Diesel  5 Seats
...                ...                    ...       ...      ...
1476          May 2012          Comprehensive    Diesel  7 Seats
1477          Jun 2008  Third Party insurance    Petrol  5 Seats
1478         Sept 2014          Comprehensive    Petrol  5 Seats
1479          Dec 2018          Comprehensive    Diesel  5 Seats
1480          May 2017          Comprehensive    Petrol  5 Seats

        Kms Driven   RTO     Ownership Engine Displacement Transmission  \
0     1,20,000 Kms  KA51   Third Owner              998 cc       Manual
1       32,706 Kms  KA05  Second Owner             1497 cc       Manual
2       11,949 Kms  KA03   First Owner             1199 cc       Manual
3       17,794 Kms  KA53   First Owner             1197 cc       Manual
4       60,000 Kms  KA04   First Owner             1248 cc       Manual
...            ...   ...           ...                 ...          ...
1476  1,56,039 Kms  KA01  Second Owner             2982 cc       Manual
1477    56,000 Kms  KA02  Second Owner             1586 cc       Manual
1478    42,000 Kms  KA03  Second Owner             1198 cc       Manual
1479    93,003 Kms  KA03   First Owner             1396 cc       Manual
1480    36,000 Kms  KA04  Second Owner             1197 cc    Automatic

      Year of Manufacture
0                  2015.0
1                  2018.0
2                  2018.0
3                  2014.0
4                  2015.0
...                   ...
1476               2012.0
1477               2008.0
1478               2014.0
1479               2018.0
1480               2017.0

[1481 rows x 10 columns]

In [116]:
import pandas as pd

def extract_data_to_dataframe(main_df, column_name):
    # Create a list to hold the rows for the new DataFrame
    data_rows = []
    
    # Iterate over each row in the main DataFrame
    for index, row in main_df.iterrows():
        # Check if the cell is a list and contains dictionaries
        if isinstance(row[column_name], list) and row[column_name]:
            # Extract the 'list' field from the first dictionary in the row
            list_values = row[column_name][0].get('list', [])
            # Create a dictionary to hold values for this row
            row_dict = {item['value']: True for item in list_values}
            # Append the dictionary to the rows list
            data_rows.append(row_dict)
        else:
            # If there's no data, append an empty dictionary
            data_rows.append({})

    # Create a DataFrame from the list of dictionaries
    data_df = pd.DataFrame(data_rows)

    return data_df

# Extract DataFrame for the 'data' column
data_df = extract_data_to_dataframe(combined_df, 'data')

# Display the DataFrame
print("DataFrame for data:")
print(data_df)

DataFrame for data:
     Power Steering Power Windows Front Power Windows Rear  \
0              True                True               True
1              True                True               True
2              True                True               True
3              True                True               True
4              True                True               True
...             ...                 ...                ...
1476           True                True               True
1477           True                True               True
1478           True                True               True
1479           True                True               True
1480           True                True               True

     Remote Trunk Opener Remote Fuel Lid Opener Low Fuel Warning Light  \
0                   True                   True                   True
1                   True                   True                   True
2                   True                   True                   True
3                   True                    NaN                   True
4                   True                   True                   True
...                  ...                    ...                    ...
1476                True                   True                   True
1477                True                   True                   True
1478                True                   True                   True
1479                True                   True                   True
1480                True                    NaN                   True

     Accessory Power Outlet Vanity Mirror Rear Seat Headrest  \
0                      True          True               True
1                      True          True               True
2                      True          True               True
3                      True          True               True
4                      True          True               True
...                     ...           ...                ...
1476                   True          True               True
1477                   True          True               True
1478                   True          True               True
1479                   True          True               True
1480                   True          True               True

     Cup Holders Front  ... Hands Free Tailgate Power Boot  \
0                 True  ...                 NaN        NaN
1                 True  ...                 NaN        NaN
2                 True  ...                 NaN        NaN
3                 True  ...                 NaN        NaN
4                 True  ...                 NaN        NaN
...                ...  ...                 ...        ...
1476              True  ...                 NaN        NaN
1477              True  ...                 NaN        NaN
1478              True  ...                 NaN        NaN
1479              True  ...                 NaN        NaN
1480              True  ...                 NaN        NaN

     Remote Engine Start Stop Steering Mounted Tripmeter  \
0                         NaN                        NaN
1                         NaN                        NaN
2                         NaN                        NaN
3                         NaN                        NaN
4                         NaN                        NaN
...                       ...                        ...
1476                      NaN                        NaN
1477                      NaN                        NaN
1478                      NaN                        NaN
1479                      NaN                        NaN
1480                      NaN                        NaN

     Remote Climate Control Remote Horn Light Control Find My Car Location  \
0                       NaN                       NaN                  NaN
1                       NaN                       NaN                  NaN
2                       NaN                       NaN                  NaN
3                       NaN                       NaN                  NaN
4                       NaN                       NaN                  NaN
...                     ...                       ...                  ...
1476                    NaN                       NaN                  NaN
1477                    NaN                       NaN                  NaN
1478                    NaN                       NaN                  NaN
1479                    NaN                       NaN                  NaN
1480                    NaN                       NaN                  NaN

     Real Time Vehicle Tracking Smart Key Band Power Folding3rd Row Seat
0                           NaN            NaN                       NaN
1                           NaN            NaN                       NaN
2                           NaN            NaN                       NaN
3                           NaN            NaN                       NaN
4                           NaN            NaN                       NaN
...                         ...            ...                       ...
1476                        NaN            NaN                       NaN
1477                        NaN            NaN                       NaN
1478                        NaN            NaN                       NaN
1479                        NaN            NaN                       NaN
1480                        NaN            NaN                       NaN

[1481 rows x 44 columns]

In [117]:
import pandas as pd

def extract_data2_to_dataframe(main_df, column_name):
    # Create a list to hold the rows for the new DataFrame
    data_rows = []
    
    # Iterate over each row in the main DataFrame
    for index, row in main_df.iterrows():
        # Check if the cell is a list and contains dictionaries
        if isinstance(row[column_name], list) and row[column_name]:
            # Create a dictionary to hold values for this row
            row_dict = {}
            for section in row[column_name]:
                # Extract the 'list' field from each section
                for item in section.get('list', []):
                    # Use the 'key' as the column name and 'value' as the value
                    row_dict[item['key']] = item['value']
            # Append the dictionary to the rows list
            data_rows.append(row_dict)
        else:
            # If there's no data, append an empty dictionary
            data_rows.append({})

    # Create a DataFrame from the list of dictionaries
    data2_df = pd.DataFrame(data_rows)

    return data2_df

# Extract DataFrame for the 'data_2' column
data2_df = extract_data2_to_dataframe(combined_df, 'data_2')

# Display the DataFrame
print("DataFrame for data_2:")
print(data2_df)

DataFrame for data_2:
       Color               Engine Type Displacement              Max Power  \
0      White               K10B Engine          998       67.04bhp@6000rpm
1      White      Ti-VCT Petrol Engine         1497      121.31bhp@6500rpm
2        Red           Revotron Engine         1199          84bhp@6000rpm
3     Others  Kappa VTVT Petrol Engine         1197       81.86bhp@6000rpm
4       Gray    DDiS 200 Diesel Engine         1248        88.5bhp@4000rpm
...      ...                       ...          ...                    ...
1476    Blue        D-4D Diesel Engine         2982       168.5bhp@3600rpm
1477     Red            In-Line Engine         1586  104.68@5,600 (PS@rpm)
1478   White             i-VTEC Engine         1198        86.8bhp@6000rpm
1479     Red     U2 CRDI Diesel Engine         1396       88.73bhp@4000rpm
1480   White  Kappa VTVT Petrol Engine         1197          82bhp@6000rpm

                Max Torque  No of Cylinder  Values per Cylinder  \
0             90Nm@3500rpm             3.0                  4.0
1            150Nm@4500rpm             3.0                  4.0
2            114Nm@3500rpm             3.0                  4.0
3         113.75Nm@4000rpm             4.0                  4.0
4            200Nm@1750rpm             4.0                  4.0
...                    ...             ...                  ...
1476    343Nm@1400-3400rpm             4.0                  4.0
1477   145@4,100 (kgm@rpm)             4.0                  4.0
1478         109Nm@4500rpm             4.0                  4.0
1479  219.7Nm@1500-2750rpm             4.0                  4.0
1480         114Nm@4000rpm             4.0                  4.0

     Value Configuration Fuel Suppy System  BoreX Stroke  ... Turning Radius  \
0                   DOHC              MPFi    73 X 82 mm  ...     4.7 metres
1                   DOHC  Direct Injection  79 X 76.5 mm  ...     5.3 metres
2                   DOHC              MPFi  77 X 85.8 mm  ...     4.9 meters
3                   DOHC  Direct Injection           NaN  ...     4.7 metres
4                   DOHC               NaN  69.6 x 82 mm  ...     5.2 meters
...                  ...               ...           ...  ...            ...
1476                DOHC              CRDi           NaN  ...     5.9 metres
1477                DOHC              MPFI    78 x 83 mm  ...          5.3 m
1478                SOHC          PGM - Fi           NaN  ...     4.5 metres
1479                DOHC              CRDI           NaN  ...     5.2 metres
1480                DOHC              MPFI           NaN  ...     4.8 metres

     Front Brake Type Rear Brake Type Top Speed   Acceleration  \
0     Ventilated Disc            Drum  150 Kmph  15.05 Seconds
1     Ventilated Disc            Drum       NaN            NaN
2                Disc            Drum  150 kmph   14.3 Seconds
3               Disc             Drum  172km/hr   14.2 Seconds
4     Ventilated Disc      Solid Disc  190 Kmph     12 Seconds
...               ...             ...       ...            ...
1476  Ventilated Disc            Drum  176 Kmph    9.6 Seconds
1477  Ventilated Disc            Drum  177 kmph   12.1 seconds
1478             Disc            Drum  164 Kmph   14.5 Seconds
1479             Disc            Drum  180 Kmph   11.9 Seconds
1480             Disc            Drum  165 Kmph   12.9 Seconds

             Tyre Type No Door Numbers Cargo Volumn Alloy Wheel Size  \
0     Tubeless, Radial               5   235-litres              NaN
1      Tubeless,Radial               4   352-litres               16
2             Tubeless               5   242-litres               14
3      Tubeless,Radial               4   407-litres               14
4      Tubeless,Radial               5   353-litres               16
...                ...             ...          ...              ...
1476   Tubeless,Radial               5   296-litres               17
1477  Tubeless, Radial               4   505 litres               16
1478   Tubeless,Radial               5   175-litres              NaN
1479          Tubeless               5   295-litres               16
1480          Tubeless               5   256-liters               14

     Ground Clearance Unladen
0                         NaN
1                         NaN
2                         NaN
3                         NaN
4                         NaN
...                       ...
1476                      NaN
1477                      NaN
1478                      NaN
1479                      NaN
1480                      NaN

[1481 rows x 35 columns]

In [118]:
import pandas as pd

# Assuming combined_df, top_df, top3_df, data2_df, top_2_df, data_df are already defined

# Concatenate the DataFrames column-wise
final_df_bangalore = pd.concat([combined_df, top_df, top3_df, data2_df, top_2_df, data_df], axis=1)

# Display the final DataFrame
print("Final DataFrame (final_df_bangalore):")
print(final_df_bangalore)

Final DataFrame (final_df_bangalore):
      it      ft         bt        km transmission  ownerNo      owner  \
0      0  Petrol  Hatchback  1,20,000       Manual        3  3rd Owner
1      0  Petrol        SUV    32,706       Manual        2  2nd Owner
2      0  Petrol  Hatchback    11,949       Manual        1  1st Owner
3      0  Petrol      Sedan    17,794       Manual        1  1st Owner
4      0  Diesel        SUV    60,000       Manual        1  1st Owner
...   ..     ...        ...       ...          ...      ...        ...
1476   0  Diesel        SUV  1,56,039       Manual        2  2nd Owner
1477   0  Petrol      Sedan    56,000       Manual        2  2nd Owner
1478   0  Petrol  Hatchback    42,000       Manual        2  2nd Owner
1479   0  Diesel  Hatchback    93,003       Manual        1  1st Owner
1480   0  Petrol  Hatchback    36,000    Automatic        2  2nd Owner

          oem               model  modelYear  ...  Hands Free Tailgate  \
0      Maruti      Maruti Celerio       2015  ...                  NaN
1        Ford       Ford Ecosport       2018  ...                  NaN
2        Tata          Tata Tiago       2018  ...                  NaN
3     Hyundai       Hyundai Xcent       2014  ...                  NaN
4      Maruti  Maruti SX4 S Cross       2015  ...                  NaN
...       ...                 ...        ...  ...                  ...
1476   Toyota     Toyota Fortuner       2012  ...                  NaN
1477   Maruti          Maruti SX4       2008  ...                  NaN
1478    Honda          Honda Brio       2014  ...                  NaN
1479  Hyundai         Hyundai i20       2018  ...                  NaN
1480  Hyundai   Hyundai Grand i10       2017  ...                  NaN

     Power Boot Remote Engine Start Stop Steering Mounted Tripmeter  \
0           NaN                      NaN                        NaN
1           NaN                      NaN                        NaN
2           NaN                      NaN                        NaN
3           NaN                      NaN                        NaN
4           NaN                      NaN                        NaN
...         ...                      ...                        ...
1476        NaN                      NaN                        NaN
1477        NaN                      NaN                        NaN
1478        NaN                      NaN                        NaN
1479        NaN                      NaN                        NaN
1480        NaN                      NaN                        NaN

     Remote Climate Control Remote Horn Light Control Find My Car Location  \
0                       NaN                       NaN                  NaN
1                       NaN                       NaN                  NaN
2                       NaN                       NaN                  NaN
3                       NaN                       NaN                  NaN
4                       NaN                       NaN                  NaN
...                     ...                       ...                  ...
1476                    NaN                       NaN                  NaN
1477                    NaN                       NaN                  NaN
1478                    NaN                       NaN                  NaN
1479                    NaN                       NaN                  NaN
1480                    NaN                       NaN                  NaN

     Real Time Vehicle Tracking Smart Key Band Power Folding3rd Row Seat
0                           NaN            NaN                       NaN
1                           NaN            NaN                       NaN
2                           NaN            NaN                       NaN
3                           NaN            NaN                       NaN
4                           NaN            NaN                       NaN
...                         ...            ...                       ...
1476                        NaN            NaN                       NaN
1477                        NaN            NaN                       NaN
1478                        NaN            NaN                       NaN
1479                        NaN            NaN                       NaN
1480                        NaN            NaN                       NaN

[1481 rows x 177 columns]

In [119]:
## # Assuming final_df_chennai is already defined

# Specify the file name
file_name = "final_df_bangalore.xlsx"

# Save the DataFrame to an Excel file
final_df_bangalore.to_excel(file_name, index=False)

print(f"DataFrame has been saved to {file_name}")

DataFrame has been saved to final_df_bangalore.xlsx

## Delhi

In [120]:
import pandas as pd
import ast  # Use ast for safer evaluation of strings to dictionaries

# Step 1: Load your DataFrame from the Excel file
file_path = 'delhi_cars.xlsx'  # Your Excel file name
df = pd.read_excel(file_path)

# Step 2: Initialize an empty list to hold the structured data
unwound_data = []

# Step 3: Loop through each row of the DataFrame
for index, row in df.iterrows():
    # Initialize a dictionary for the current row
    combined_data = {}
    
    # Specify the columns containing dictionaries
    dict_columns = ['new_car_detail', 'new_car_overview', 'new_car_feature', 'new_car_specs']
    
    # Step 4: Extract and merge dictionaries from the specified columns
    for col in dict_columns:
        try:
            # Safely convert the string representation of the dictionary to an actual dictionary
            dict_value = ast.literal_eval(row[col])  
            if isinstance(dict_value, dict):
                combined_data.update(dict_value)  # Merge the extracted dictionary
        except Exception as e:
            print(f"Error parsing row {index}, column {col}: {e}")

    # Append the combined data for the current row to the unwound data list
    unwound_data.append(combined_data)

# Step 5: Create a DataFrame from the unwound data
unwound_df = pd.DataFrame(unwound_data)

# Optional: Display the unwound DataFrame
print(unwound_df)

# Save the unwound DataFrame to a new Excel file if needed
#unwound_df.to_excel('unwound_bangalore_cars.xlsx', index=False)

      it      ft         bt      km transmission  ownerNo      owner  \
0      0  Diesel        SUV  10,000    Automatic        1  1st Owner
1      0  Petrol        SUV  57,437       Manual        2  2nd Owner
2      0  Petrol        SUV   8,000    Automatic        1  1st Owner
3      0  Petrol  Hatchback  28,151       Manual        2  2nd Owner
4      0  Petrol        SUV  60,000       Manual        1  1st Owner
...   ..     ...        ...     ...          ...      ...        ...
1480   0  Petrol      Sedan  60,000    Automatic        1  1st Owner
1481   0  Petrol        SUV  20,000       Manual        1  1st Owner
1482   0  Petrol      Sedan  60,000       Manual        1  1st Owner
1483   0  Diesel        SUV  38,000       Manual        1  1st Owner
1484   0  Diesel        SUV   7,000    Automatic        0  0th Owner

                oem              model  modelYear  ...         price  \
0               Kia         Kia Seltos       2022  ...     ₹ 19 Lakh
1           Hyundai      Hyundai Creta       2016  ...   ₹ 7.62 Lakh
2     Mercedes-Benz  Mercedes-Benz GLC       2020  ...     ₹ 56 Lakh
3            Maruti       Maruti Swift       2018  ...   ₹ 5.23 Lakh
4           Hyundai      Hyundai Creta       2017  ...   ₹ 7.65 Lakh
...             ...                ...        ...  ...           ...
1480          Honda         Honda City       2019  ...      ₹ 9 Lakh
1481            Kia          Kia Sonet       2021  ...   ₹ 9.50 Lakh
1482        Hyundai      Hyundai Verna       2011  ...   ₹ 4.18 Lakh
1483        Hyundai      Hyundai Creta       2019  ...  ₹ 11.95 Lakh
1484             MG         MG Gloster       2023  ...  ₹ 46.40 Lakh

     priceActual priceSaving priceFixedText  \
0                                      None
1                                      None
2                                      None
3                                      None
4                                      None
...          ...         ...            ...
1480                                   None
1481                                   None
1482                                   None
1483                                   None
1484                                   None

                                           trendingText         heading  \
0     {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
1     {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
2     {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
3     {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
4     {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
...                                                 ...             ...
1480  {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
1481  {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
1482  {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
1483  {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
1484  {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications

                                                    top bottomData  \
0     [{'key': 'Mileage', 'value': '18 kmpl'}, {'key...       None
1     [{'key': 'Mileage', 'value': '15.29 kmpl'}, {'...       None
2     [{'key': 'Mileage', 'value': '12.74 kmpl'}, {'...       None
3     [{'key': 'Mileage', 'value': '22.38 kmpl'}, {'...       None
4     [{'key': 'Mileage', 'value': '15.29 kmpl'}, {'...       None
...                                                 ...        ...
1480  [{'key': 'Mileage', 'value': '18 kmpl'}, {'key...       None
1481  [{'key': 'Mileage', 'value': '18.4 kmpl'}, {'k...       None
1482  [{'key': 'Mileage', 'value': '17.01 kmpl'}, {'...       None
1483  [{'key': 'Mileage', 'value': '20.5 kmpl'}, {'k...       None
1484  [{'key': 'Mileage', 'value': '12.04 kmpl'}, {'...       None

                                                   data commonIcon
0     [{'heading': 'Engine and Transmission', 'subHe...
1     [{'heading': 'Engine and Transmission', 'subHe...
2     [{'heading': 'Engine and Transmission', 'subHe...
3     [{'heading': 'Engine and Transmission', 'subHe...
4     [{'heading': 'Engine and Transmission', 'subHe...
...                                                 ...        ...
1480  [{'heading': 'Engine and Transmission', 'subHe...
1481  [{'heading': 'Engine and Transmission', 'subHe...
1482  [{'heading': 'Engine and Transmission', 'subHe...
1483  [{'heading': 'Engine and Transmission', 'subHe...
1484  [{'heading': 'Engine and Transmission', 'subHe...

[1485 rows x 22 columns]

In [121]:
import pandas as pd

# Step 1: Read the Excel file
df = pd.read_excel("delhi_cars.xlsx")

# Step 2: Initialize an empty list to hold structured data
structured_data = []

# Step 3: Loop through each row of the DataFrame
for index, row in df.iterrows():
    row_data = {}
    
    # Convert the string representation of the dictionary to an actual dictionary
    try:
        dict_value = eval(row['new_car_detail'])  # Replace eval with ast.literal_eval for safer evaluation
        if isinstance(dict_value, dict):
            row_data = dict_value
    except Exception as e:
        print(f"Error parsing row {index}: {e}")
        row_data = None

    # Append the row dictionary to the structured data list
    structured_data.append(row_data)

# Step 4: Create a DataFrame from the list of dictionaries in 'new_car_detail'
unwound_df = pd.json_normalize(structured_data)

# Optional: Display the unwound DataFrame
print(unwound_df)

# Save the unwound DataFrame to a new Excel file
#unwound_df.to_excel('unwound_new_car_detail.xlsx', index=False)

      it      ft         bt      km transmission  ownerNo      owner  \
0      0  Diesel        SUV  10,000    Automatic        1  1st Owner
1      0  Petrol        SUV  57,437       Manual        2  2nd Owner
2      0  Petrol        SUV   8,000    Automatic        1  1st Owner
3      0  Petrol  Hatchback  28,151       Manual        2  2nd Owner
4      0  Petrol        SUV  60,000       Manual        1  1st Owner
...   ..     ...        ...     ...          ...      ...        ...
1480   0  Petrol      Sedan  60,000    Automatic        1  1st Owner
1481   0  Petrol        SUV  20,000       Manual        1  1st Owner
1482   0  Petrol      Sedan  60,000       Manual        1  1st Owner
1483   0  Diesel        SUV  38,000       Manual        1  1st Owner
1484   0  Diesel        SUV   7,000    Automatic        0  0th Owner

                oem              model  modelYear  centralVariantId  \
0               Kia         Kia Seltos       2022              7121
1           Hyundai      Hyundai Creta       2016              1449
2     Mercedes-Benz  Mercedes-Benz GLC       2020              6837
3            Maruti       Maruti Swift       2018             10403
4           Hyundai      Hyundai Creta       2017              5362
...             ...                ...        ...               ...
1480          Honda         Honda City       2019              5627
1481            Kia          Kia Sonet       2021              8000
1482        Hyundai      Hyundai Verna       2011              1832
1483        Hyundai      Hyundai Creta       2019              6440
1484             MG         MG Gloster       2023              9298

               variantName         price priceActual priceSaving  \
0       GTX Plus Diesel AT     ₹ 19 Lakh
1               1.6 VTVT S   ₹ 7.62 Lakh
2                      200     ₹ 56 Lakh
3                      VXI   ₹ 5.23 Lakh
4          1.6 VTVT E Plus   ₹ 7.65 Lakh
...                    ...           ...         ...         ...
1480          i-VTEC CVT V      ₹ 9 Lakh
1481         HTK Plus BSVI   ₹ 9.50 Lakh
1482           1.6 SX VTVT   ₹ 4.18 Lakh
1483  1.6 SX Option Diesel  ₹ 11.95 Lakh
1484       Savvy 6 Str 4x4  ₹ 46.40 Lakh

     priceFixedText                                trendingText.imgUrl  \
0              None  https://stimg.cardekho.com/used-cars/common/ic...
1              None  https://stimg.cardekho.com/used-cars/common/ic...
2              None  https://stimg.cardekho.com/used-cars/common/ic...
3              None  https://stimg.cardekho.com/used-cars/common/ic...
4              None  https://stimg.cardekho.com/used-cars/common/ic...
...             ...                                                ...
1480           None  https://stimg.cardekho.com/used-cars/common/ic...
1481           None  https://stimg.cardekho.com/used-cars/common/ic...
1482           None  https://stimg.cardekho.com/used-cars/common/ic...
1483           None  https://stimg.cardekho.com/used-cars/common/ic...
1484           None  https://stimg.cardekho.com/used-cars/common/ic...

     trendingText.heading                    trendingText.desc
0           Trending Car!  High chances of sale in next 6 days
1           Trending Car!  High chances of sale in next 6 days
2           Trending Car!  High chances of sale in next 6 days
3           Trending Car!  High chances of sale in next 6 days
4           Trending Car!  High chances of sale in next 6 days
...                   ...                                  ...
1480        Trending Car!  High chances of sale in next 6 days
1481        Trending Car!  High chances of sale in next 6 days
1482        Trending Car!  High chances of sale in next 6 days
1483        Trending Car!  High chances of sale in next 6 days
1484        Trending Car!  High chances of sale in next 6 days

[1485 rows x 19 columns]

In [122]:
import pandas as pd

# Step 1: Read the Excel file
df = pd.read_excel("delhi_cars.xlsx")

# Step 2: Initialize an empty list to hold structured data
structured_data = []

# Step 3: Loop through each row of the DataFrame
for index, row in df.iterrows():
    row_data = {}
    
    # Convert the string representation of the dictionary to an actual dictionary
    try:
        dict_value = eval(row['new_car_overview'])  # Replace eval with ast.literal_eval for safer evaluation
        if isinstance(dict_value, dict):
            row_data = dict_value
    except Exception as e:
        print(f"Error parsing row {index}: {e}")
        row_data = None

    # Append the row dictionary to the structured data list
    structured_data.append(row_data)

# Step 4: Create a DataFrame from the list of dictionaries in 'new_car_detail'
unwound_df1 = pd.json_normalize(structured_data)

# Optional: Display the unwound DataFrame
print(unwound_df1)

# Save the unwound DataFrame to a new Excel file
#unwound_df.to_excel('unwound_new_car_detail.xlsx', index=False)

           heading                                                top  \
0     Car overview  [{'key': 'Registration Year', 'value': '2022',...
1     Car overview  [{'key': 'Registration Year', 'value': 'May 20...
2     Car overview  [{'key': 'Registration Year', 'value': 'Dec 20...
3     Car overview  [{'key': 'Registration Year', 'value': 'Jan 20...
4     Car overview  [{'key': 'Registration Year', 'value': '2017',...
...            ...                                                ...
1480  Car overview  [{'key': 'Registration Year', 'value': '2019',...
1481  Car overview  [{'key': 'Registration Year', 'value': '2021',...
1482  Car overview  [{'key': 'Registration Year', 'value': '2011',...
1483  Car overview  [{'key': 'Registration Year', 'value': 'Oct 20...
1484  Car overview  [{'key': 'Insurance Validity', 'value': 'Third...

     bottomData
0          None
1          None
2          None
3          None
4          None
...         ...
1480       None
1481       None
1482       None
1483       None
1484       None

[1485 rows x 3 columns]

In [123]:
import pandas as pd

# Step 1: Read the Excel file
df = pd.read_excel("delhi_cars.xlsx")

# Step 2: Initialize an empty list to hold structured data
structured_data = []

# Step 3: Loop through each row of the DataFrame
for index, row in df.iterrows():
    row_data = {}
    
    # Convert the string representation of the dictionary to an actual dictionary
    try:
        dict_value = eval(row['new_car_feature'])  # Replace eval with ast.literal_eval for safer evaluation
        if isinstance(dict_value, dict):
            row_data = dict_value
    except Exception as e:
        print(f"Error parsing row {index}: {e}")
        row_data = None

    # Append the row dictionary to the structured data list
    structured_data.append(row_data)

# Step 4: Create a DataFrame from the list of dictionaries in 'new_car_detail'
unwound_df2 = pd.json_normalize(structured_data)

# Optional: Display the unwound DataFrame
print(unwound_df2)

# Save the unwound DataFrame to a new Excel file
#unwound_df.to_excel('unwound_new_car_detail.xlsx', index=False)

       heading                                                top  \
0     Features  [{'value': 'Power Steering'}, {'value': 'Power...
1     Features  [{'value': 'Power Steering'}, {'value': 'Power...
2     Features  [{'value': 'Power Steering'}, {'value': 'Power...
3     Features  [{'value': 'Power Steering'}, {'value': 'Power...
4     Features  [{'value': 'Power Steering'}, {'value': 'Power...
...        ...                                                ...
1480  Features  [{'value': 'Power Steering'}, {'value': 'Power...
1481  Features  [{'value': 'Power Steering'}, {'value': 'Power...
1482  Features  [{'value': 'Power Steering'}, {'value': 'Power...
1483  Features  [{'value': 'Power Steering'}, {'value': 'Power...
1484  Features  [{'value': 'Power Steering'}, {'value': 'Power...

                                                   data  \
0     [{'heading': 'Comfort & Convenience', 'subHead...
1     [{'heading': 'Comfort & Convenience', 'subHead...
2     [{'heading': 'Comfort & Convenience', 'subHead...
3     [{'heading': 'Comfort & Convenience', 'subHead...
4     [{'heading': 'Comfort & Convenience', 'subHead...
...                                                 ...
1480  [{'heading': 'Comfort & Convenience', 'subHead...
1481  [{'heading': 'Comfort & Convenience', 'subHead...
1482  [{'heading': 'Comfort & Convenience', 'subHead...
1483  [{'heading': 'Comfort & Convenience', 'subHead...
1484  [{'heading': 'Comfort & Convenience', 'subHead...

                                             commonIcon
0     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
2     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
3     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
4     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
...                                                 ...
1480  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1481  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1482  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1483  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1484  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg

[1485 rows x 4 columns]

In [124]:
import pandas as pd

# Step 1: Read the Excel file
df = pd.read_excel("delhi_cars.xlsx")

# Step 2: Initialize an empty list to hold structured data
structured_data = []

# Step 3: Loop through each row of the DataFrame
for index, row in df.iterrows():
    row_data = {}
    
    # Convert the string representation of the dictionary to an actual dictionary
    try:
        dict_value = eval(row['new_car_specs'])  # Replace eval with ast.literal_eval for safer evaluation
        if isinstance(dict_value, dict):
            row_data = dict_value
    except Exception as e:
        print(f"Error parsing row {index}: {e}")
        row_data = None

    # Append the row dictionary to the structured data list
    structured_data.append(row_data)

# Step 4: Create a DataFrame from the list of dictionaries in 'new_car_detail'
unwound_df3 = pd.json_normalize(structured_data)

# Optional: Display the unwound DataFrame
print(unwound_df3)

# Save the unwound DataFrame to a new Excel file
#unwound_df.to_excel('unwound_new_car_detail.xlsx', index=False)

             heading                                                top  \
0     Specifications  [{'key': 'Mileage', 'value': '18 kmpl'}, {'key...
1     Specifications  [{'key': 'Mileage', 'value': '15.29 kmpl'}, {'...
2     Specifications  [{'key': 'Mileage', 'value': '12.74 kmpl'}, {'...
3     Specifications  [{'key': 'Mileage', 'value': '22.38 kmpl'}, {'...
4     Specifications  [{'key': 'Mileage', 'value': '15.29 kmpl'}, {'...
...              ...                                                ...
1480  Specifications  [{'key': 'Mileage', 'value': '18 kmpl'}, {'key...
1481  Specifications  [{'key': 'Mileage', 'value': '18.4 kmpl'}, {'k...
1482  Specifications  [{'key': 'Mileage', 'value': '17.01 kmpl'}, {'...
1483  Specifications  [{'key': 'Mileage', 'value': '20.5 kmpl'}, {'k...
1484  Specifications  [{'key': 'Mileage', 'value': '12.04 kmpl'}, {'...

                                                   data commonIcon
0     [{'heading': 'Engine and Transmission', 'subHe...
1     [{'heading': 'Engine and Transmission', 'subHe...
2     [{'heading': 'Engine and Transmission', 'subHe...
3     [{'heading': 'Engine and Transmission', 'subHe...
4     [{'heading': 'Engine and Transmission', 'subHe...
...                                                 ...        ...
1480  [{'heading': 'Engine and Transmission', 'subHe...
1481  [{'heading': 'Engine and Transmission', 'subHe...
1482  [{'heading': 'Engine and Transmission', 'subHe...
1483  [{'heading': 'Engine and Transmission', 'subHe...
1484  [{'heading': 'Engine and Transmission', 'subHe...

[1485 rows x 4 columns]

In [125]:
import pandas as pd

# Assume df1, df2, df3, and df4 are your four DataFrames

# Concatenate the DataFrames column-wise
combined_df = pd.concat([unwound_df, unwound_df1, unwound_df2, unwound_df3], axis=1)

# Optional: Display the combined DataFrame
print(combined_df)

# Save the combined DataFrame to a new Excel file if needed
combined_df.to_excel('combined_data_column_wise_delhi.xlsx', index=False)

      it      ft         bt      km transmission  ownerNo      owner  \
0      0  Diesel        SUV  10,000    Automatic        1  1st Owner
1      0  Petrol        SUV  57,437       Manual        2  2nd Owner
2      0  Petrol        SUV   8,000    Automatic        1  1st Owner
3      0  Petrol  Hatchback  28,151       Manual        2  2nd Owner
4      0  Petrol        SUV  60,000       Manual        1  1st Owner
...   ..     ...        ...     ...          ...      ...        ...
1480   0  Petrol      Sedan  60,000    Automatic        1  1st Owner
1481   0  Petrol        SUV  20,000       Manual        1  1st Owner
1482   0  Petrol      Sedan  60,000       Manual        1  1st Owner
1483   0  Diesel        SUV  38,000       Manual        1  1st Owner
1484   0  Diesel        SUV   7,000    Automatic        0  0th Owner

                oem              model  modelYear  ...  \
0               Kia         Kia Seltos       2022  ...
1           Hyundai      Hyundai Creta       2016  ...
2     Mercedes-Benz  Mercedes-Benz GLC       2020  ...
3            Maruti       Maruti Swift       2018  ...
4           Hyundai      Hyundai Creta       2017  ...
...             ...                ...        ...  ...
1480          Honda         Honda City       2019  ...
1481            Kia          Kia Sonet       2021  ...
1482        Hyundai      Hyundai Verna       2011  ...
1483        Hyundai      Hyundai Creta       2019  ...
1484             MG         MG Gloster       2023  ...

                                                    top bottomData   heading  \
0     [{'key': 'Registration Year', 'value': '2022',...       None  Features
1     [{'key': 'Registration Year', 'value': 'May 20...       None  Features
2     [{'key': 'Registration Year', 'value': 'Dec 20...       None  Features
3     [{'key': 'Registration Year', 'value': 'Jan 20...       None  Features
4     [{'key': 'Registration Year', 'value': '2017',...       None  Features
...                                                 ...        ...       ...
1480  [{'key': 'Registration Year', 'value': '2019',...       None  Features
1481  [{'key': 'Registration Year', 'value': '2021',...       None  Features
1482  [{'key': 'Registration Year', 'value': '2011',...       None  Features
1483  [{'key': 'Registration Year', 'value': 'Oct 20...       None  Features
1484  [{'key': 'Insurance Validity', 'value': 'Third...       None  Features

                                                    top  \
0     [{'value': 'Power Steering'}, {'value': 'Power...
1     [{'value': 'Power Steering'}, {'value': 'Power...
2     [{'value': 'Power Steering'}, {'value': 'Power...
3     [{'value': 'Power Steering'}, {'value': 'Power...
4     [{'value': 'Power Steering'}, {'value': 'Power...
...                                                 ...
1480  [{'value': 'Power Steering'}, {'value': 'Power...
1481  [{'value': 'Power Steering'}, {'value': 'Power...
1482  [{'value': 'Power Steering'}, {'value': 'Power...
1483  [{'value': 'Power Steering'}, {'value': 'Power...
1484  [{'value': 'Power Steering'}, {'value': 'Power...

                                                   data  \
0     [{'heading': 'Comfort & Convenience', 'subHead...
1     [{'heading': 'Comfort & Convenience', 'subHead...
2     [{'heading': 'Comfort & Convenience', 'subHead...
3     [{'heading': 'Comfort & Convenience', 'subHead...
4     [{'heading': 'Comfort & Convenience', 'subHead...
...                                                 ...
1480  [{'heading': 'Comfort & Convenience', 'subHead...
1481  [{'heading': 'Comfort & Convenience', 'subHead...
1482  [{'heading': 'Comfort & Convenience', 'subHead...
1483  [{'heading': 'Comfort & Convenience', 'subHead...
1484  [{'heading': 'Comfort & Convenience', 'subHead...

                                             commonIcon         heading  \
0     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
1     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
2     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
3     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
4     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
...                                                 ...             ...
1480  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
1481  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
1482  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
1483  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
1484  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications

                                                    top  \
0     [{'key': 'Mileage', 'value': '18 kmpl'}, {'key...
1     [{'key': 'Mileage', 'value': '15.29 kmpl'}, {'...
2     [{'key': 'Mileage', 'value': '12.74 kmpl'}, {'...
3     [{'key': 'Mileage', 'value': '22.38 kmpl'}, {'...
4     [{'key': 'Mileage', 'value': '15.29 kmpl'}, {'...
...                                                 ...
1480  [{'key': 'Mileage', 'value': '18 kmpl'}, {'key...
1481  [{'key': 'Mileage', 'value': '18.4 kmpl'}, {'k...
1482  [{'key': 'Mileage', 'value': '17.01 kmpl'}, {'...
1483  [{'key': 'Mileage', 'value': '20.5 kmpl'}, {'k...
1484  [{'key': 'Mileage', 'value': '12.04 kmpl'}, {'...

                                                   data commonIcon
0     [{'heading': 'Engine and Transmission', 'subHe...
1     [{'heading': 'Engine and Transmission', 'subHe...
2     [{'heading': 'Engine and Transmission', 'subHe...
3     [{'heading': 'Engine and Transmission', 'subHe...
4     [{'heading': 'Engine and Transmission', 'subHe...
...                                                 ...        ...
1480  [{'heading': 'Engine and Transmission', 'subHe...
1481  [{'heading': 'Engine and Transmission', 'subHe...
1482  [{'heading': 'Engine and Transmission', 'subHe...
1483  [{'heading': 'Engine and Transmission', 'subHe...
1484  [{'heading': 'Engine and Transmission', 'subHe...

[1485 rows x 30 columns]

In [126]:
import pandas as pd

# Example DataFrame with repeating columns (for demonstration purposes)
# combined_df = pd.DataFrame(...)  # Assume this is your existing DataFrame

# Step 1: Get the current column names
original_columns = combined_df.columns

# Step 2: Create a new list to hold unique column names
new_columns = []
column_count = {}

# Step 3: Loop through original columns and create unique names
for col in original_columns:
    if col in column_count:
        column_count[col] += 1
        new_columns.append(f"{col}_{column_count[col]}")  # Append count as suffix
    else:
        column_count[col] = 1
        new_columns.append(col)  # Keep original name for the first occurrence

# Step 4: Assign the new column names to the DataFrame
combined_df.columns = new_columns

# Optional: Display the updated DataFrame columns
print(combined_df.columns)

Index(['it', 'ft', 'bt', 'km', 'transmission', 'ownerNo', 'owner', 'oem',
       'model', 'modelYear', 'centralVariantId', 'variantName', 'price',
       'priceActual', 'priceSaving', 'priceFixedText', 'trendingText.imgUrl',
       'trendingText.heading', 'trendingText.desc', 'heading', 'top',
       'bottomData', 'heading_2', 'top_2', 'data', 'commonIcon', 'heading_3',
       'top_3', 'data_2', 'commonIcon_2'],
      dtype='object')

In [127]:
import pandas as pd

# Function to extract and convert 'top1' into a DataFrame
def extract_top_to_dataframe(main_df):
    rows = []  # To hold the extracted data
    
    # Loop through each row in the main DataFrame
    for _, row in main_df.iterrows():
        top3_data = row['top_3']  # Access the list directly
        
        # Check if the top1_data is a list
        if isinstance(top3_data, list):
            # Create a dictionary from the extracted key-value pairs
            row_dict = {item['key']: item['value'] for item in top3_data if 'key' in item and 'value' in item}
            rows.append(row_dict)  # Add the dictionary to the rows list
        else:
            print(f"Unexpected format for row: {row}. Expected a list but got {type(top3_data)}")
    
    # Create a new DataFrame from the rows list
    top3_df = pd.DataFrame(rows)
    return top3_df

# Extracting the DataFrame from 'top1'
top3_df = extract_top_to_dataframe(combined_df)

# Display the new DataFrame
print(top3_df)

         Mileage   Engine  Max Power    Torque Wheel Size Seats
0        18 kmpl  1493 CC  113.43bhp     250Nm         17     5
1     15.29 kmpl  1591 CC   121.3bhp     151Nm        NaN     5
2     12.74 kmpl  1991 CC     197bhp     320nm         19     5
3     22.38 kmpl  1197 CC   88.50bhp     113Nm        NaN     5
4     15.29 kmpl  1591 CC   121.3bhp     151Nm        NaN     5
...          ...      ...        ...       ...        ...   ...
1480     18 kmpl  1497 CC   117.6bhp     145Nm         15     5
1481   18.4 kmpl  1197 CC   81.86bhp     115Nm        NaN     5
1482  17.01 kmpl  1591 CC   121.3bhp   154.9Nm         16     5
1483   20.5 kmpl  1582 CC   126.2bhp  259.87NM         17     5
1484  12.04 kmpl  1996 CC  212.55bhp   478.5Nm         19     6

[1485 rows x 6 columns]

In [128]:
import pandas as pd

# Assuming combined_df is your existing DataFrame with a column named 'top_2'
# combined_df = ...  # Your existing DataFrame

def extract_list_of_dicts_to_dataframe(main_df, column_name):
    # Initialize a list to store the extracted data
    extracted_data = []

    for index, row in main_df.iterrows():
        # Check if the cell is a list and not empty
        if isinstance(row[column_name], list) and row[column_name]:
            # Create a dictionary from the extracted values
            row_dict = {item['value']: True for item in row[column_name]}
        else:
            row_dict = {}

        extracted_data.append(row_dict)

    # Create a DataFrame from the extracted data
    extracted_df = pd.DataFrame(extracted_data)

    return extracted_df

# Extract DataFrame for top_2
top_2_df = extract_list_of_dicts_to_dataframe(combined_df, 'top_2')

# Display the DataFrame
print("DataFrame for top_2:")
print(top_2_df)

DataFrame for top_2:
     Power Steering Power Windows Front Air Conditioner Heater  \
0              True                True            True   True
1              True                True            True   True
2              True                True            True   True
3              True                True            True   True
4              True                True            True   True
...             ...                 ...             ...    ...
1480           True                True            True   True
1481           True                True            True   True
1482           True                True            True   True
1483           True                True            True   True
1484           True                True            True   True

     Adjustable Head Lights Fog Lights Front Anti Lock Braking System  \
0                      True             True                     True
1                      True             True                     True
2                      True             True                     True
3                      True              NaN                     True
4                      True              NaN                     True
...                     ...              ...                      ...
1480                   True             True                     True
1481                   True             True                     True
1482                   True             True                     True
1483                   True             True                     True
1484                   True             True                     True

     Brake Assist Radio Centeral Locking  ... Usb Auxiliary Input  \
0            True  True              NaN  ...                 NaN
1             NaN   NaN             True  ...                 NaN
2            True  True              NaN  ...                 NaN
3            True  True              NaN  ...                 NaN
4             NaN   NaN             True  ...                 NaN
...           ...   ...              ...  ...                 ...
1480          NaN  True             True  ...                 NaN
1481          NaN  True             True  ...                 NaN
1482          NaN   NaN             True  ...                 NaN
1483          NaN  True             True  ...                 NaN
1484         True  True              NaN  ...                 NaN

     Rear Seat Belts Digital Odometer Digital Clock Passenger Air Bag  \
0                NaN              NaN           NaN               NaN
1                NaN              NaN           NaN               NaN
2                NaN              NaN           NaN               NaN
3                NaN              NaN           NaN               NaN
4                NaN              NaN           NaN               NaN
...              ...              ...           ...               ...
1480             NaN              NaN           NaN               NaN
1481             NaN              NaN           NaN               NaN
1482             NaN              NaN           NaN               NaN
1483             NaN              NaN           NaN               NaN
1484             NaN              NaN           NaN               NaN

     Rear Window Wiper Glove Compartment Bluetooth Rear Seat Headrest  \
0                  NaN               NaN       NaN                NaN
1                  NaN               NaN       NaN                NaN
2                  NaN               NaN       NaN                NaN
3                  NaN               NaN       NaN                NaN
4                  NaN               NaN       NaN                NaN
...                ...               ...       ...                ...
1480               NaN               NaN       NaN                NaN
1481               NaN               NaN       NaN                NaN
1482               NaN               NaN       NaN                NaN
1483               NaN               NaN       NaN                NaN
1484               NaN               NaN       NaN                NaN

     Integrated2Din Audio
0                     NaN
1                     NaN
2                     NaN
3                     NaN
4                     NaN
...                   ...
1480                  NaN
1481                  NaN
1482                  NaN
1483                  NaN
1484                  NaN

[1485 rows x 60 columns]

In [129]:
import pandas as pd

# Function to extract and convert 'top1' into a DataFrame
def extract_top_to_dataframe(main_df):
    rows = []  # To hold the extracted data
    
    # Loop through each row in the main DataFrame
    for _, row in main_df.iterrows():
        top_data = row['top']  # Access the list directly
        
        # Check if the top1_data is a list
        if isinstance(top_data, list):
            # Create a dictionary from the extracted key-value pairs
            row_dict = {item['key']: item['value'] for item in top_data if 'key' in item and 'value' in item}
            rows.append(row_dict)  # Add the dictionary to the rows list
        else:
            print(f"Unexpected format for row: {row}. Expected a list but got {type(top_data)}")
    
    # Create a new DataFrame from the rows list
    top_df = pd.DataFrame(rows)
    return top_df

# Extracting the DataFrame from 'top1'
top_df = extract_top_to_dataframe(combined_df)

# Display the new DataFrame
print(top_df)

     Registration Year     Insurance Validity Fuel Type    Seats  Kms Driven  \
0                 2022  Third Party insurance    Diesel  5 Seats  10,000 Kms
1             May 2016               Zero Dep    Petrol  5 Seats  57,437 Kms
2             Dec 2020          Comprehensive    Petrol  5 Seats   8,000 Kms
3             Jan 2019          Comprehensive    Petrol  5 Seats  28,151 Kms
4                 2017  Third Party insurance    Petrol  5 Seats  60,000 Kms
...                ...                    ...       ...      ...         ...
1480              2019  Third Party insurance    Petrol  5 Seats  60,000 Kms
1481              2021  Third Party insurance    Petrol  5 Seats  20,000 Kms
1482              2011  Third Party insurance    Petrol  5 Seats  60,000 Kms
1483          Oct 2019  Third Party insurance    Diesel  5 Seats  38,000 Kms
1484               NaN  Third Party insurance    Diesel  6 Seats   7,000 Kms

         Ownership Engine Displacement Transmission  Year of Manufacture   RTO
0      First Owner             1493 cc    Automatic                 2022   NaN
1     Second Owner             1591 cc       Manual                 2016  HR51
2      First Owner             1991 cc    Automatic                 2020  DL01
3     Second Owner             1197 cc       Manual                 2018  DL4C
4      First Owner             1591 cc       Manual                 2017  DL8C
...            ...                 ...          ...                  ...   ...
1480   First Owner             1497 cc    Automatic                 2019  DL4C
1481   First Owner             1197 cc       Manual                 2021   NaN
1482   First Owner             1591 cc       Manual                 2011   NaN
1483   First Owner             1582 cc       Manual                 2019  HR26
1484           NaN             1996 cc    Automatic                 2023   NaN

[1485 rows x 10 columns]

In [130]:
import pandas as pd

def extract_data_to_dataframe(main_df, column_name):
    # Create a list to hold the rows for the new DataFrame
    data_rows = []
    
    # Iterate over each row in the main DataFrame
    for index, row in main_df.iterrows():
        # Check if the cell is a list and contains dictionaries
        if isinstance(row[column_name], list) and row[column_name]:
            # Extract the 'list' field from the first dictionary in the row
            list_values = row[column_name][0].get('list', [])
            # Create a dictionary to hold values for this row
            row_dict = {item['value']: True for item in list_values}
            # Append the dictionary to the rows list
            data_rows.append(row_dict)
        else:
            # If there's no data, append an empty dictionary
            data_rows.append({})

    # Create a DataFrame from the list of dictionaries
    data_df = pd.DataFrame(data_rows)

    return data_df

# Extract DataFrame for the 'data' column
data_df = extract_data_to_dataframe(combined_df, 'data')

# Display the DataFrame
print("DataFrame for data:")
print(data_df)

DataFrame for data:
     Power Steering Power Windows Front Power Windows Rear  \
0              True                True               True
1              True                True               True
2              True                True               True
3              True                True               True
4              True                True               True
...             ...                 ...                ...
1480           True                True               True
1481           True                True               True
1482           True                True               True
1483           True                True               True
1484           True                True               True

     Air Quality Control Low Fuel Warning Light Accessory Power Outlet  \
0                   True                   True                   True
1                    NaN                   True                   True
2                   True                   True                   True
3                    NaN                   True                   True
4                    NaN                   True                   True
...                  ...                    ...                    ...
1480                True                   True                   True
1481                 NaN                   True                   True
1482                True                   True                   True
1483                True                   True                   True
1484                 NaN                   True                   True

     Trunk Light Rear Reading Lamp Rear Seat Headrest  \
0           True              True               True
1           True               NaN               True
2           True              True               True
3            NaN               NaN               True
4           True               NaN               True
...          ...               ...                ...
1480        True               NaN               True
1481         NaN              True               True
1482        True               NaN               True
1483        True              True               True
1484        True              True               True

     Rear Seat Centre Arm Rest  ... Power Boot Battery Saver  \
0                         True  ...        NaN           NaN
1                         True  ...        NaN           NaN
2                         True  ...        NaN           NaN
3                          NaN  ...       True           NaN
4                          NaN  ...        NaN          True
...                        ...  ...        ...           ...
1480                      True  ...        NaN           NaN
1481                       NaN  ...        NaN          True
1482                      True  ...        NaN           NaN
1483                      True  ...        NaN          True
1484                      True  ...       True           NaN

     Steering Mounted Tripmeter Find My Car Location  \
0                           NaN                  NaN
1                           NaN                  NaN
2                           NaN                  NaN
3                           NaN                  NaN
4                           NaN                  NaN
...                         ...                  ...
1480                        NaN                  NaN
1481                        NaN                  NaN
1482                        NaN                  NaN
1483                        NaN                  NaN
1484                        NaN                 True

     Remote Horn Light Control Hands Free Tailgate Real Time Vehicle Tracking  \
0                          NaN                 NaN                        NaN
1                          NaN                 NaN                        NaN
2                          NaN                 NaN                        NaN
3                          NaN                 NaN                        NaN
4                          NaN                 NaN                        NaN
...                        ...                 ...                        ...
1480                       NaN                 NaN                        NaN
1481                       NaN                 NaN                        NaN
1482                       NaN                 NaN                        NaN
1483                       NaN                 NaN                        NaN
1484                       NaN                True                        NaN

     Active Noise Cancellation Power Folding3rd Row Seat Smart Key Band
0                          NaN                       NaN            NaN
1                          NaN                       NaN            NaN
2                          NaN                       NaN            NaN
3                          NaN                       NaN            NaN
4                          NaN                       NaN            NaN
...                        ...                       ...            ...
1480                       NaN                       NaN            NaN
1481                       NaN                       NaN            NaN
1482                       NaN                       NaN            NaN
1483                       NaN                       NaN            NaN
1484                       NaN                       NaN            NaN

[1485 rows x 44 columns]

In [131]:
import pandas as pd

def extract_data2_to_dataframe(main_df, column_name):
    # Create a list to hold the rows for the new DataFrame
    data_rows = []
    
    # Iterate over each row in the main DataFrame
    for index, row in main_df.iterrows():
        # Check if the cell is a list and contains dictionaries
        if isinstance(row[column_name], list) and row[column_name]:
            # Create a dictionary to hold values for this row
            row_dict = {}
            for section in row[column_name]:
                # Extract the 'list' field from each section
                for item in section.get('list', []):
                    # Use the 'key' as the column name and 'value' as the value
                    row_dict[item['key']] = item['value']
            # Append the dictionary to the rows list
            data_rows.append(row_dict)
        else:
            # If there's no data, append an empty dictionary
            data_rows.append({})

    # Create a DataFrame from the list of dictionaries
    data2_df = pd.DataFrame(data_rows)

    return data2_df

# Extract DataFrame for the 'data_2' column
data2_df = extract_data2_to_dataframe(combined_df, 'data_2')

# Display the DataFrame
print("DataFrame for data_2:")
print(data2_df)

DataFrame for data_2:
       Color             Engine Type Displacement            Max Power  \
0       Gray          1.5 L CRDi VGT         1493    113.43bhp@4000rpm
1      White      VTVT Petrol Engine         1591     121.3bhp@6400rpm
2       Grey     M 264 petrol engine         1991  197bhp@5500-6100rpm
3     Silver       K Series Dual jet         1197     88.50bhp@6000rpm
4      White      VTVT Petrol Engine         1591     121.3bhp@6400rpm
...      ...                     ...          ...                  ...
1480  Others           i VTEC Engine         1497     117.6bhp@6600rpm
1481  Others        SMARTSTREAM G1.2         1197     81.86bhp@6000rpm
1482  Others      VTVT Petrol Engine         1591     121.3bhp@6300rpm
1483  Silver      U2 CRDI VGT Engine         1582     126.2bhp@4000rpm
1484    Grey  DIESEL 2.0L TWIN TURBO         1996    212.55bhp@4000rpm

                 Max Torque  No of Cylinder  Values per Cylinder  \
0        250Nm@1500-2750rpm             4.0                  4.0
1             151Nm@4850rpm             4.0                  4.0
2        320nm@1650-4000rpm             4.0                  4.0
3             113Nm@4400rpm             4.0                  4.0
4             151Nm@4850rpm             4.0                  4.0
...                     ...             ...                  ...
1480          145Nm@4600rpm             4.0                  4.0
1481          115Nm@4200rpm             4.0                  4.0
1482        154.9Nm@4200rpm             4.0                  4.0
1483  259.87NM@1500-3000rpm             4.0                  4.0
1484   478.5Nm@1500-2400rpm             4.0                  4.0

     Fuel Suppy System Turbo Charger  Length  ... Super Charger  \
0                 CRDi           Yes  4315mm  ...           NaN
1                 MPFI            No  4270mm  ...            No
2                  EFI            No  4658mm  ...           NaN
3                  NaN           NaN  3845mm  ...           NaN
4                 MPFI            No  4270mm  ...            No
...                ...           ...     ...  ...           ...
1480            PGM-Fi            No  4440mm  ...            No
1481               MPI            No  3995mm  ...           NaN
1482              MPFI            No  4375mm  ...            No
1483              CRDi           Yes  4270mm  ...            No
1484               NaN          Twin  4985mm  ...           NaN

     Turning Radius   Top Speed  Acceleration Gross Weight Front Tread  \
0               NaN         NaN           NaN          NaN         NaN
1        5.3 metres    165 Kmph  10.5 Seconds          NaN         NaN
2               NaN    217 Kmph           NaN       2360kg         NaN
3               4.8         NaN           NaN         1335        1530
4        5.3 metres    165 Kmph  10.5 Seconds          NaN         NaN
...             ...         ...           ...          ...         ...
1480     5.3 metres    195 Kmph    10 Seconds       1455kg      1490mm
1481            NaN         NaN           NaN          NaN         NaN
1482     5.2 metres    196km/hr  10.5 Seconds          NaN         NaN
1483     5.3 metres  160.58kmph       10.83 s          NaN         NaN
1484            NaN         NaN           NaN          NaN         NaN

     Rear Tread      BoreX Stroke Compression Ratio Ground Clearance Unladen
0           NaN               NaN               NaN                      NaN
1           NaN               NaN               NaN                      NaN
2           NaN               NaN               NaN                      NaN
3          1530               NaN               NaN                      NaN
4           NaN               NaN               NaN                      NaN
...         ...               ...               ...                      ...
1480     1480mm    73.0 X 89.4 mm            10.3:1                      NaN
1481        NaN               NaN               NaN                      NaN
1482        NaN  77.0mm X 85.44mm            10.5;1                      NaN
1483        NaN               NaN               NaN                    190mm
1484        NaN               NaN               NaN                      NaN

[1485 rows x 35 columns]

In [132]:
import pandas as pd

# Assuming combined_df, top_df, top3_df, data2_df, top_2_df, data_df are already defined

# Concatenate the DataFrames column-wise
final_df_delhi = pd.concat([combined_df, top_df, top3_df, data2_df, top_2_df, data_df], axis=1)

# Display the final DataFrame
print("Final DataFrame (final_df_delhi):")
print(final_df_delhi)

Final DataFrame (final_df_delhi):
      it      ft         bt      km transmission  ownerNo      owner  \
0      0  Diesel        SUV  10,000    Automatic        1  1st Owner
1      0  Petrol        SUV  57,437       Manual        2  2nd Owner
2      0  Petrol        SUV   8,000    Automatic        1  1st Owner
3      0  Petrol  Hatchback  28,151       Manual        2  2nd Owner
4      0  Petrol        SUV  60,000       Manual        1  1st Owner
...   ..     ...        ...     ...          ...      ...        ...
1480   0  Petrol      Sedan  60,000    Automatic        1  1st Owner
1481   0  Petrol        SUV  20,000       Manual        1  1st Owner
1482   0  Petrol      Sedan  60,000       Manual        1  1st Owner
1483   0  Diesel        SUV  38,000       Manual        1  1st Owner
1484   0  Diesel        SUV   7,000    Automatic        0  0th Owner

                oem              model  modelYear  ...  Power Boot  \
0               Kia         Kia Seltos       2022  ...         NaN
1           Hyundai      Hyundai Creta       2016  ...         NaN
2     Mercedes-Benz  Mercedes-Benz GLC       2020  ...         NaN
3            Maruti       Maruti Swift       2018  ...        True
4           Hyundai      Hyundai Creta       2017  ...         NaN
...             ...                ...        ...  ...         ...
1480          Honda         Honda City       2019  ...         NaN
1481            Kia          Kia Sonet       2021  ...         NaN
1482        Hyundai      Hyundai Verna       2011  ...         NaN
1483        Hyundai      Hyundai Creta       2019  ...         NaN
1484             MG         MG Gloster       2023  ...        True

     Battery Saver Steering Mounted Tripmeter Find My Car Location  \
0              NaN                        NaN                  NaN
1              NaN                        NaN                  NaN
2              NaN                        NaN                  NaN
3              NaN                        NaN                  NaN
4             True                        NaN                  NaN
...            ...                        ...                  ...
1480           NaN                        NaN                  NaN
1481          True                        NaN                  NaN
1482           NaN                        NaN                  NaN
1483          True                        NaN                  NaN
1484           NaN                        NaN                 True

     Remote Horn Light Control Hands Free Tailgate Real Time Vehicle Tracking  \
0                          NaN                 NaN                        NaN
1                          NaN                 NaN                        NaN
2                          NaN                 NaN                        NaN
3                          NaN                 NaN                        NaN
4                          NaN                 NaN                        NaN
...                        ...                 ...                        ...
1480                       NaN                 NaN                        NaN
1481                       NaN                 NaN                        NaN
1482                       NaN                 NaN                        NaN
1483                       NaN                 NaN                        NaN
1484                       NaN                True                        NaN

     Active Noise Cancellation Power Folding3rd Row Seat Smart Key Band
0                          NaN                       NaN            NaN
1                          NaN                       NaN            NaN
2                          NaN                       NaN            NaN
3                          NaN                       NaN            NaN
4                          NaN                       NaN            NaN
...                        ...                       ...            ...
1480                       NaN                       NaN            NaN
1481                       NaN                       NaN            NaN
1482                       NaN                       NaN            NaN
1483                       NaN                       NaN            NaN
1484                       NaN                       NaN            NaN

[1485 rows x 185 columns]

In [133]:
## # Assuming final_df_chennai is already defined

# Specify the file name
file_name = "final_df_delhi.xlsx"

# Save the DataFrame to an Excel file
final_df_delhi.to_excel(file_name, index=False)

print(f"DataFrame has been saved to {file_name}")

DataFrame has been saved to final_df_delhi.xlsx

## Hyderabad:

In [134]:
## import pandas as pd
import ast  # Use ast for safer evaluation of strings to dictionaries

# Step 1: Load your DataFrame from the Excel file
file_path = 'hyderabad_cars.xlsx'  # Your Excel file name
df = pd.read_excel(file_path)

# Step 2: Initialize an empty list to hold the structured data
unwound_data = []

# Step 3: Loop through each row of the DataFrame
for index, row in df.iterrows():
    # Initialize a dictionary for the current row
    combined_data = {}
    
    # Specify the columns containing dictionaries
    dict_columns = ['new_car_detail', 'new_car_overview', 'new_car_feature', 'new_car_specs']
    
    # Step 4: Extract and merge dictionaries from the specified columns
    for col in dict_columns:
        try:
            # Safely convert the string representation of the dictionary to an actual dictionary
            dict_value = ast.literal_eval(row[col])  
            if isinstance(dict_value, dict):
                combined_data.update(dict_value)  # Merge the extracted dictionary
        except Exception as e:
            print(f"Error parsing row {index}, column {col}: {e}")

    # Append the combined data for the current row to the unwound data list
    unwound_data.append(combined_data)

# Step 5: Create a DataFrame from the unwound data
unwound_df = pd.DataFrame(unwound_data)

# Optional: Display the unwound DataFrame
print(unwound_df)

# Save the unwound DataFrame to a new Excel file if needed
#unwound_df.to_excel('unwound_bangalore_cars.xlsx', index=False)

      it      ft         bt        km transmission  ownerNo      owner  \
0      0  Petrol  Hatchback    20,000    Automatic        1  1st Owner
1      0  Petrol  Hatchback    85,582       Manual        2  2nd Owner
2      0  Petrol        SUV    10,000       Manual        1  1st Owner
3      0  Petrol  Hatchback    50,750       Manual        1  1st Owner
4      0  Petrol        SUV    10,000    Automatic        1  1st Owner
...   ..     ...        ...       ...          ...      ...        ...
1478   0  Diesel        SUV    60,000       Manual        1  1st Owner
1479   0  Diesel      Sedan    50,000    Automatic        1  1st Owner
1480   0  Diesel      Sedan  1,20,000    Automatic        3  3rd Owner
1481   0  Diesel        SUV    50,000    Automatic        2  2nd Owner
1482   0  Diesel        MUV  1,00,000       Manual        1  1st Owner

             oem            model  modelYear  ...         price priceActual  \
0     Volkswagen  Volkswagen Polo       2022  ...  ₹ 10.44 Lakh
1        Hyundai      Hyundai EON       2014  ...   ₹ 2.60 Lakh
2        Hyundai    Hyundai Venue       2023  ...   ₹ 9.55 Lakh
3         Maruti    Maruti Baleno       2017  ...   ₹ 6.71 Lakh
4       Mahindra    Mahindra Thar       2022  ...     ₹ 19 Lakh
...          ...              ...        ...  ...           ...         ...
1478    Mahindra  Mahindra XUV500       2013  ...      ₹ 7 Lakh
1479      Jaguar        Jaguar XF       2014  ...     ₹ 20 Lakh
1480         BMW     BMW 5 Series       2018  ...     ₹ 35 Lakh
1481        Tata       Tata Nexon       2019  ...   ₹ 8.50 Lakh
1482      Toyota    Toyota Innova       2015  ...     ₹ 15 Lakh

     priceSaving priceFixedText  \
0                          None
1                          None
2                          None
3                          None
4                          None
...          ...            ...
1478                       None
1479                       None
1480                       None
1481                       None
1482                       None

                                           trendingText         heading  \
0     {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
1     {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
2     {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
3     {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
4     {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
...                                                 ...             ...
1478  {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
1479  {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
1480  {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
1481  {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
1482  {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications

                                                    top bottomData  \
0     [{'key': 'Mileage', 'value': '16.47 kmpl'}, {'...       None
1     [{'key': 'Mileage', 'value': '21.1 kmpl'}, {'k...       None
2     [{'key': 'Engine', 'value': '1197 CC'}, {'key'...       None
3     [{'key': 'Mileage', 'value': '21.4 kmpl'}, {'k...       None
4     [{'key': 'Engine', 'value': '1997 CC'}, {'key'...       None
...                                                 ...        ...
1478  [{'key': 'Mileage', 'value': '15.1 kmpl'}, {'k...       None
1479  [{'key': 'Mileage', 'value': '14.74 kmpl'}, {'...       None
1480  [{'key': 'Mileage', 'value': '20.37 kmpl'}, {'...       None
1481  [{'key': 'Mileage', 'value': '21.5 kmpl'}, {'k...       None
1482  [{'key': 'Mileage', 'value': '12.99 kmpl'}, {'...       None

                                                   data commonIcon
0     [{'heading': 'Engine and Transmission', 'subHe...
1     [{'heading': 'Engine and Transmission', 'subHe...
2     [{'heading': 'Engine and Transmission', 'subHe...
3     [{'heading': 'Engine and Transmission', 'subHe...
4     [{'heading': 'Engine and Transmission', 'subHe...
...                                                 ...        ...
1478  [{'heading': 'Engine and Transmission', 'subHe...
1479  [{'heading': 'Engine and Transmission', 'subHe...
1480  [{'heading': 'Engine and Transmission', 'subHe...
1481  [{'heading': 'Engine and Transmission', 'subHe...
1482  [{'heading': 'Engine and Transmission', 'subHe...

[1483 rows x 22 columns]

In [135]:
import pandas as pd

# Step 1: Read the Excel file
df = pd.read_excel("hyderabad_cars.xlsx")

# Step 2: Initialize an empty list to hold structured data
structured_data = []

# Step 3: Loop through each row of the DataFrame
for index, row in df.iterrows():
    row_data = {}
    
    # Convert the string representation of the dictionary to an actual dictionary
    try:
        dict_value = eval(row['new_car_detail'])  # Replace eval with ast.literal_eval for safer evaluation
        if isinstance(dict_value, dict):
            row_data = dict_value
    except Exception as e:
        print(f"Error parsing row {index}: {e}")
        row_data = None

    # Append the row dictionary to the structured data list
    structured_data.append(row_data)

# Step 4: Create a DataFrame from the list of dictionaries in 'new_car_detail'
unwound_df = pd.json_normalize(structured_data)

# Optional: Display the unwound DataFrame
print(unwound_df)

# Save the unwound DataFrame to a new Excel file
#unwound_df.to_excel('unwound_new_car_detail.xlsx', index=False)

      it      ft         bt        km transmission  ownerNo      owner  \
0      0  Petrol  Hatchback    20,000    Automatic        1  1st Owner
1      0  Petrol  Hatchback    85,582       Manual        2  2nd Owner
2      0  Petrol        SUV    10,000       Manual        1  1st Owner
3      0  Petrol  Hatchback    50,750       Manual        1  1st Owner
4      0  Petrol        SUV    10,000    Automatic        1  1st Owner
...   ..     ...        ...       ...          ...      ...        ...
1478   0  Diesel        SUV    60,000       Manual        1  1st Owner
1479   0  Diesel      Sedan    50,000    Automatic        1  1st Owner
1480   0  Diesel      Sedan  1,20,000    Automatic        3  3rd Owner
1481   0  Diesel        SUV    50,000    Automatic        2  2nd Owner
1482   0  Diesel        MUV  1,00,000       Manual        1  1st Owner

             oem            model  modelYear  centralVariantId  \
0     Volkswagen  Volkswagen Polo       2022              7746
1        Hyundai      Hyundai EON       2014              1502
2        Hyundai    Hyundai Venue       2023              9153
3         Maruti    Maruti Baleno       2017              3970
4       Mahindra    Mahindra Thar       2022              8074
...          ...              ...        ...               ...
1478    Mahindra  Mahindra XUV500       2013              3823
1479      Jaguar        Jaguar XF       2014              5007
1480         BMW     BMW 5 Series       2018               250
1481        Tata       Tata Nexon       2019              6500
1482      Toyota    Toyota Innova       2015              2294

                     variantName         price priceActual priceSaving  \
0       1.0 TSI Highline Plus AT  ₹ 10.44 Lakh
1                       Era Plus   ₹ 2.60 Lakh
2                         S BSVI   ₹ 9.55 Lakh
3                      1.2 Alpha   ₹ 6.71 Lakh
4      LX 4-Str Hard Top AT BSVI     ₹ 19 Lakh
...                          ...           ...         ...         ...
1478                      W8 2WD      ₹ 7 Lakh
1479  3.0 Litre S Premium Luxury     ₹ 20 Lakh
1480            520d Luxury Line     ₹ 35 Lakh
1481            1.5 Revotorq XMA   ₹ 8.50 Lakh
1482      2.5 ZX Diesel 7 Seater     ₹ 15 Lakh

     priceFixedText                                trendingText.imgUrl  \
0              None  https://stimg.cardekho.com/used-cars/common/ic...
1              None  https://stimg.cardekho.com/used-cars/common/ic...
2              None  https://stimg.cardekho.com/used-cars/common/ic...
3              None  https://stimg.cardekho.com/used-cars/common/ic...
4              None  https://stimg.cardekho.com/used-cars/common/ic...
...             ...                                                ...
1478           None  https://stimg.cardekho.com/used-cars/common/ic...
1479           None  https://stimg.cardekho.com/used-cars/common/ic...
1480           None  https://stimg.cardekho.com/used-cars/common/ic...
1481           None  https://stimg.cardekho.com/used-cars/common/ic...
1482           None  https://stimg.cardekho.com/used-cars/common/ic...

     trendingText.heading                    trendingText.desc
0           Trending Car!  High chances of sale in next 6 days
1           Trending Car!  High chances of sale in next 6 days
2           Trending Car!  High chances of sale in next 6 days
3           Trending Car!  High chances of sale in next 6 days
4           Trending Car!  High chances of sale in next 6 days
...                   ...                                  ...
1478        Trending Car!  High chances of sale in next 6 days
1479        Trending Car!  High chances of sale in next 6 days
1480        Trending Car!  High chances of sale in next 6 days
1481        Trending Car!  High chances of sale in next 6 days
1482        Trending Car!  High chances of sale in next 6 days

[1483 rows x 19 columns]

In [136]:
import pandas as pd

# Step 1: Read the Excel file
df = pd.read_excel("hyderabad_cars.xlsx")

# Step 2: Initialize an empty list to hold structured data
structured_data = []

# Step 3: Loop through each row of the DataFrame
for index, row in df.iterrows():
    row_data = {}
    
    # Convert the string representation of the dictionary to an actual dictionary
    try:
        dict_value = eval(row['new_car_overview'])  # Replace eval with ast.literal_eval for safer evaluation
        if isinstance(dict_value, dict):
            row_data = dict_value
    except Exception as e:
        print(f"Error parsing row {index}: {e}")
        row_data = None

    # Append the row dictionary to the structured data list
    structured_data.append(row_data)

# Step 4: Create a DataFrame from the list of dictionaries in 'new_car_detail'
unwound_df1 = pd.json_normalize(structured_data)

# Optional: Display the unwound DataFrame
print(unwound_df1)

# Save the unwound DataFrame to a new Excel file
#unwound_df.to_excel('unwound_new_car_detail.xlsx', index=False)

           heading                                                top  \
0     Car overview  [{'key': 'Registration Year', 'value': '2022',...
1     Car overview  [{'key': 'Registration Year', 'value': 'Oct 20...
2     Car overview  [{'key': 'Registration Year', 'value': '2023',...
3     Car overview  [{'key': 'Registration Year', 'value': 'Mar 20...
4     Car overview  [{'key': 'Registration Year', 'value': '2022',...
...            ...                                                ...
1478  Car overview  [{'key': 'Registration Year', 'value': '2013',...
1479  Car overview  [{'key': 'Registration Year', 'value': '2014',...
1480  Car overview  [{'key': 'Registration Year', 'value': '2018',...
1481  Car overview  [{'key': 'Registration Year', 'value': '2019',...
1482  Car overview  [{'key': 'Registration Year', 'value': '2015',...

     bottomData
0          None
1          None
2          None
3          None
4          None
...         ...
1478       None
1479       None
1480       None
1481       None
1482       None

[1483 rows x 3 columns]

In [137]:
import pandas as pd

# Step 1: Read the Excel file
df = pd.read_excel("hyderabad_cars.xlsx")

# Step 2: Initialize an empty list to hold structured data
structured_data = []

# Step 3: Loop through each row of the DataFrame
for index, row in df.iterrows():
    row_data = {}
    
    # Convert the string representation of the dictionary to an actual dictionary
    try:
        dict_value = eval(row['new_car_feature'])  # Replace eval with ast.literal_eval for safer evaluation
        if isinstance(dict_value, dict):
            row_data = dict_value
    except Exception as e:
        print(f"Error parsing row {index}: {e}")
        row_data = None

    # Append the row dictionary to the structured data list
    structured_data.append(row_data)

# Step 4: Create a DataFrame from the list of dictionaries in 'new_car_detail'
unwound_df2 = pd.json_normalize(structured_data)

# Optional: Display the unwound DataFrame
print(unwound_df2)

# Save the unwound DataFrame to a new Excel file
#unwound_df.to_excel('unwound_new_car_detail.xlsx', index=False)

       heading                                                top  \
0     Features  [{'value': 'Power Steering'}, {'value': 'Power...
1     Features  [{'value': 'Power Steering'}, {'value': 'Power...
2     Features  [{'value': 'Power Steering'}, {'value': 'Power...
3     Features  [{'value': 'Power Steering'}, {'value': 'Power...
4     Features  [{'value': 'Power Steering'}, {'value': 'Power...
...        ...                                                ...
1478  Features  [{'value': 'Power Steering'}, {'value': 'Power...
1479  Features  [{'value': 'Power Steering'}, {'value': 'Power...
1480  Features  [{'value': 'Power Steering'}, {'value': 'Power...
1481  Features  [{'value': 'Power Steering'}, {'value': 'Power...
1482  Features  [{'value': 'Power Steering'}, {'value': 'Power...

                                                   data  \
0     [{'heading': 'Comfort & Convenience', 'subHead...
1     [{'heading': 'Comfort & Convenience', 'subHead...
2     [{'heading': 'Comfort & Convenience', 'subHead...
3     [{'heading': 'Comfort & Convenience', 'subHead...
4     [{'heading': 'Comfort & Convenience', 'subHead...
...                                                 ...
1478  [{'heading': 'Comfort & Convenience', 'subHead...
1479  [{'heading': 'Comfort & Convenience', 'subHead...
1480  [{'heading': 'Comfort & Convenience', 'subHead...
1481  [{'heading': 'Comfort & Convenience', 'subHead...
1482  [{'heading': 'Comfort & Convenience', 'subHead...

                                             commonIcon
0     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
2     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
3     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
4     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
...                                                 ...
1478  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1479  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1480  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1481  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1482  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg

[1483 rows x 4 columns]

In [138]:
import pandas as pd

# Step 1: Read the Excel file
df = pd.read_excel("hyderabad_cars.xlsx")

# Step 2: Initialize an empty list to hold structured data
structured_data = []

# Step 3: Loop through each row of the DataFrame
for index, row in df.iterrows():
    row_data = {}
    
    # Convert the string representation of the dictionary to an actual dictionary
    try:
        dict_value = eval(row['new_car_specs'])  # Replace eval with ast.literal_eval for safer evaluation
        if isinstance(dict_value, dict):
            row_data = dict_value
    except Exception as e:
        print(f"Error parsing row {index}: {e}")
        row_data = None

    # Append the row dictionary to the structured data list
    structured_data.append(row_data)

# Step 4: Create a DataFrame from the list of dictionaries in 'new_car_detail'
unwound_df3 = pd.json_normalize(structured_data)

# Optional: Display the unwound DataFrame
print(unwound_df3)

# Save the unwound DataFrame to a new Excel file
#unwound_df.to_excel('unwound_new_car_detail.xlsx', index=False)

             heading                                                top  \
0     Specifications  [{'key': 'Mileage', 'value': '16.47 kmpl'}, {'...
1     Specifications  [{'key': 'Mileage', 'value': '21.1 kmpl'}, {'k...
2     Specifications  [{'key': 'Engine', 'value': '1197 CC'}, {'key'...
3     Specifications  [{'key': 'Mileage', 'value': '21.4 kmpl'}, {'k...
4     Specifications  [{'key': 'Engine', 'value': '1997 CC'}, {'key'...
...              ...                                                ...
1478  Specifications  [{'key': 'Mileage', 'value': '15.1 kmpl'}, {'k...
1479  Specifications  [{'key': 'Mileage', 'value': '14.74 kmpl'}, {'...
1480  Specifications  [{'key': 'Mileage', 'value': '20.37 kmpl'}, {'...
1481  Specifications  [{'key': 'Mileage', 'value': '21.5 kmpl'}, {'k...
1482  Specifications  [{'key': 'Mileage', 'value': '12.99 kmpl'}, {'...

                                                   data commonIcon
0     [{'heading': 'Engine and Transmission', 'subHe...
1     [{'heading': 'Engine and Transmission', 'subHe...
2     [{'heading': 'Engine and Transmission', 'subHe...
3     [{'heading': 'Engine and Transmission', 'subHe...
4     [{'heading': 'Engine and Transmission', 'subHe...
...                                                 ...        ...
1478  [{'heading': 'Engine and Transmission', 'subHe...
1479  [{'heading': 'Engine and Transmission', 'subHe...
1480  [{'heading': 'Engine and Transmission', 'subHe...
1481  [{'heading': 'Engine and Transmission', 'subHe...
1482  [{'heading': 'Engine and Transmission', 'subHe...

[1483 rows x 4 columns]

In [139]:
import pandas as pd

# Assume df1, df2, df3, and df4 are your four DataFrames

# Concatenate the DataFrames column-wise
combined_df = pd.concat([unwound_df, unwound_df1, unwound_df2, unwound_df3], axis=1)

# Optional: Display the combined DataFrame
print(combined_df)

# Save the combined DataFrame to a new Excel file if needed
combined_df.to_excel('combined_data_column_wise_hyderabad.xlsx', index=False)

      it      ft         bt        km transmission  ownerNo      owner  \
0      0  Petrol  Hatchback    20,000    Automatic        1  1st Owner
1      0  Petrol  Hatchback    85,582       Manual        2  2nd Owner
2      0  Petrol        SUV    10,000       Manual        1  1st Owner
3      0  Petrol  Hatchback    50,750       Manual        1  1st Owner
4      0  Petrol        SUV    10,000    Automatic        1  1st Owner
...   ..     ...        ...       ...          ...      ...        ...
1478   0  Diesel        SUV    60,000       Manual        1  1st Owner
1479   0  Diesel      Sedan    50,000    Automatic        1  1st Owner
1480   0  Diesel      Sedan  1,20,000    Automatic        3  3rd Owner
1481   0  Diesel        SUV    50,000    Automatic        2  2nd Owner
1482   0  Diesel        MUV  1,00,000       Manual        1  1st Owner

             oem            model  modelYear  ...  \
0     Volkswagen  Volkswagen Polo       2022  ...
1        Hyundai      Hyundai EON       2014  ...
2        Hyundai    Hyundai Venue       2023  ...
3         Maruti    Maruti Baleno       2017  ...
4       Mahindra    Mahindra Thar       2022  ...
...          ...              ...        ...  ...
1478    Mahindra  Mahindra XUV500       2013  ...
1479      Jaguar        Jaguar XF       2014  ...
1480         BMW     BMW 5 Series       2018  ...
1481        Tata       Tata Nexon       2019  ...
1482      Toyota    Toyota Innova       2015  ...

                                                    top bottomData   heading  \
0     [{'key': 'Registration Year', 'value': '2022',...       None  Features
1     [{'key': 'Registration Year', 'value': 'Oct 20...       None  Features
2     [{'key': 'Registration Year', 'value': '2023',...       None  Features
3     [{'key': 'Registration Year', 'value': 'Mar 20...       None  Features
4     [{'key': 'Registration Year', 'value': '2022',...       None  Features
...                                                 ...        ...       ...
1478  [{'key': 'Registration Year', 'value': '2013',...       None  Features
1479  [{'key': 'Registration Year', 'value': '2014',...       None  Features
1480  [{'key': 'Registration Year', 'value': '2018',...       None  Features
1481  [{'key': 'Registration Year', 'value': '2019',...       None  Features
1482  [{'key': 'Registration Year', 'value': '2015',...       None  Features

                                                    top  \
0     [{'value': 'Power Steering'}, {'value': 'Power...
1     [{'value': 'Power Steering'}, {'value': 'Power...
2     [{'value': 'Power Steering'}, {'value': 'Power...
3     [{'value': 'Power Steering'}, {'value': 'Power...
4     [{'value': 'Power Steering'}, {'value': 'Power...
...                                                 ...
1478  [{'value': 'Power Steering'}, {'value': 'Power...
1479  [{'value': 'Power Steering'}, {'value': 'Power...
1480  [{'value': 'Power Steering'}, {'value': 'Power...
1481  [{'value': 'Power Steering'}, {'value': 'Power...
1482  [{'value': 'Power Steering'}, {'value': 'Power...

                                                   data  \
0     [{'heading': 'Comfort & Convenience', 'subHead...
1     [{'heading': 'Comfort & Convenience', 'subHead...
2     [{'heading': 'Comfort & Convenience', 'subHead...
3     [{'heading': 'Comfort & Convenience', 'subHead...
4     [{'heading': 'Comfort & Convenience', 'subHead...
...                                                 ...
1478  [{'heading': 'Comfort & Convenience', 'subHead...
1479  [{'heading': 'Comfort & Convenience', 'subHead...
1480  [{'heading': 'Comfort & Convenience', 'subHead...
1481  [{'heading': 'Comfort & Convenience', 'subHead...
1482  [{'heading': 'Comfort & Convenience', 'subHead...

                                             commonIcon         heading  \
0     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
1     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
2     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
3     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
4     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
...                                                 ...             ...
1478  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
1479  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
1480  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
1481  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
1482  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications

                                                    top  \
0     [{'key': 'Mileage', 'value': '16.47 kmpl'}, {'...
1     [{'key': 'Mileage', 'value': '21.1 kmpl'}, {'k...
2     [{'key': 'Engine', 'value': '1197 CC'}, {'key'...
3     [{'key': 'Mileage', 'value': '21.4 kmpl'}, {'k...
4     [{'key': 'Engine', 'value': '1997 CC'}, {'key'...
...                                                 ...
1478  [{'key': 'Mileage', 'value': '15.1 kmpl'}, {'k...
1479  [{'key': 'Mileage', 'value': '14.74 kmpl'}, {'...
1480  [{'key': 'Mileage', 'value': '20.37 kmpl'}, {'...
1481  [{'key': 'Mileage', 'value': '21.5 kmpl'}, {'k...
1482  [{'key': 'Mileage', 'value': '12.99 kmpl'}, {'...

                                                   data commonIcon
0     [{'heading': 'Engine and Transmission', 'subHe...
1     [{'heading': 'Engine and Transmission', 'subHe...
2     [{'heading': 'Engine and Transmission', 'subHe...
3     [{'heading': 'Engine and Transmission', 'subHe...
4     [{'heading': 'Engine and Transmission', 'subHe...
...                                                 ...        ...
1478  [{'heading': 'Engine and Transmission', 'subHe...
1479  [{'heading': 'Engine and Transmission', 'subHe...
1480  [{'heading': 'Engine and Transmission', 'subHe...
1481  [{'heading': 'Engine and Transmission', 'subHe...
1482  [{'heading': 'Engine and Transmission', 'subHe...

[1483 rows x 30 columns]

In [140]:
import pandas as pd

# Example DataFrame with repeating columns (for demonstration purposes)
# combined_df = pd.DataFrame(...)  # Assume this is your existing DataFrame

# Step 1: Get the current column names
original_columns = combined_df.columns

# Step 2: Create a new list to hold unique column names
new_columns = []
column_count = {}

# Step 3: Loop through original columns and create unique names
for col in original_columns:
    if col in column_count:
        column_count[col] += 1
        new_columns.append(f"{col}_{column_count[col]}")  # Append count as suffix
    else:
        column_count[col] = 1
        new_columns.append(col)  # Keep original name for the first occurrence

# Step 4: Assign the new column names to the DataFrame
combined_df.columns = new_columns

# Optional: Display the updated DataFrame columns
print(combined_df.columns)

Index(['it', 'ft', 'bt', 'km', 'transmission', 'ownerNo', 'owner', 'oem',
       'model', 'modelYear', 'centralVariantId', 'variantName', 'price',
       'priceActual', 'priceSaving', 'priceFixedText', 'trendingText.imgUrl',
       'trendingText.heading', 'trendingText.desc', 'heading', 'top',
       'bottomData', 'heading_2', 'top_2', 'data', 'commonIcon', 'heading_3',
       'top_3', 'data_2', 'commonIcon_2'],
      dtype='object')

In [141]:
import pandas as pd

# Function to extract and convert 'top1' into a DataFrame
def extract_top_to_dataframe(main_df):
    rows = []  # To hold the extracted data
    
    # Loop through each row in the main DataFrame
    for _, row in main_df.iterrows():
        top3_data = row['top_3']  # Access the list directly
        
        # Check if the top1_data is a list
        if isinstance(top3_data, list):
            # Create a dictionary from the extracted key-value pairs
            row_dict = {item['key']: item['value'] for item in top3_data if 'key' in item and 'value' in item}
            rows.append(row_dict)  # Add the dictionary to the rows list
        else:
            print(f"Unexpected format for row: {row}. Expected a list but got {type(top3_data)}")
    
    # Create a new DataFrame from the rows list
    top3_df = pd.DataFrame(rows)
    return top3_df

# Extracting the DataFrame from 'top1'
top3_df = extract_top_to_dataframe(combined_df)

# Display the new DataFrame
print(top3_df)

         Mileage   Engine  Max Power   Torque Wheel Size Seats
0     16.47 kmpl   999 CC  108.62bhp    175nm        R16     5
1      21.1 kmpl   814 CC    55.2bhp   74.5Nm        NaN     5
2            NaN  1197 CC   81.80bhp  113.8Nm        NaN     5
3      21.4 kmpl  1197 CC    83.1bhp    115Nm         16     5
4            NaN  1997 CC     150bhp    320Nm         18     4
...          ...      ...        ...      ...        ...   ...
1478   15.1 kmpl  2179 CC     140bhp    330Nm         17     7
1479  14.74 kmpl  2993 CC   270.9bhp    600Nm         20     5
1480  20.37 kmpl  1995 CC  187.74bhp    400Nm        R18     5
1481   21.5 kmpl  1497 CC   108.5bhp    260Nm        NaN     5
1482  12.99 kmpl  2494 CC   100.6bhp    200Nm         15     7

[1483 rows x 6 columns]

In [142]:
import pandas as pd

# Assuming combined_df is your existing DataFrame with a column named 'top_2'
# combined_df = ...  # Your existing DataFrame

def extract_list_of_dicts_to_dataframe(main_df, column_name):
    # Initialize a list to store the extracted data
    extracted_data = []

    for index, row in main_df.iterrows():
        # Check if the cell is a list and not empty
        if isinstance(row[column_name], list) and row[column_name]:
            # Create a dictionary from the extracted values
            row_dict = {item['value']: True for item in row[column_name]}
        else:
            row_dict = {}

        extracted_data.append(row_dict)

    # Create a DataFrame from the extracted data
    extracted_df = pd.DataFrame(extracted_data)

    return extracted_df

# Extract DataFrame for top_2
top_2_df = extract_list_of_dicts_to_dataframe(combined_df, 'top_2')

# Display the DataFrame
print("DataFrame for top_2:")
print(top_2_df)

DataFrame for top_2:
     Power Steering Power Windows Front Air Conditioner Heater  \
0              True                True            True   True
1              True                True            True   True
2              True                True            True   True
3              True                True            True   True
4              True                True            True   True
...             ...                 ...             ...    ...
1478           True                True            True   True
1479           True                True            True   True
1480           True                True            True   True
1481           True                True            True   True
1482           True                True            True   True

     Adjustable Head Lights Fog Lights Front Anti Lock Braking System  \
0                      True             True                     True
1                      True              NaN                      NaN
2                      True              NaN                     True
3                      True             True                     True
4                      True             True                     True
...                     ...              ...                      ...
1478                   True             True                     True
1479                   True              NaN                     True
1480                   True             True                     True
1481                   True              NaN                     True
1482                   True             True                     True

     Centeral Locking Radio Manually Adjustable Exterior Rear View Mirror  \
0                True  True                                           NaN
1                 NaN   NaN                                          True
2                 NaN  True                                           NaN
3                True  True                                           NaN
4                 NaN  True                                           NaN
...               ...   ...                                           ...
1478             True   NaN                                           NaN
1479              NaN   NaN                                           NaN
1480              NaN   NaN                                           NaN
1481             True  True                                           NaN
1482             True   NaN                                           NaN

      ... Tachometer Wheel Covers Accessory Power Outlet Rear Seat Headrest  \
0     ...        NaN          NaN                    NaN                NaN
1     ...        NaN          NaN                    NaN                NaN
2     ...        NaN          NaN                    NaN                NaN
3     ...        NaN          NaN                    NaN                NaN
4     ...        NaN          NaN                    NaN                NaN
...   ...        ...          ...                    ...                ...
1478  ...        NaN          NaN                    NaN                NaN
1479  ...        NaN          NaN                    NaN                NaN
1480  ...        NaN          NaN                    NaN                NaN
1481  ...        NaN          NaN                    NaN                NaN
1482  ...        NaN          NaN                    NaN                NaN

     Integrated2Din Audio Rear Seat Belts Rear Folding Table  \
0                     NaN             NaN                NaN
1                     NaN             NaN                NaN
2                     NaN             NaN                NaN
3                     NaN             NaN                NaN
4                     NaN             NaN                NaN
...                   ...             ...                ...
1478                  NaN             NaN                NaN
1479                  NaN             NaN                NaN
1480                  NaN             NaN                NaN
1481                  NaN             NaN                NaN
1482                  NaN             NaN                NaN

     Driving Experience Control Eco Engine Immobilizer Leather Steering Wheel
0                               NaN                NaN                    NaN
1                               NaN                NaN                    NaN
2                               NaN                NaN                    NaN
3                               NaN                NaN                    NaN
4                               NaN                NaN                    NaN
...                             ...                ...                    ...
1478                            NaN                NaN                    NaN
1479                            NaN                NaN                    NaN
1480                            NaN                NaN                    NaN
1481                            NaN                NaN                    NaN
1482                            NaN                NaN                    NaN

[1483 rows x 55 columns]

In [143]:
import pandas as pd

# Function to extract and convert 'top1' into a DataFrame
def extract_top_to_dataframe(main_df):
    rows = []  # To hold the extracted data
    
    # Loop through each row in the main DataFrame
    for _, row in main_df.iterrows():
        top_data = row['top']  # Access the list directly
        
        # Check if the top1_data is a list
        if isinstance(top_data, list):
            # Create a dictionary from the extracted key-value pairs
            row_dict = {item['key']: item['value'] for item in top_data if 'key' in item and 'value' in item}
            rows.append(row_dict)  # Add the dictionary to the rows list
        else:
            print(f"Unexpected format for row: {row}. Expected a list but got {type(top_data)}")
    
    # Create a new DataFrame from the rows list
    top_df = pd.DataFrame(rows)
    return top_df

# Extracting the DataFrame from 'top1'
top_df = extract_top_to_dataframe(combined_df)

# Display the new DataFrame
print(top_df)

     Registration Year     Insurance Validity Fuel Type    Seats  \
0                 2022  Third Party insurance    Petrol  5 Seats
1             Oct 2014  Third Party insurance    Petrol  5 Seats
2                 2023  Third Party insurance    Petrol  5 Seats
3             Mar 2017  Third Party insurance    Petrol  5 Seats
4                 2022  Third Party insurance    Petrol  4 Seats
...                ...                    ...       ...      ...
1478              2013  Third Party insurance    Diesel  7 Seats
1479              2014  Third Party insurance    Diesel  5 Seats
1480              2018  Third Party insurance    Diesel  5 Seats
1481              2019  Third Party insurance    Diesel  5 Seats
1482              2015  Third Party insurance    Diesel  7 Seats

        Kms Driven   RTO     Ownership Engine Displacement Transmission  \
0       20,000 Kms  TS04   First Owner              999 cc    Automatic
1       85,582 Kms  TS09  Second Owner              814 cc       Manual
2       10,000 Kms   NaN   First Owner             1197 cc       Manual
3       50,750 Kms  TS07   First Owner             1197 cc       Manual
4       10,000 Kms   NaN   First Owner             1997 cc    Automatic
...            ...   ...           ...                 ...          ...
1478    60,000 Kms  TS09   First Owner             2179 cc       Manual
1479    50,000 Kms   NaN   First Owner             2993 cc    Automatic
1480  1,20,000 Kms  TS09   Third Owner             1995 cc    Automatic
1481    50,000 Kms  TS08  Second Owner             1497 cc    Automatic
1482  1,00,000 Kms   NaN   First Owner             2494 cc       Manual

      Year of Manufacture
0                  2022.0
1                  2014.0
2                  2023.0
3                  2017.0
4                  2022.0
...                   ...
1478               2013.0
1479               2014.0
1480               2018.0
1481               2019.0
1482               2015.0

[1483 rows x 10 columns]

In [144]:
import pandas as pd

def extract_data_to_dataframe(main_df, column_name):
    # Create a list to hold the rows for the new DataFrame
    data_rows = []
    
    # Iterate over each row in the main DataFrame
    for index, row in main_df.iterrows():
        # Check if the cell is a list and contains dictionaries
        if isinstance(row[column_name], list) and row[column_name]:
            # Extract the 'list' field from the first dictionary in the row
            list_values = row[column_name][0].get('list', [])
            # Create a dictionary to hold values for this row
            row_dict = {item['value']: True for item in list_values}
            # Append the dictionary to the rows list
            data_rows.append(row_dict)
        else:
            # If there's no data, append an empty dictionary
            data_rows.append({})

    # Create a DataFrame from the list of dictionaries
    data_df = pd.DataFrame(data_rows)

    return data_df

# Extract DataFrame for the 'data' column
data_df = extract_data_to_dataframe(combined_df, 'data')

# Display the DataFrame
print("DataFrame for data:")
print(data_df)

DataFrame for data:
     Power Steering Power Windows Front Power Windows Rear  \
0              True                True               True
1              True                True                NaN
2              True                True               True
3              True                True               True
4              True                True                NaN
...             ...                 ...                ...
1478           True                True               True
1479           True                True               True
1480           True                True               True
1481           True                True               True
1482           True                True               True

     Remote Trunk Opener Low Fuel Warning Light Accessory Power Outlet  \
0                   True                   True                   True
1                   True                   True                   True
2                    NaN                   True                   True
3                   True                   True                   True
4                    NaN                   True                   True
...                  ...                    ...                    ...
1478                True                   True                   True
1479                True                   True                   True
1480                True                   True                   True
1481                 NaN                   True                   True
1482                True                   True                   True

     Vanity Mirror Rear Seat Headrest Cup Holders Front Seat Lumbar Support  \
0             True               True              True                True
1              NaN               True              True                 NaN
2              NaN               True               NaN                 NaN
3             True               True              True                 NaN
4              NaN               True               NaN                True
...            ...                ...               ...                 ...
1478           NaN               True              True                 NaN
1479          True               True              True                True
1480          True               True              True                True
1481           NaN               True              True                 NaN
1482          True               True              True                 NaN

      ... Power Antenna Integrated Antenna Tinted Glass Rear Spoiler  \
0     ...           NaN                NaN          NaN          NaN
1     ...           NaN                NaN          NaN          NaN
2     ...           NaN                NaN          NaN          NaN
3     ...           NaN                NaN          NaN          NaN
4     ...           NaN                NaN          NaN          NaN
...   ...           ...                ...          ...          ...
1478  ...           NaN                NaN          NaN          NaN
1479  ...           NaN                NaN          NaN          NaN
1480  ...           NaN                NaN          NaN          NaN
1481  ...           NaN                NaN          NaN          NaN
1482  ...           NaN                NaN          NaN          NaN

     Removable Convertible Top Roof Carrier Sun Roof Moon Roof Side Stepper  \
0                          NaN          NaN      NaN       NaN          NaN
1                          NaN          NaN      NaN       NaN          NaN
2                          NaN          NaN      NaN       NaN          NaN
3                          NaN          NaN      NaN       NaN          NaN
4                          NaN          NaN      NaN       NaN          NaN
...                        ...          ...      ...       ...          ...
1478                       NaN          NaN      NaN       NaN          NaN
1479                       NaN          NaN      NaN       NaN          NaN
1480                       NaN          NaN      NaN       NaN          NaN
1481                       NaN          NaN      NaN       NaN          NaN
1482                       NaN          NaN      NaN       NaN          NaN

     Outside Rear View Mirror Turn Indicators
0                                         NaN
1                                         NaN
2                                         NaN
3                                         NaN
4                                         NaN
...                                       ...
1478                                      NaN
1479                                      NaN
1480                                      NaN
1481                                      NaN
1482                                      NaN

[1483 rows x 64 columns]

In [145]:
import pandas as pd

def extract_data2_to_dataframe(main_df, column_name):
    # Create a list to hold the rows for the new DataFrame
    data_rows = []
    
    # Iterate over each row in the main DataFrame
    for index, row in main_df.iterrows():
        # Check if the cell is a list and contains dictionaries
        if isinstance(row[column_name], list) and row[column_name]:
            # Create a dictionary to hold values for this row
            row_dict = {}
            for section in row[column_name]:
                # Extract the 'list' field from each section
                for item in section.get('list', []):
                    # Use the 'key' as the column name and 'value' as the value
                    row_dict[item['key']] = item['value']
            # Append the dictionary to the rows list
            data_rows.append(row_dict)
        else:
            # If there's no data, append an empty dictionary
            data_rows.append({})

    # Create a DataFrame from the list of dictionaries
    data2_df = pd.DataFrame(data_rows)

    return data2_df

# Extract DataFrame for the 'data_2' column
data2_df = extract_data2_to_dataframe(combined_df, 'data_2')

# Display the DataFrame
print("DataFrame for data_2:")
print(data2_df)

DataFrame for data_2:
       Color                               Engine Type Displacement  \
0     Others                           1.0L TSI Petrol          999
1        Red                             Petrol Engine          814
2     Others                          1.2 Kappa Petrol         1197
3        Red                         VVT Petrol Engine         1197
4     Others                 mStallion 150 TGDi Engine         1997
...      ...                                       ...          ...
1478  Others                       mHawk Diesel Engine         2179
1479    Blue                           Diesel S Engine         2993
1480    Blue  TwinPower Turbo Inline 4 Cylinder Engine         1995
1481  Others        Revotorq, 1.5L Turbocharged engine         1497
1482  Others                     2KD-FTV Diesel Engine         2494

                   Max Power          Max Torque  No of Cylinder  \
0     108.62bhp@5000-5500rpm  175nm@1750-4000rpm             3.0
1            55.2bhp@5500rpm      74.5Nm@4000rpm             3.0
2           81.80bhp@6000rpm     113.8Nm@4000rpm             4.0
3            83.1bhp@6000rpm       115Nm@4000rpm             4.0
4             150bhp@5000rpm  320Nm@1500-3000rpm             4.0
...                      ...                 ...             ...
1478          140bhp@3750rpm  330Nm@1600-2800rpm             4.0
1479        270.9bhp@4000rpm       600Nm@2000rpm             6.0
1480       187.74bhp@4000rpm  400Nm@1750-2500rpm             4.0
1481        108.5bhp@3750rpm  260Nm@1500-2750rpm             4.0
1482        100.6bhp@3600rpm  200Nm@1200-3600rpm             4.0

      Values per Cylinder Value Configuration Fuel Suppy System  BoreX Stroke  \
0                     4.0                DOHC               TSI  74.5x76.4 mm
1                     3.0                SOHC              MPFI           NaN
2                     4.0                 NaN               NaN           NaN
3                     4.0                DOHC              MPFI           NaN
4                     4.0                 NaN               NaN           NaN
...                   ...                 ...               ...           ...
1478                  4.0                DOHC  Direct Injection           NaN
1479                  4.0                DOHC  Direct Injection           NaN
1480                  4.0                 NaN              CRDi           NaN
1481                  4.0                DOHC               CDI       76x82.5
1482                  4.0                DOHC              CRDi           NaN

      ... Turning Radius     Front Brake Type      Rear Brake Type  \
0     ...            4.9                 Disc                 Drum
1     ...     4.6 metres                 Disc                 Drum
2     ...            NaN                 Disc                 Drum
3     ...     4.9 meters                 Disc                 Drum
4     ...            NaN                 Disc                 Drum
...   ...            ...                  ...                  ...
1478  ...     5.6 metres  Disc & Caliper Type  Disc & Caliper Type
1479  ...    5.75 metres                 Disc                 Disc
1480  ...            5.6      Ventilated Disc      Ventilated Disc
1481  ...           5.1m                 Disc                 Drum
1482  ...     5.4 metres      Ventilated Disc                 Drum

                  Tyre Type Alloy Wheel Size No Door Numbers Cargo Volumn  \
0           Tubeless,Radial              R16               5          280
1                  Tubeless              NaN               5   215-litres
2          Tubeless, Radial              NaN               5          NaN
3           Tubeless,Radial               16               5   339-litres
4          Radial, Tubeless               18               3          NaN
...                     ...              ...             ...          ...
1478       Tubeless,Radial                17               5          NaN
1479        Tubeless,Radial               20               4   540-litres
1480      Tubeless, Runflat              R18               4   520-litres
1481  Tubeless Radial Tyres              NaN               5          350
1482        Tubeless,Radial               15               5   300-litres

        Top Speed   Acceleration Ground Clearance Unladen
0             NaN            NaN                      NaN
1        135 Kmph     19 Seconds                      NaN
2             NaN            NaN                      NaN
3        180 Kmph  12.36 seconds                      NaN
4             NaN            NaN                      NaN
...           ...            ...                      ...
1478     175 kmph   12.5 Seconds                      NaN
1479     250 Kmph    6.4 Seconds                      NaN
1480      235kmph            7.5                      NaN
1481  154.19 kmph  13.25 Seconds                   209 mm
1482     155 Kmph   13.3 Seconds                      NaN

[1483 rows x 35 columns]

In [146]:
import pandas as pd

# Assuming combined_df, top_df, top3_df, data2_df, top_2_df, data_df are already defined

# Concatenate the DataFrames column-wise
final_df_hyderabad = pd.concat([combined_df, top_df, top3_df, data2_df, top_2_df, data_df], axis=1)

# Display the final DataFrame
print("Final DataFrame (final_df_hyderabad):")
print(final_df_hyderabad)

Final DataFrame (final_df_hyderabad):
      it      ft         bt        km transmission  ownerNo      owner  \
0      0  Petrol  Hatchback    20,000    Automatic        1  1st Owner
1      0  Petrol  Hatchback    85,582       Manual        2  2nd Owner
2      0  Petrol        SUV    10,000       Manual        1  1st Owner
3      0  Petrol  Hatchback    50,750       Manual        1  1st Owner
4      0  Petrol        SUV    10,000    Automatic        1  1st Owner
...   ..     ...        ...       ...          ...      ...        ...
1478   0  Diesel        SUV    60,000       Manual        1  1st Owner
1479   0  Diesel      Sedan    50,000    Automatic        1  1st Owner
1480   0  Diesel      Sedan  1,20,000    Automatic        3  3rd Owner
1481   0  Diesel        SUV    50,000    Automatic        2  2nd Owner
1482   0  Diesel        MUV  1,00,000       Manual        1  1st Owner

             oem            model  modelYear  ...  Power Antenna  \
0     Volkswagen  Volkswagen Polo       2022  ...            NaN
1        Hyundai      Hyundai EON       2014  ...            NaN
2        Hyundai    Hyundai Venue       2023  ...            NaN
3         Maruti    Maruti Baleno       2017  ...            NaN
4       Mahindra    Mahindra Thar       2022  ...            NaN
...          ...              ...        ...  ...            ...
1478    Mahindra  Mahindra XUV500       2013  ...            NaN
1479      Jaguar        Jaguar XF       2014  ...            NaN
1480         BMW     BMW 5 Series       2018  ...            NaN
1481        Tata       Tata Nexon       2019  ...            NaN
1482      Toyota    Toyota Innova       2015  ...            NaN

     Integrated Antenna Tinted Glass Rear Spoiler Removable Convertible Top  \
0                   NaN          NaN          NaN                       NaN
1                   NaN          NaN          NaN                       NaN
2                   NaN          NaN          NaN                       NaN
3                   NaN          NaN          NaN                       NaN
4                   NaN          NaN          NaN                       NaN
...                 ...          ...          ...                       ...
1478                NaN          NaN          NaN                       NaN
1479                NaN          NaN          NaN                       NaN
1480                NaN          NaN          NaN                       NaN
1481                NaN          NaN          NaN                       NaN
1482                NaN          NaN          NaN                       NaN

     Roof Carrier Sun Roof Moon Roof Side Stepper  \
0             NaN      NaN       NaN          NaN
1             NaN      NaN       NaN          NaN
2             NaN      NaN       NaN          NaN
3             NaN      NaN       NaN          NaN
4             NaN      NaN       NaN          NaN
...           ...      ...       ...          ...
1478          NaN      NaN       NaN          NaN
1479          NaN      NaN       NaN          NaN
1480          NaN      NaN       NaN          NaN
1481          NaN      NaN       NaN          NaN
1482          NaN      NaN       NaN          NaN

     Outside Rear View Mirror Turn Indicators
0                                         NaN
1                                         NaN
2                                         NaN
3                                         NaN
4                                         NaN
...                                       ...
1478                                      NaN
1479                                      NaN
1480                                      NaN
1481                                      NaN
1482                                      NaN

[1483 rows x 200 columns]

In [147]:
## # Assuming final_df_chennai is already defined

# Specify the file name
file_name = "final_df_hyderabad.xlsx"

# Save the DataFrame to an Excel file
final_df_hyderabad.to_excel(file_name, index=False)

print(f"DataFrame has been saved to {file_name}")

DataFrame has been saved to final_df_hyderabad.xlsx

## Jaipur :

In [148]:
## import pandas as pd
import ast  # Use ast for safer evaluation of strings to dictionaries

# Step 1: Load your DataFrame from the Excel file
file_path = 'jaipur_cars.xlsx'  # Your Excel file name
df = pd.read_excel(file_path)

# Step 2: Initialize an empty list to hold the structured data
unwound_data = []

# Step 3: Loop through each row of the DataFrame
for index, row in df.iterrows():
    # Initialize a dictionary for the current row
    combined_data = {}
    
    # Specify the columns containing dictionaries
    dict_columns = ['new_car_detail', 'new_car_overview', 'new_car_feature', 'new_car_specs']
    
    # Step 4: Extract and merge dictionaries from the specified columns
    for col in dict_columns:
        try:
            # Safely convert the string representation of the dictionary to an actual dictionary
            dict_value = ast.literal_eval(row[col])  
            if isinstance(dict_value, dict):
                combined_data.update(dict_value)  # Merge the extracted dictionary
        except Exception as e:
            print(f"Error parsing row {index}, column {col}: {e}")

    # Append the combined data for the current row to the unwound data list
    unwound_data.append(combined_data)

# Step 5: Create a DataFrame from the unwound data
unwound_df = pd.DataFrame(unwound_data)

# Optional: Display the unwound DataFrame
print(unwound_df)

# Save the unwound DataFrame to a new Excel file if needed
#unwound_df.to_excel('unwound_bangalore_cars.xlsx', index=False)

      it      ft         bt        km transmission  ownerNo      owner  \
0      0  Diesel  Hatchback  1,20,000       Manual        2  2nd Owner
1      0  Petrol  Hatchback    66,951       Manual        1  1st Owner
2      0  Petrol  Hatchback    80,000    Automatic        2  2nd Owner
3      0  Petrol  Hatchback    44,392       Manual        1  1st Owner
4      0  Petrol  Hatchback    40,000    Automatic        1  1st Owner
...   ..     ...        ...       ...          ...      ...        ...
1115   0  Petrol  Hatchback  1,20,000       Manual        1  1st Owner
1116   0  Petrol  Hatchback    70,000       Manual        1  1st Owner
1117   0  Petrol        SUV    20,000       Manual        1  1st Owner
1118   0  Petrol  Hatchback    40,000       Manual        1  1st Owner
1119   0  Petrol  Hatchback    80,000       Manual        1  1st Owner

            oem              model  modelYear  ...        price priceActual  \
0       Hyundai        Hyundai i20       2015  ...  ₹ 5.10 Lakh
1        Maruti       Maruti Swift       2012  ...  ₹ 3.81 Lakh
2        Maruti     Maruti Celerio       2016  ...  ₹ 3.20 Lakh
3       Hyundai  Hyundai Grand i10       2017  ...  ₹ 4.20 Lakh
4        Maruti     Maruti Wagon R       2016  ...  ₹ 3.50 Lakh
...         ...                ...        ...  ...          ...         ...
1115  Chevrolet     Chevrolet Beat       2011  ...  ₹ 1.08 Lakh
1116     Maruti        Maruti Alto       2007  ...  ₹ 1.05 Lakh
1117    Renault      Renault Kiger       2022  ...  ₹ 8.50 Lakh
1118     Maruti        Maruti Alto       2009  ...     ₹ 1 Lakh
1119     Maruti      Maruti Baleno       2018  ...     ₹ 5 Lakh

     priceSaving priceFixedText  \
0                          None
1                          None
2                          None
3                          None
4                          None
...          ...            ...
1115                       None
1116                       None
1117                       None
1118                       None
1119                       None

                                           trendingText         heading  \
0     {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
1     {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
2     {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
3     {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
4     {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
...                                                 ...             ...
1115  {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
1116  {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
1117  {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
1118  {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
1119  {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications

                                                    top bottomData  \
0     [{'key': 'Mileage', 'value': '22.54 kmpl'}, {'...       None
1     [{'key': 'Mileage', 'value': '22.38 kmpl'}, {'...       None
2     [{'key': 'Mileage', 'value': '23.1 kmpl'}, {'k...       None
3     [{'key': 'Mileage', 'value': '18.9 kmpl'}, {'k...       None
4     [{'key': 'Mileage', 'value': '20.51 kmpl'}, {'...       None
...                                                 ...        ...
1115  [{'key': 'Mileage', 'value': '18.6 kmpl'}, {'k...       None
1116  [{'key': 'Mileage', 'value': '19.7 kmpl'}, {'k...       None
1117  [{'key': 'Mileage', 'value': '19.17 kmpl'}, {'...       None
1118  [{'key': 'Mileage', 'value': '19.7 kmpl'}, {'k...       None
1119  [{'key': 'Mileage', 'value': '21.4 kmpl'}, {'k...       None

                                                   data commonIcon
0     [{'heading': 'Engine and Transmission', 'subHe...
1     [{'heading': 'Engine and Transmission', 'subHe...
2     [{'heading': 'Engine and Transmission', 'subHe...
3     [{'heading': 'Engine and Transmission', 'subHe...
4     [{'heading': 'Engine and Transmission', 'subHe...
...                                                 ...        ...
1115  [{'heading': 'Engine and Transmission', 'subHe...
1116  [{'heading': 'Engine and Transmission', 'subHe...
1117  [{'heading': 'Engine and Transmission', 'subHe...
1118  [{'heading': 'Engine and Transmission', 'subHe...
1119  [{'heading': 'Engine and Transmission', 'subHe...

[1120 rows x 22 columns]

In [149]:
import pandas as pd

# Step 1: Read the Excel file
df = pd.read_excel("jaipur_cars.xlsx")

# Step 2: Initialize an empty list to hold structured data
structured_data = []

# Step 3: Loop through each row of the DataFrame
for index, row in df.iterrows():
    row_data = {}
    
    # Convert the string representation of the dictionary to an actual dictionary
    try:
        dict_value = eval(row['new_car_detail'])  # Replace eval with ast.literal_eval for safer evaluation
        if isinstance(dict_value, dict):
            row_data = dict_value
    except Exception as e:
        print(f"Error parsing row {index}: {e}")
        row_data = None

    # Append the row dictionary to the structured data list
    structured_data.append(row_data)

# Step 4: Create a DataFrame from the list of dictionaries in 'new_car_detail'
unwound_df = pd.json_normalize(structured_data)

# Optional: Display the unwound DataFrame
print(unwound_df)

# Save the unwound DataFrame to a new Excel file
#unwound_df.to_excel('unwound_new_car_detail.xlsx', index=False)

      it      ft         bt        km transmission  ownerNo      owner  \
0      0  Diesel  Hatchback  1,20,000       Manual        2  2nd Owner
1      0  Petrol  Hatchback    66,951       Manual        1  1st Owner
2      0  Petrol  Hatchback    80,000    Automatic        2  2nd Owner
3      0  Petrol  Hatchback    44,392       Manual        1  1st Owner
4      0  Petrol  Hatchback    40,000    Automatic        1  1st Owner
...   ..     ...        ...       ...          ...      ...        ...
1115   0  Petrol  Hatchback  1,20,000       Manual        1  1st Owner
1116   0  Petrol  Hatchback    70,000       Manual        1  1st Owner
1117   0  Petrol        SUV    20,000       Manual        1  1st Owner
1118   0  Petrol  Hatchback    40,000       Manual        1  1st Owner
1119   0  Petrol  Hatchback    80,000       Manual        1  1st Owner

            oem              model  modelYear  centralVariantId  \
0       Hyundai        Hyundai i20       2015              1487
1        Maruti       Maruti Swift       2012             10403
2        Maruti     Maruti Celerio       2016              3982
3       Hyundai  Hyundai Grand i10       2017              5602
4        Maruti     Maruti Wagon R       2016              4319
...         ...                ...        ...               ...
1115  Chevrolet     Chevrolet Beat       2011               438
1116     Maruti        Maruti Alto       2007              3917
1117    Renault      Renault Kiger       2022              8350
1118     Maruti        Maruti Alto       2009              3904
1119     Maruti      Maruti Baleno       2018              3962

               variantName        price priceActual priceSaving  \
0            Asta 1.4 CRDi  ₹ 5.10 Lakh
1                      VXI  ₹ 3.81 Lakh
2                   VXI AT  ₹ 3.20 Lakh
3     1.2 Kappa Magna BSIV  ₹ 4.20 Lakh
4                  AMT VXI  ₹ 3.50 Lakh
...                    ...          ...         ...         ...
1115                    LT  ₹ 1.08 Lakh
1116                   STD  ₹ 1.05 Lakh
1117                   RXZ  ₹ 8.50 Lakh
1118                   Std     ₹ 1 Lakh
1119             1.2 Delta     ₹ 5 Lakh

     priceFixedText                                trendingText.imgUrl  \
0              None  https://stimg.cardekho.com/used-cars/common/ic...
1              None  https://stimg.cardekho.com/used-cars/common/ic...
2              None  https://stimg.cardekho.com/used-cars/common/ic...
3              None  https://stimg.cardekho.com/used-cars/common/ic...
4              None  https://stimg.cardekho.com/used-cars/common/ic...
...             ...                                                ...
1115           None  https://stimg.cardekho.com/used-cars/common/ic...
1116           None  https://stimg.cardekho.com/used-cars/common/ic...
1117           None  https://stimg.cardekho.com/used-cars/common/ic...
1118           None  https://stimg.cardekho.com/used-cars/common/ic...
1119           None  https://stimg.cardekho.com/used-cars/common/ic...

     trendingText.heading                    trendingText.desc
0           Trending Car!  High chances of sale in next 6 days
1           Trending Car!  High chances of sale in next 6 days
2           Trending Car!  High chances of sale in next 6 days
3           Trending Car!  High chances of sale in next 6 days
4           Trending Car!  High chances of sale in next 6 days
...                   ...                                  ...
1115        Trending Car!  High chances of sale in next 6 days
1116        Trending Car!  High chances of sale in next 6 days
1117        Trending Car!  High chances of sale in next 6 days
1118        Trending Car!  High chances of sale in next 6 days
1119        Trending Car!  High chances of sale in next 6 days

[1120 rows x 19 columns]

In [150]:
import pandas as pd

# Step 1: Read the Excel file
df = pd.read_excel("jaipur_cars.xlsx")

# Step 2: Initialize an empty list to hold structured data
structured_data = []

# Step 3: Loop through each row of the DataFrame
for index, row in df.iterrows():
    row_data = {}
    
    # Convert the string representation of the dictionary to an actual dictionary
    try:
        dict_value = eval(row['new_car_overview'])  # Replace eval with ast.literal_eval for safer evaluation
        if isinstance(dict_value, dict):
            row_data = dict_value
    except Exception as e:
        print(f"Error parsing row {index}: {e}")
        row_data = None

    # Append the row dictionary to the structured data list
    structured_data.append(row_data)

# Step 4: Create a DataFrame from the list of dictionaries in 'new_car_detail'
unwound_df1 = pd.json_normalize(structured_data)

# Optional: Display the unwound DataFrame
print(unwound_df1)

# Save the unwound DataFrame to a new Excel file
#unwound_df.to_excel('unwound_new_car_detail.xlsx', index=False)

           heading                                                top  \
0     Car overview  [{'key': 'Registration Year', 'value': '2015',...
1     Car overview  [{'key': 'Registration Year', 'value': 'Jan 20...
2     Car overview  [{'key': 'Registration Year', 'value': '2016',...
3     Car overview  [{'key': 'Registration Year', 'value': 'Apr 20...
4     Car overview  [{'key': 'Registration Year', 'value': '2016',...
...            ...                                                ...
1115  Car overview  [{'key': 'Registration Year', 'value': '2011',...
1116  Car overview  [{'key': 'Registration Year', 'value': '2007',...
1117  Car overview  [{'key': 'Registration Year', 'value': '2022',...
1118  Car overview  [{'key': 'Registration Year', 'value': '2009',...
1119  Car overview  [{'key': 'Registration Year', 'value': '2018',...

     bottomData
0          None
1          None
2          None
3          None
4          None
...         ...
1115       None
1116       None
1117       None
1118       None
1119       None

[1120 rows x 3 columns]

In [151]:
import pandas as pd

# Step 1: Read the Excel file
df = pd.read_excel("jaipur_cars.xlsx")

# Step 2: Initialize an empty list to hold structured data
structured_data = []

# Step 3: Loop through each row of the DataFrame
for index, row in df.iterrows():
    row_data = {}
    
    # Convert the string representation of the dictionary to an actual dictionary
    try:
        dict_value = eval(row['new_car_feature'])  # Replace eval with ast.literal_eval for safer evaluation
        if isinstance(dict_value, dict):
            row_data = dict_value
    except Exception as e:
        print(f"Error parsing row {index}: {e}")
        row_data = None

    # Append the row dictionary to the structured data list
    structured_data.append(row_data)

# Step 4: Create a DataFrame from the list of dictionaries in 'new_car_detail'
unwound_df2 = pd.json_normalize(structured_data)

# Optional: Display the unwound DataFrame
print(unwound_df2)

# Save the unwound DataFrame to a new Excel file
#unwound_df.to_excel('unwound_new_car_detail.xlsx', index=False)

       heading                                                top  \
0     Features  [{'value': 'Power Steering'}, {'value': 'Power...
1     Features  [{'value': 'Power Steering'}, {'value': 'Power...
2     Features  [{'value': 'Power Steering'}, {'value': 'Power...
3     Features  [{'value': 'Power Steering'}, {'value': 'Power...
4     Features  [{'value': 'Power Steering'}, {'value': 'Power...
...        ...                                                ...
1115  Features  [{'value': 'Power Steering'}, {'value': 'Power...
1116  Features  [{'value': 'Low Fuel Warning Light'}, {'value'...
1117  Features  [{'value': 'Power Steering'}, {'value': 'Power...
1118  Features  [{'value': 'Low Fuel Warning Light'}, {'value'...
1119  Features  [{'value': 'Power Steering'}, {'value': 'Power...

                                                   data  \
0     [{'heading': 'Comfort & Convenience', 'subHead...
1     [{'heading': 'Comfort & Convenience', 'subHead...
2     [{'heading': 'Comfort & Convenience', 'subHead...
3     [{'heading': 'Comfort & Convenience', 'subHead...
4     [{'heading': 'Comfort & Convenience', 'subHead...
...                                                 ...
1115  [{'heading': 'Comfort & Convenience', 'subHead...
1116  [{'heading': 'Comfort & Convenience', 'subHead...
1117  [{'heading': 'Comfort & Convenience', 'subHead...
1118  [{'heading': 'Comfort & Convenience', 'subHead...
1119  [{'heading': 'Comfort & Convenience', 'subHead...

                                             commonIcon
0     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
2     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
3     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
4     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
...                                                 ...
1115  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1116  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1117  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1118  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1119  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg

[1120 rows x 4 columns]

In [152]:
import pandas as pd

# Step 1: Read the Excel file
df = pd.read_excel("jaipur_cars.xlsx")

# Step 2: Initialize an empty list to hold structured data
structured_data = []

# Step 3: Loop through each row of the DataFrame
for index, row in df.iterrows():
    row_data = {}
    
    # Convert the string representation of the dictionary to an actual dictionary
    try:
        dict_value = eval(row['new_car_specs'])  # Replace eval with ast.literal_eval for safer evaluation
        if isinstance(dict_value, dict):
            row_data = dict_value
    except Exception as e:
        print(f"Error parsing row {index}: {e}")
        row_data = None

    # Append the row dictionary to the structured data list
    structured_data.append(row_data)

# Step 4: Create a DataFrame from the list of dictionaries in 'new_car_detail'
unwound_df3 = pd.json_normalize(structured_data)

# Optional: Display the unwound DataFrame
print(unwound_df3)

# Save the unwound DataFrame to a new Excel file
#unwound_df.to_excel('unwound_new_car_detail.xlsx', index=False)

             heading                                                top  \
0     Specifications  [{'key': 'Mileage', 'value': '22.54 kmpl'}, {'...
1     Specifications  [{'key': 'Mileage', 'value': '22.38 kmpl'}, {'...
2     Specifications  [{'key': 'Mileage', 'value': '23.1 kmpl'}, {'k...
3     Specifications  [{'key': 'Mileage', 'value': '18.9 kmpl'}, {'k...
4     Specifications  [{'key': 'Mileage', 'value': '20.51 kmpl'}, {'...
...              ...                                                ...
1115  Specifications  [{'key': 'Mileage', 'value': '18.6 kmpl'}, {'k...
1116  Specifications  [{'key': 'Mileage', 'value': '19.7 kmpl'}, {'k...
1117  Specifications  [{'key': 'Mileage', 'value': '19.17 kmpl'}, {'...
1118  Specifications  [{'key': 'Mileage', 'value': '19.7 kmpl'}, {'k...
1119  Specifications  [{'key': 'Mileage', 'value': '21.4 kmpl'}, {'k...

                                                   data commonIcon
0     [{'heading': 'Engine and Transmission', 'subHe...
1     [{'heading': 'Engine and Transmission', 'subHe...
2     [{'heading': 'Engine and Transmission', 'subHe...
3     [{'heading': 'Engine and Transmission', 'subHe...
4     [{'heading': 'Engine and Transmission', 'subHe...
...                                                 ...        ...
1115  [{'heading': 'Engine and Transmission', 'subHe...
1116  [{'heading': 'Engine and Transmission', 'subHe...
1117  [{'heading': 'Engine and Transmission', 'subHe...
1118  [{'heading': 'Engine and Transmission', 'subHe...
1119  [{'heading': 'Engine and Transmission', 'subHe...

[1120 rows x 4 columns]

In [153]:
import pandas as pd

# Assume df1, df2, df3, and df4 are your four DataFrames

# Concatenate the DataFrames column-wise
combined_df = pd.concat([unwound_df, unwound_df1, unwound_df2, unwound_df3], axis=1)

# Optional: Display the combined DataFrame
print(combined_df)

# Save the combined DataFrame to a new Excel file if needed
combined_df.to_excel('combined_data_column_wise_jaipur.xlsx', index=False)

      it      ft         bt        km transmission  ownerNo      owner  \
0      0  Diesel  Hatchback  1,20,000       Manual        2  2nd Owner
1      0  Petrol  Hatchback    66,951       Manual        1  1st Owner
2      0  Petrol  Hatchback    80,000    Automatic        2  2nd Owner
3      0  Petrol  Hatchback    44,392       Manual        1  1st Owner
4      0  Petrol  Hatchback    40,000    Automatic        1  1st Owner
...   ..     ...        ...       ...          ...      ...        ...
1115   0  Petrol  Hatchback  1,20,000       Manual        1  1st Owner
1116   0  Petrol  Hatchback    70,000       Manual        1  1st Owner
1117   0  Petrol        SUV    20,000       Manual        1  1st Owner
1118   0  Petrol  Hatchback    40,000       Manual        1  1st Owner
1119   0  Petrol  Hatchback    80,000       Manual        1  1st Owner

            oem              model  modelYear  ...  \
0       Hyundai        Hyundai i20       2015  ...
1        Maruti       Maruti Swift       2012  ...
2        Maruti     Maruti Celerio       2016  ...
3       Hyundai  Hyundai Grand i10       2017  ...
4        Maruti     Maruti Wagon R       2016  ...
...         ...                ...        ...  ...
1115  Chevrolet     Chevrolet Beat       2011  ...
1116     Maruti        Maruti Alto       2007  ...
1117    Renault      Renault Kiger       2022  ...
1118     Maruti        Maruti Alto       2009  ...
1119     Maruti      Maruti Baleno       2018  ...

                                                    top bottomData   heading  \
0     [{'key': 'Registration Year', 'value': '2015',...       None  Features
1     [{'key': 'Registration Year', 'value': 'Jan 20...       None  Features
2     [{'key': 'Registration Year', 'value': '2016',...       None  Features
3     [{'key': 'Registration Year', 'value': 'Apr 20...       None  Features
4     [{'key': 'Registration Year', 'value': '2016',...       None  Features
...                                                 ...        ...       ...
1115  [{'key': 'Registration Year', 'value': '2011',...       None  Features
1116  [{'key': 'Registration Year', 'value': '2007',...       None  Features
1117  [{'key': 'Registration Year', 'value': '2022',...       None  Features
1118  [{'key': 'Registration Year', 'value': '2009',...       None  Features
1119  [{'key': 'Registration Year', 'value': '2018',...       None  Features

                                                    top  \
0     [{'value': 'Power Steering'}, {'value': 'Power...
1     [{'value': 'Power Steering'}, {'value': 'Power...
2     [{'value': 'Power Steering'}, {'value': 'Power...
3     [{'value': 'Power Steering'}, {'value': 'Power...
4     [{'value': 'Power Steering'}, {'value': 'Power...
...                                                 ...
1115  [{'value': 'Power Steering'}, {'value': 'Power...
1116  [{'value': 'Low Fuel Warning Light'}, {'value'...
1117  [{'value': 'Power Steering'}, {'value': 'Power...
1118  [{'value': 'Low Fuel Warning Light'}, {'value'...
1119  [{'value': 'Power Steering'}, {'value': 'Power...

                                                   data  \
0     [{'heading': 'Comfort & Convenience', 'subHead...
1     [{'heading': 'Comfort & Convenience', 'subHead...
2     [{'heading': 'Comfort & Convenience', 'subHead...
3     [{'heading': 'Comfort & Convenience', 'subHead...
4     [{'heading': 'Comfort & Convenience', 'subHead...
...                                                 ...
1115  [{'heading': 'Comfort & Convenience', 'subHead...
1116  [{'heading': 'Comfort & Convenience', 'subHead...
1117  [{'heading': 'Comfort & Convenience', 'subHead...
1118  [{'heading': 'Comfort & Convenience', 'subHead...
1119  [{'heading': 'Comfort & Convenience', 'subHead...

                                             commonIcon         heading  \
0     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
1     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
2     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
3     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
4     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
...                                                 ...             ...
1115  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
1116  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
1117  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
1118  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
1119  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications

                                                    top  \
0     [{'key': 'Mileage', 'value': '22.54 kmpl'}, {'...
1     [{'key': 'Mileage', 'value': '22.38 kmpl'}, {'...
2     [{'key': 'Mileage', 'value': '23.1 kmpl'}, {'k...
3     [{'key': 'Mileage', 'value': '18.9 kmpl'}, {'k...
4     [{'key': 'Mileage', 'value': '20.51 kmpl'}, {'...
...                                                 ...
1115  [{'key': 'Mileage', 'value': '18.6 kmpl'}, {'k...
1116  [{'key': 'Mileage', 'value': '19.7 kmpl'}, {'k...
1117  [{'key': 'Mileage', 'value': '19.17 kmpl'}, {'...
1118  [{'key': 'Mileage', 'value': '19.7 kmpl'}, {'k...
1119  [{'key': 'Mileage', 'value': '21.4 kmpl'}, {'k...

                                                   data commonIcon
0     [{'heading': 'Engine and Transmission', 'subHe...
1     [{'heading': 'Engine and Transmission', 'subHe...
2     [{'heading': 'Engine and Transmission', 'subHe...
3     [{'heading': 'Engine and Transmission', 'subHe...
4     [{'heading': 'Engine and Transmission', 'subHe...
...                                                 ...        ...
1115  [{'heading': 'Engine and Transmission', 'subHe...
1116  [{'heading': 'Engine and Transmission', 'subHe...
1117  [{'heading': 'Engine and Transmission', 'subHe...
1118  [{'heading': 'Engine and Transmission', 'subHe...
1119  [{'heading': 'Engine and Transmission', 'subHe...

[1120 rows x 30 columns]

In [154]:
import pandas as pd

# Example DataFrame with repeating columns (for demonstration purposes)
# combined_df = pd.DataFrame(...)  # Assume this is your existing DataFrame

# Step 1: Get the current column names
original_columns = combined_df.columns

# Step 2: Create a new list to hold unique column names
new_columns = []
column_count = {}

# Step 3: Loop through original columns and create unique names
for col in original_columns:
    if col in column_count:
        column_count[col] += 1
        new_columns.append(f"{col}_{column_count[col]}")  # Append count as suffix
    else:
        column_count[col] = 1
        new_columns.append(col)  # Keep original name for the first occurrence

# Step 4: Assign the new column names to the DataFrame
combined_df.columns = new_columns

# Optional: Display the updated DataFrame columns
print(combined_df.columns)

Index(['it', 'ft', 'bt', 'km', 'transmission', 'ownerNo', 'owner', 'oem',
       'model', 'modelYear', 'centralVariantId', 'variantName', 'price',
       'priceActual', 'priceSaving', 'priceFixedText', 'trendingText.imgUrl',
       'trendingText.heading', 'trendingText.desc', 'heading', 'top',
       'bottomData', 'heading_2', 'top_2', 'data', 'commonIcon', 'heading_3',
       'top_3', 'data_2', 'commonIcon_2'],
      dtype='object')

In [155]:
import pandas as pd

# Function to extract and convert 'top1' into a DataFrame
def extract_top_to_dataframe(main_df):
    rows = []  # To hold the extracted data
    
    # Loop through each row in the main DataFrame
    for _, row in main_df.iterrows():
        top3_data = row['top_3']  # Access the list directly
        
        # Check if the top1_data is a list
        if isinstance(top3_data, list):
            # Create a dictionary from the extracted key-value pairs
            row_dict = {item['key']: item['value'] for item in top3_data if 'key' in item and 'value' in item}
            rows.append(row_dict)  # Add the dictionary to the rows list
        else:
            print(f"Unexpected format for row: {row}. Expected a list but got {type(top3_data)}")
    
    # Create a new DataFrame from the rows list
    top3_df = pd.DataFrame(rows)
    return top3_df

# Extracting the DataFrame from 'top1'
top3_df = extract_top_to_dataframe(combined_df)

# Display the new DataFrame
print(top3_df)

         Mileage   Engine Max Power    Torque Wheel Size Seats
0     22.54 kmpl  1396 CC  88.73bhp   219.7Nm         16     5
1     22.38 kmpl  1197 CC  88.50bhp     113Nm        NaN     5
2      23.1 kmpl   998 CC  67.04bhp      90Nm        NaN     5
3      18.9 kmpl  1197 CC  81.86bhp  113.75nm        NaN     5
4     20.51 kmpl   998 CC     67bhp      90Nm        NaN     5
...          ...      ...       ...       ...        ...   ...
1115   18.6 kmpl  1199 CC   79.4bhp     108Nm         14     5
1116   19.7 kmpl   796 CC   46.3bhp      62Nm         12     5
1117  19.17 kmpl   999 CC  71.01bhp      96Nm         16     5
1118   19.7 kmpl   796 CC   46.3bhp      62Nm         12     5
1119   21.4 kmpl  1197 CC   83.1bhp     115Nm        NaN     5

[1120 rows x 6 columns]

In [156]:
import pandas as pd

# Assuming combined_df is your existing DataFrame with a column named 'top_2'
# combined_df = ...  # Your existing DataFrame

def extract_list_of_dicts_to_dataframe(main_df, column_name):
    # Initialize a list to store the extracted data
    extracted_data = []

    for index, row in main_df.iterrows():
        # Check if the cell is a list and not empty
        if isinstance(row[column_name], list) and row[column_name]:
            # Create a dictionary from the extracted values
            row_dict = {item['value']: True for item in row[column_name]}
        else:
            row_dict = {}

        extracted_data.append(row_dict)

    # Create a DataFrame from the extracted data
    extracted_df = pd.DataFrame(extracted_data)

    return extracted_df

# Extract DataFrame for top_2
top_2_df = extract_list_of_dicts_to_dataframe(combined_df, 'top_2')

# Display the DataFrame
print("DataFrame for top_2:")
print(top_2_df)

DataFrame for top_2:
     Power Steering Power Windows Front Air Conditioner Heater  \
0              True                True            True   True
1              True                True            True   True
2              True                True            True   True
3              True                True            True   True
4              True                True            True   True
...             ...                 ...             ...    ...
1115           True                True            True   True
1116            NaN                 NaN             NaN    NaN
1117           True                True            True   True
1118            NaN                 NaN             NaN    NaN
1119           True                True            True   True

     Adjustable Head Lights Fog Lights Front Anti Lock Braking System  \
0                      True             True                     True
1                      True              NaN                     True
2                      True              NaN                      NaN
3                      True              NaN                     True
4                      True             True                      NaN
...                     ...              ...                      ...
1115                    NaN             True                      NaN
1116                    NaN              NaN                      NaN
1117                   True              NaN                     True
1118                    NaN              NaN                      NaN
1119                   True              NaN                     True

     Centeral Locking Cd Player Power Adjustable Exterior Rear View Mirror  \
0                True      True                                        NaN
1                 NaN       NaN                                       True
2                True       NaN                                        NaN
3                True       NaN                                       True
4                True      True                                        NaN
...               ...       ...                                        ...
1115             True      True                                        NaN
1116              NaN       NaN                                        NaN
1117             True       NaN                                       True
1118              NaN       NaN                                        NaN
1119             True      True                                       True

      ... Tachometer Cup Holders Front Rear Window Wiper Digital Odometer  \
0     ...        NaN               NaN               NaN              NaN
1     ...        NaN               NaN               NaN              NaN
2     ...        NaN               NaN               NaN              NaN
3     ...        NaN               NaN               NaN              NaN
4     ...        NaN               NaN               NaN              NaN
...   ...        ...               ...               ...              ...
1115  ...        NaN               NaN               NaN              NaN
1116  ...        NaN               NaN               NaN              NaN
1117  ...        NaN               NaN               NaN              NaN
1118  ...        NaN               NaN               NaN              NaN
1119  ...        NaN               NaN               NaN              NaN

     Power Antenna Number Of Speaker Vanity Mirror Integrated Antenna  \
0              NaN               NaN           NaN                NaN
1              NaN               NaN           NaN                NaN
2              NaN               NaN           NaN                NaN
3              NaN               NaN           NaN                NaN
4              NaN               NaN           NaN                NaN
...            ...               ...           ...                ...
1115           NaN               NaN           NaN                NaN
1116           NaN               NaN           NaN                NaN
1117           NaN               NaN           NaN                NaN
1118           NaN               NaN           NaN                NaN
1119           NaN               NaN           NaN                NaN

     Audio System Remote Control Trunk Light
0                            NaN         NaN
1                            NaN         NaN
2                            NaN         NaN
3                            NaN         NaN
4                            NaN         NaN
...                          ...         ...
1115                         NaN         NaN
1116                         NaN         NaN
1117                         NaN         NaN
1118                         NaN         NaN
1119                         NaN         NaN

[1120 rows x 55 columns]

In [157]:
import pandas as pd

# Function to extract and convert 'top1' into a DataFrame
def extract_top_to_dataframe(main_df):
    rows = []  # To hold the extracted data
    
    # Loop through each row in the main DataFrame
    for _, row in main_df.iterrows():
        top_data = row['top']  # Access the list directly
        
        # Check if the top1_data is a list
        if isinstance(top_data, list):
            # Create a dictionary from the extracted key-value pairs
            row_dict = {item['key']: item['value'] for item in top_data if 'key' in item and 'value' in item}
            rows.append(row_dict)  # Add the dictionary to the rows list
        else:
            print(f"Unexpected format for row: {row}. Expected a list but got {type(top_data)}")
    
    # Create a new DataFrame from the rows list
    top_df = pd.DataFrame(rows)
    return top_df

# Extracting the DataFrame from 'top1'
top_df = extract_top_to_dataframe(combined_df)

# Display the new DataFrame
print(top_df)

     Registration Year     Insurance Validity Fuel Type    Seats  \
0                 2015  Third Party insurance    Diesel  5 Seats
1             Jan 2012            Third Party    Petrol  5 Seats
2                 2016  Third Party insurance    Petrol  5 Seats
3             Apr 2017  Third Party insurance    Petrol  5 Seats
4                 2016  Third Party insurance    Petrol  5 Seats
...                ...                    ...       ...      ...
1115              2011  Third Party insurance    Petrol  5 Seats
1116              2007  Third Party insurance    Petrol  5 Seats
1117              2022  Third Party insurance    Petrol  5 Seats
1118              2009  Third Party insurance    Petrol  5 Seats
1119              2018  Third Party insurance    Petrol  5 Seats

        Kms Driven   RTO     Ownership Engine Displacement Transmission  \
0     1,20,000 Kms  RJ13  Second Owner             1396 cc       Manual
1       66,951 Kms  RJ14   First Owner             1197 cc       Manual
2       80,000 Kms  RJ14  Second Owner              998 cc    Automatic
3       44,392 Kms  RJ14   First Owner             1197 cc       Manual
4       40,000 Kms  RJ14   First Owner              998 cc    Automatic
...            ...   ...           ...                 ...          ...
1115  1,20,000 Kms  RJ14   First Owner             1199 cc       Manual
1116    70,000 Kms  RJ30   First Owner              796 cc       Manual
1117    20,000 Kms  RJ45   First Owner              999 cc       Manual
1118    40,000 Kms   NaN   First Owner              796 cc       Manual
1119    80,000 Kms  UP82   First Owner             1197 cc       Manual

      Year of Manufacture
0                  2015.0
1                  2012.0
2                  2016.0
3                  2017.0
4                  2016.0
...                   ...
1115               2011.0
1116               2007.0
1117               2022.0
1118               2009.0
1119               2018.0

[1120 rows x 10 columns]

In [158]:
import pandas as pd

def extract_data_to_dataframe(main_df, column_name):
    # Create a list to hold the rows for the new DataFrame
    data_rows = []
    
    # Iterate over each row in the main DataFrame
    for index, row in main_df.iterrows():
        # Check if the cell is a list and contains dictionaries
        if isinstance(row[column_name], list) and row[column_name]:
            # Extract the 'list' field from the first dictionary in the row
            list_values = row[column_name][0].get('list', [])
            # Create a dictionary to hold values for this row
            row_dict = {item['value']: True for item in list_values}
            # Append the dictionary to the rows list
            data_rows.append(row_dict)
        else:
            # If there's no data, append an empty dictionary
            data_rows.append({})

    # Create a DataFrame from the list of dictionaries
    data_df = pd.DataFrame(data_rows)

    return data_df

# Extract DataFrame for the 'data' column
data_df = extract_data_to_dataframe(combined_df, 'data')

# Display the DataFrame
print("DataFrame for data:")
print(data_df)

DataFrame for data:
     Power Steering Power Windows Front Power Windows Rear  \
0              True                True               True
1              True                True               True
2              True                True               True
3              True                True               True
4              True                True               True
...             ...                 ...                ...
1115           True                True               True
1116            NaN                 NaN                NaN
1117           True                True               True
1118            NaN                 NaN                NaN
1119           True                True               True

     Air Quality Control Remote Trunk Opener Remote Fuel Lid Opener  \
0                   True                True                   True
1                    NaN                 NaN                    NaN
2                    NaN                True                   True
3                    NaN                 NaN                    NaN
4                    NaN                True                   True
...                  ...                 ...                    ...
1115                 NaN                True                   True
1116                 NaN                 NaN                    NaN
1117                True                 NaN                    NaN
1118                 NaN                 NaN                    NaN
1119                 NaN                True                   True

     Low Fuel Warning Light Accessory Power Outlet Trunk Light Vanity Mirror  \
0                      True                   True        True          True
1                      True                   True         NaN          True
2                      True                   True         NaN          True
3                      True                   True         NaN          True
4                      True                   True         NaN          True
...                     ...                    ...         ...           ...
1115                   True                   True         NaN          True
1116                   True                    NaN         NaN           NaN
1117                   True                   True         NaN          True
1118                   True                    NaN         NaN           NaN
1119                   True                   True         NaN          True

      ... Remote Climate Control Luggage Hook And Net  \
0     ...                    NaN                  NaN
1     ...                    NaN                  NaN
2     ...                    NaN                  NaN
3     ...                    NaN                  NaN
4     ...                    NaN                  NaN
...   ...                    ...                  ...
1115  ...                    NaN                  NaN
1116  ...                    NaN                  NaN
1117  ...                    NaN                  NaN
1118  ...                    NaN                  NaN
1119  ...                    NaN                  NaN

     Remote Engine Start Stop Hands Free Tailgate Find My Car Location  \
0                         NaN                 NaN                  NaN
1                         NaN                 NaN                  NaN
2                         NaN                 NaN                  NaN
3                         NaN                 NaN                  NaN
4                         NaN                 NaN                  NaN
...                       ...                 ...                  ...
1115                      NaN                 NaN                  NaN
1116                      NaN                 NaN                  NaN
1117                      NaN                 NaN                  NaN
1118                      NaN                 NaN                  NaN
1119                      NaN                 NaN                  NaN

     Real Time Vehicle Tracking Remote Horn Light Control  \
0                           NaN                       NaN
1                           NaN                       NaN
2                           NaN                       NaN
3                           NaN                       NaN
4                           NaN                       NaN
...                         ...                       ...
1115                        NaN                       NaN
1116                        NaN                       NaN
1117                        NaN                       NaN
1118                        NaN                       NaN
1119                        NaN                       NaN

     Active Noise Cancellation Steering Mounted Tripmeter Smart Key Band
0                          NaN                        NaN            NaN
1                          NaN                        NaN            NaN
2                          NaN                        NaN            NaN
3                          NaN                        NaN            NaN
4                          NaN                        NaN            NaN
...                        ...                        ...            ...
1115                       NaN                        NaN            NaN
1116                       NaN                        NaN            NaN
1117                       NaN                        NaN            NaN
1118                       NaN                        NaN            NaN
1119                       NaN                        NaN            NaN

[1120 rows x 43 columns]

In [159]:
import pandas as pd

def extract_data2_to_dataframe(main_df, column_name):
    # Create a list to hold the rows for the new DataFrame
    data_rows = []
    
    # Iterate over each row in the main DataFrame
    for index, row in main_df.iterrows():
        # Check if the cell is a list and contains dictionaries
        if isinstance(row[column_name], list) and row[column_name]:
            # Create a dictionary to hold values for this row
            row_dict = {}
            for section in row[column_name]:
                # Extract the 'list' field from each section
                for item in section.get('list', []):
                    # Use the 'key' as the column name and 'value' as the value
                    row_dict[item['key']] = item['value']
            # Append the dictionary to the rows list
            data_rows.append(row_dict)
        else:
            # If there's no data, append an empty dictionary
            data_rows.append({})

    # Create a DataFrame from the list of dictionaries
    data2_df = pd.DataFrame(data_rows)

    return data2_df

# Extract DataFrame for the 'data_2' column
data2_df = extract_data2_to_dataframe(combined_df, 'data_2')

# Display the DataFrame
print("DataFrame for data_2:")
print(data2_df)

DataFrame for data_2:
       Color               Engine Type Displacement         Max Power  \
0     Others     U2 CRDI Diesel Engine         1396  88.73bhp@4000rpm
1      White         K Series Dual jet         1197  88.50bhp@6000rpm
2     Others               K10B Engine          998  67.04bhp@6000rpm
3     Silver  Kappa VTVT Petrol Engine         1197  81.86bhp@6000rpm
4     Silver        K10B Petrol Engine          998     67bhp@6000rpm
...      ...                       ...          ...               ...
1115  Others           Smartech Engine         1199   79.4bhp@6200rpm
1116  Others            In-Line Engine          796   46.3bhp@6200rpm
1117  Others               1.0L energy          999  71.01bhp@6250rpm
1118  Others            In-Line Engine          796   46.3bhp@6200rpm
1119  Others         VVT Petrol Engine         1197   83.1bhp@6000rpm

                Max Torque  No of Cylinder  Values per Cylinder  \
0     219.7Nm@1500-2750rpm             4.0                  4.0
1            113Nm@4400rpm             4.0                  4.0
2             90Nm@3500rpm             3.0                  4.0
3         113.75nm@4000rpm             4.0                  4.0
4             90Nm@3500rpm             3.0                  4.0
...                    ...             ...                  ...
1115         108Nm@4400rpm             4.0                  4.0
1116          62Nm@3000rpm             3.0                  4.0
1117          96Nm@3500rpm             3.0                  4.0
1118          62Nm@3000rpm             3.0                  4.0
1119         115Nm@4000rpm             4.0                  4.0

     Value Configuration Fuel Suppy System Turbo Charger  ... Top Speed  \
0                   DOHC              CRDI           Yes  ...  180 Kmph
1                    NaN               NaN           NaN  ...       NaN
2                   DOHC              MPFi            No  ...  150 Kmph
3                   DOHC              MPFI            No  ...  165 Kmph
4                   DOHC               NaN            No  ...  152 kmph
...                  ...               ...           ...  ...       ...
1115                DOHC              MPFI            No  ...       NaN
1116                SOHC              MPFI            No  ...  137km/hr
1117                 NaN              MPFi           NaN  ...       NaN
1118                SOHC              MPFI            No  ...  137km/hr
1119                DOHC              MPFI            No  ...  180 Kmph

       Acceleration         Tyre Type Alloy Wheel Size No Door Numbers  \
0      11.9 Seconds          Tubeless               16               5
1               NaN  Radial, Tubeless              NaN               5
2     15.05 Seconds  Tubeless, Radial              NaN               5
3      12.9 Seconds          Tubeless              NaN               5
4      18.6 Seconds    Tubeless Tyres              NaN               5
...             ...               ...              ...             ...
1115            NaN   Tubeless,Radial               14               5
1116   17.7 seconds   Tubeless,Radial               12               5
1117            NaN  Tubeless, Radial               16               5
1118   17.7 seconds   Tubeless,Radial               12               5
1119  12.36 seconds   Tubeless,Radial              NaN               5

     Cargo Volumn Gross Weight    BoreX Stroke Compression Ratio  \
0      295-litres          NaN             NaN               NaN
1             268         1335             NaN               NaN
2      235-litres       1250kg      73 X 82 mm            11.0:1
3             256          NaN             NaN               NaN
4      180-liters       1350kg      69 x 72 mm               NaN
...           ...          ...             ...               ...
1115   170-litres          NaN             NaN               NaN
1116          NaN       1140kg  68.5 x 72.0 mm               NaN
1117          405          NaN             NaN               NaN
1118          NaN       1140kg  68.5 x 72.0 mm               NaN
1119   339-litres       1340kg             NaN               NaN

     Ground Clearance Unladen
0                         NaN
1                         NaN
2                         NaN
3                         NaN
4                         NaN
...                       ...
1115                      NaN
1116                      NaN
1117                      NaN
1118                      NaN
1119                      NaN

[1120 rows x 35 columns]

In [160]:
import pandas as pd

# Assuming combined_df, top_df, top3_df, data2_df, top_2_df, data_df are already defined

# Concatenate the DataFrames column-wise
final_df_jaipur = pd.concat([combined_df, top_df, top3_df, data2_df, top_2_df, data_df], axis=1)

# Display the final DataFrame
print("Final DataFrame (final_df_jaipur):")
print(final_df_jaipur)

Final DataFrame (final_df_jaipur):
      it      ft         bt        km transmission  ownerNo      owner  \
0      0  Diesel  Hatchback  1,20,000       Manual        2  2nd Owner
1      0  Petrol  Hatchback    66,951       Manual        1  1st Owner
2      0  Petrol  Hatchback    80,000    Automatic        2  2nd Owner
3      0  Petrol  Hatchback    44,392       Manual        1  1st Owner
4      0  Petrol  Hatchback    40,000    Automatic        1  1st Owner
...   ..     ...        ...       ...          ...      ...        ...
1115   0  Petrol  Hatchback  1,20,000       Manual        1  1st Owner
1116   0  Petrol  Hatchback    70,000       Manual        1  1st Owner
1117   0  Petrol        SUV    20,000       Manual        1  1st Owner
1118   0  Petrol  Hatchback    40,000       Manual        1  1st Owner
1119   0  Petrol  Hatchback    80,000       Manual        1  1st Owner

            oem              model  modelYear  ...  Remote Climate Control  \
0       Hyundai        Hyundai i20       2015  ...                     NaN
1        Maruti       Maruti Swift       2012  ...                     NaN
2        Maruti     Maruti Celerio       2016  ...                     NaN
3       Hyundai  Hyundai Grand i10       2017  ...                     NaN
4        Maruti     Maruti Wagon R       2016  ...                     NaN
...         ...                ...        ...  ...                     ...
1115  Chevrolet     Chevrolet Beat       2011  ...                     NaN
1116     Maruti        Maruti Alto       2007  ...                     NaN
1117    Renault      Renault Kiger       2022  ...                     NaN
1118     Maruti        Maruti Alto       2009  ...                     NaN
1119     Maruti      Maruti Baleno       2018  ...                     NaN

     Luggage Hook And Net Remote Engine Start Stop Hands Free Tailgate  \
0                     NaN                      NaN                 NaN
1                     NaN                      NaN                 NaN
2                     NaN                      NaN                 NaN
3                     NaN                      NaN                 NaN
4                     NaN                      NaN                 NaN
...                   ...                      ...                 ...
1115                  NaN                      NaN                 NaN
1116                  NaN                      NaN                 NaN
1117                  NaN                      NaN                 NaN
1118                  NaN                      NaN                 NaN
1119                  NaN                      NaN                 NaN

     Find My Car Location Real Time Vehicle Tracking  \
0                     NaN                        NaN
1                     NaN                        NaN
2                     NaN                        NaN
3                     NaN                        NaN
4                     NaN                        NaN
...                   ...                        ...
1115                  NaN                        NaN
1116                  NaN                        NaN
1117                  NaN                        NaN
1118                  NaN                        NaN
1119                  NaN                        NaN

     Remote Horn Light Control Active Noise Cancellation  \
0                          NaN                       NaN
1                          NaN                       NaN
2                          NaN                       NaN
3                          NaN                       NaN
4                          NaN                       NaN
...                        ...                       ...
1115                       NaN                       NaN
1116                       NaN                       NaN
1117                       NaN                       NaN
1118                       NaN                       NaN
1119                       NaN                       NaN

     Steering Mounted Tripmeter Smart Key Band
0                           NaN            NaN
1                           NaN            NaN
2                           NaN            NaN
3                           NaN            NaN
4                           NaN            NaN
...                         ...            ...
1115                        NaN            NaN
1116                        NaN            NaN
1117                        NaN            NaN
1118                        NaN            NaN
1119                        NaN            NaN

[1120 rows x 179 columns]

In [161]:
## # Assuming final_df_chennai is already defined

# Specify the file name
file_name = "final_df_jaipur.xlsx"

# Save the DataFrame to an Excel file
final_df_jaipur.to_excel(file_name, index=False)

print(f"DataFrame has been saved to {file_name}")

DataFrame has been saved to final_df_jaipur.xlsx

## Kolkata :

In [162]:
## import pandas as pd
import ast  # Use ast for safer evaluation of strings to dictionaries

# Step 1: Load your DataFrame from the Excel file
file_path = 'kolkata_cars.xlsx'  # Your Excel file name
df = pd.read_excel(file_path)

# Step 2: Initialize an empty list to hold the structured data
unwound_data = []

# Step 3: Loop through each row of the DataFrame
for index, row in df.iterrows():
    # Initialize a dictionary for the current row
    combined_data = {}
    
    # Specify the columns containing dictionaries
    dict_columns = ['new_car_detail', 'new_car_overview', 'new_car_feature', 'new_car_specs']
    
    # Step 4: Extract and merge dictionaries from the specified columns
    for col in dict_columns:
        try:
            # Safely convert the string representation of the dictionary to an actual dictionary
            dict_value = ast.literal_eval(row[col])  
            if isinstance(dict_value, dict):
                combined_data.update(dict_value)  # Merge the extracted dictionary
        except Exception as e:
            print(f"Error parsing row {index}, column {col}: {e}")

    # Append the combined data for the current row to the unwound data list
    unwound_data.append(combined_data)

# Step 5: Create a DataFrame from the unwound data
unwound_df = pd.DataFrame(unwound_data)

# Optional: Display the unwound DataFrame
print(unwound_df)

# Save the unwound DataFrame to a new Excel file if needed
#unwound_df.to_excel('unwound_bangalore_cars.xlsx', index=False)

      it      ft         bt        km transmission  ownerNo      owner  \
0      0  Petrol      Sedan    70,000    Automatic        3  3rd Owner
1      0  Petrol  Hatchback    23,981       Manual        1  1st Owner
2      0  Petrol        SUV     7,100    Automatic        1  1st Owner
3      0  Petrol  Hatchback    71,574       Manual        2  2nd Owner
4      0  Diesel        SUV    50,000    Automatic        2  2nd Owner
...   ..     ...        ...       ...          ...      ...        ...
1376   0  Petrol  Hatchback    10,000       Manual        1  1st Owner
1377   0  Petrol  Hatchback  1,20,000       Manual        1  1st Owner
1378   0  Petrol      Sedan    50,000    Automatic        3  3rd Owner
1379   0  Petrol  Hatchback    40,000       Manual        1  1st Owner
1380   0  Diesel        SUV  1,20,000       Manual        2  2nd Owner

                oem                  model  modelYear  ...        price  \
0            Toyota           Toyota Camry       2014  ...  ₹ 9.75 Lakh
1            Datsun          Datsun RediGO       2017  ...  ₹ 2.66 Lakh
2           Renault          Renault Kiger       2021  ...  ₹ 5.95 Lakh
3           Hyundai            Hyundai i20       2011  ...  ₹ 2.23 Lakh
4              Audi                Audi Q3       2014  ...    ₹ 12 Lakh
...             ...                    ...        ...  ...          ...
1376         Maruti         Maruti Celerio       2022  ...  ₹ 5.10 Lakh
1377         Maruti        Maruti Alto 800       2014  ...  ₹ 1.80 Lakh
1378  Mercedes-Benz  Mercedes-Benz C-Class       2011  ...  ₹ 5.50 Lakh
1379         Maruti            Maruti Ritz       2012  ...  ₹ 1.40 Lakh
1380        Renault         Renault Duster       2017  ...     ₹ 5 Lakh

     priceActual priceSaving priceFixedText  \
0                                      None
1                                      None
2                                      None
3                                      None
4                                      None
...          ...         ...            ...
1376                                   None
1377                                   None
1378                                   None
1379                                   None
1380                                   None

                                           trendingText         heading  \
0     {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
1     {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
2     {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
3     {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
4     {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
...                                                 ...             ...
1376  {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
1377  {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
1378  {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
1379  {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications
1380  {'imgUrl': 'https://stimg.cardekho.com/used-ca...  Specifications

                                                    top bottomData  \
0     [{'key': 'Mileage', 'value': '19.16 kmpl'}, {'...       None
1     [{'key': 'Mileage', 'value': '22.7 kmpl'}, {'k...       None
2     [{'key': 'Mileage', 'value': '19.03 kmpl'}, {'...       None
3     [{'key': 'Mileage', 'value': '17 kmpl'}, {'key...       None
4     [{'key': 'Mileage', 'value': '15.73 kmpl'}, {'...       None
...                                                 ...        ...
1376  [{'key': 'Mileage', 'value': '25.24 kmpl'}, {'...       None
1377  [{'key': 'Mileage', 'value': '22.74 kmpl'}, {'...       None
1378  [{'key': 'Mileage', 'value': '11.74 kmpl'}, {'...       None
1379  [{'key': 'Mileage', 'value': '18.5 kmpl'}, {'k...       None
1380  [{'key': 'Mileage', 'value': '19.72 kmpl'}, {'...       None

                                                   data commonIcon
0     [{'heading': 'Engine and Transmission', 'subHe...
1     [{'heading': 'Engine and Transmission', 'subHe...
2     [{'heading': 'Engine and Transmission', 'subHe...
3     [{'heading': 'Engine and Transmission', 'subHe...
4     [{'heading': 'Engine and Transmission', 'subHe...
...                                                 ...        ...
1376  [{'heading': 'Engine and Transmission', 'subHe...
1377  [{'heading': 'Engine and Transmission', 'subHe...
1378  [{'heading': 'Engine and Transmission', 'subHe...
1379  [{'heading': 'Engine and Transmission', 'subHe...
1380  [{'heading': 'Engine and Transmission', 'subHe...

[1381 rows x 22 columns]

In [163]:
import pandas as pd

# Step 1: Read the Excel file
df = pd.read_excel("kolkata_cars.xlsx")

# Step 2: Initialize an empty list to hold structured data
structured_data = []

# Step 3: Loop through each row of the DataFrame
for index, row in df.iterrows():
    row_data = {}
    
    # Convert the string representation of the dictionary to an actual dictionary
    try:
        dict_value = eval(row['new_car_detail'])  # Replace eval with ast.literal_eval for safer evaluation
        if isinstance(dict_value, dict):
            row_data = dict_value
    except Exception as e:
        print(f"Error parsing row {index}: {e}")
        row_data = None

    # Append the row dictionary to the structured data list
    structured_data.append(row_data)

# Step 4: Create a DataFrame from the list of dictionaries in 'new_car_detail'
unwound_df = pd.json_normalize(structured_data)

# Optional: Display the unwound DataFrame
print(unwound_df)

# Save the unwound DataFrame to a new Excel file
#unwound_df.to_excel('unwound_new_car_detail.xlsx', index=False)

      it      ft         bt        km transmission  ownerNo      owner  \
0      0  Petrol      Sedan    70,000    Automatic        3  3rd Owner
1      0  Petrol  Hatchback    23,981       Manual        1  1st Owner
2      0  Petrol        SUV     7,100    Automatic        1  1st Owner
3      0  Petrol  Hatchback    71,574       Manual        2  2nd Owner
4      0  Diesel        SUV    50,000    Automatic        2  2nd Owner
...   ..     ...        ...       ...          ...      ...        ...
1376   0  Petrol  Hatchback    10,000       Manual        1  1st Owner
1377   0  Petrol  Hatchback  1,20,000       Manual        1  1st Owner
1378   0  Petrol      Sedan    50,000    Automatic        3  3rd Owner
1379   0  Petrol  Hatchback    40,000       Manual        1  1st Owner
1380   0  Diesel        SUV  1,20,000       Manual        2  2nd Owner

                oem                  model  modelYear  centralVariantId  \
0            Toyota           Toyota Camry       2014              2123
1            Datsun          Datsun RediGO       2017              5236
2           Renault          Renault Kiger       2021              8352
3           Hyundai            Hyundai i20       2011              1642
4              Audi                Audi Q3       2014                99
...             ...                    ...        ...               ...
1376         Maruti         Maruti Celerio       2022              8682
1377         Maruti        Maruti Alto 800       2014              3943
1378  Mercedes-Benz  Mercedes-Benz C-Class       2011              4672
1379         Maruti            Maruti Ritz       2012              4144
1380        Renault         Renault Duster       2017              5048

                 variantName        price priceActual priceSaving  \
0                     Hybrid  ₹ 9.75 Lakh
1                   T Option  ₹ 2.66 Lakh
2                    RXT AMT  ₹ 5.95 Lakh
3                 1.2 Sportz  ₹ 2.23 Lakh
4     35 TDI Quattro Premium    ₹ 12 Lakh
...                      ...          ...         ...         ...
1376                ZXI BSVI  ₹ 5.10 Lakh
1377                     LXI  ₹ 1.80 Lakh
1378      C 200 CGI Elegance  ₹ 5.50 Lakh
1379                     ZXi  ₹ 1.40 Lakh
1380    110PS Diesel RxZ AWD     ₹ 5 Lakh

     priceFixedText                                trendingText.imgUrl  \
0              None  https://stimg.cardekho.com/used-cars/common/ic...
1              None  https://stimg.cardekho.com/used-cars/common/ic...
2              None  https://stimg.cardekho.com/used-cars/common/ic...
3              None  https://stimg.cardekho.com/used-cars/common/ic...
4              None  https://stimg.cardekho.com/used-cars/common/ic...
...             ...                                                ...
1376           None  https://stimg.cardekho.com/used-cars/common/ic...
1377           None  https://stimg.cardekho.com/used-cars/common/ic...
1378           None  https://stimg.cardekho.com/used-cars/common/ic...
1379           None  https://stimg.cardekho.com/used-cars/common/ic...
1380           None  https://stimg.cardekho.com/used-cars/common/ic...

     trendingText.heading                    trendingText.desc
0           Trending Car!  High chances of sale in next 6 days
1           Trending Car!  High chances of sale in next 6 days
2           Trending Car!  High chances of sale in next 6 days
3           Trending Car!  High chances of sale in next 6 days
4           Trending Car!  High chances of sale in next 6 days
...                   ...                                  ...
1376        Trending Car!  High chances of sale in next 6 days
1377        Trending Car!  High chances of sale in next 6 days
1378        Trending Car!  High chances of sale in next 6 days
1379        Trending Car!  High chances of sale in next 6 days
1380        Trending Car!  High chances of sale in next 6 days

[1381 rows x 19 columns]

In [164]:
import pandas as pd

# Step 1: Read the Excel file
df = pd.read_excel("kolkata_cars.xlsx")

# Step 2: Initialize an empty list to hold structured data
structured_data = []

# Step 3: Loop through each row of the DataFrame
for index, row in df.iterrows():
    row_data = {}
    
    # Convert the string representation of the dictionary to an actual dictionary
    try:
        dict_value = eval(row['new_car_overview'])  # Replace eval with ast.literal_eval for safer evaluation
        if isinstance(dict_value, dict):
            row_data = dict_value
    except Exception as e:
        print(f"Error parsing row {index}: {e}")
        row_data = None

    # Append the row dictionary to the structured data list
    structured_data.append(row_data)

# Step 4: Create a DataFrame from the list of dictionaries in 'new_car_detail'
unwound_df1 = pd.json_normalize(structured_data)

# Optional: Display the unwound DataFrame
print(unwound_df1)

# Save the unwound DataFrame to a new Excel file
#unwound_df.to_excel('unwound_new_car_detail.xlsx', index=False)

           heading                                                top  \
0     Car overview  [{'key': 'Registration Year', 'value': '2014',...
1     Car overview  [{'key': 'Registration Year', 'value': 'Jul 20...
2     Car overview  [{'key': 'Registration Year', 'value': 'Nov 20...
3     Car overview  [{'key': 'Registration Year', 'value': 'Feb 20...
4     Car overview  [{'key': 'Registration Year', 'value': '2014',...
...            ...                                                ...
1376  Car overview  [{'key': 'Registration Year', 'value': '2022',...
1377  Car overview  [{'key': 'Registration Year', 'value': '2014',...
1378  Car overview  [{'key': 'Registration Year', 'value': '2011',...
1379  Car overview  [{'key': 'Registration Year', 'value': '2012',...
1380  Car overview  [{'key': 'Registration Year', 'value': '2017',...

     bottomData
0          None
1          None
2          None
3          None
4          None
...         ...
1376       None
1377       None
1378       None
1379       None
1380       None

[1381 rows x 3 columns]

In [165]:
import pandas as pd

# Step 1: Read the Excel file
df = pd.read_excel("kolkata_cars.xlsx")

# Step 2: Initialize an empty list to hold structured data
structured_data = []

# Step 3: Loop through each row of the DataFrame
for index, row in df.iterrows():
    row_data = {}
    
    # Convert the string representation of the dictionary to an actual dictionary
    try:
        dict_value = eval(row['new_car_feature'])  # Replace eval with ast.literal_eval for safer evaluation
        if isinstance(dict_value, dict):
            row_data = dict_value
    except Exception as e:
        print(f"Error parsing row {index}: {e}")
        row_data = None

    # Append the row dictionary to the structured data list
    structured_data.append(row_data)

# Step 4: Create a DataFrame from the list of dictionaries in 'new_car_detail'
unwound_df2 = pd.json_normalize(structured_data)

# Optional: Display the unwound DataFrame
print(unwound_df2)

# Save the unwound DataFrame to a new Excel file
#unwound_df.to_excel('unwound_new_car_detail.xlsx', index=False)

       heading                                                top  \
0     Features  [{'value': 'Power Steering'}, {'value': 'Power...
1     Features  [{'value': 'Power Steering'}, {'value': 'Power...
2     Features  [{'value': 'Power Steering'}, {'value': 'Power...
3     Features  [{'value': 'Power Steering'}, {'value': 'Power...
4     Features  [{'value': 'Power Steering'}, {'value': 'Power...
...        ...                                                ...
1376  Features  [{'value': 'Power Steering'}, {'value': 'Power...
1377  Features  [{'value': 'Power Steering'}, {'value': 'Power...
1378  Features  [{'value': 'Power Steering'}, {'value': 'Power...
1379  Features  [{'value': 'Power Steering'}, {'value': 'Power...
1380  Features  [{'value': 'Power Steering'}, {'value': 'Power...

                                                   data  \
0     [{'heading': 'Comfort & Convenience', 'subHead...
1     [{'heading': 'Comfort & Convenience', 'subHead...
2     [{'heading': 'Comfort & Convenience', 'subHead...
3     [{'heading': 'Comfort & Convenience', 'subHead...
4     [{'heading': 'Comfort & Convenience', 'subHead...
...                                                 ...
1376  [{'heading': 'Comfort & Convenience', 'subHead...
1377  [{'heading': 'Comfort & Convenience', 'subHead...
1378  [{'heading': 'Comfort & Convenience', 'subHead...
1379  [{'heading': 'Comfort & Convenience', 'subHead...
1380  [{'heading': 'Comfort & Convenience', 'subHead...

                                             commonIcon
0     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
2     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
3     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
4     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
...                                                 ...
1376  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1377  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1378  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1379  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg
1380  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg

[1381 rows x 4 columns]

In [167]:
import pandas as pd

# Step 1: Read the Excel file
df = pd.read_excel("kolkata_cars.xlsx")

# Step 2: Initialize an empty list to hold structured data
structured_data = []

# Step 3: Loop through each row of the DataFrame
for index, row in df.iterrows():
    row_data = {}
    
    # Convert the string representation of the dictionary to an actual dictionary
    try:
        dict_value = eval(row['new_car_specs'])  # Replace eval with ast.literal_eval for safer evaluation
        if isinstance(dict_value, dict):
            row_data = dict_value
    except Exception as e:
        print(f"Error parsing row {index}: {e}")
        row_data = None

    # Append the row dictionary to the structured data list
    structured_data.append(row_data)

# Step 4: Create a DataFrame from the list of dictionaries in 'new_car_detail'
unwound_df3 = pd.json_normalize(structured_data)

# Optional: Display the unwound DataFrame
print(unwound_df3)

# Save the unwound DataFrame to a new Excel file
#unwound_df.to_excel('unwound_new_car_detail.xlsx', index=False)

             heading                                                top  \
0     Specifications  [{'key': 'Mileage', 'value': '19.16 kmpl'}, {'...
1     Specifications  [{'key': 'Mileage', 'value': '22.7 kmpl'}, {'k...
2     Specifications  [{'key': 'Mileage', 'value': '19.03 kmpl'}, {'...
3     Specifications  [{'key': 'Mileage', 'value': '17 kmpl'}, {'key...
4     Specifications  [{'key': 'Mileage', 'value': '15.73 kmpl'}, {'...
...              ...                                                ...
1376  Specifications  [{'key': 'Mileage', 'value': '25.24 kmpl'}, {'...
1377  Specifications  [{'key': 'Mileage', 'value': '22.74 kmpl'}, {'...
1378  Specifications  [{'key': 'Mileage', 'value': '11.74 kmpl'}, {'...
1379  Specifications  [{'key': 'Mileage', 'value': '18.5 kmpl'}, {'k...
1380  Specifications  [{'key': 'Mileage', 'value': '19.72 kmpl'}, {'...

                                                   data commonIcon
0     [{'heading': 'Engine and Transmission', 'subHe...
1     [{'heading': 'Engine and Transmission', 'subHe...
2     [{'heading': 'Engine and Transmission', 'subHe...
3     [{'heading': 'Engine and Transmission', 'subHe...
4     [{'heading': 'Engine and Transmission', 'subHe...
...                                                 ...        ...
1376  [{'heading': 'Engine and Transmission', 'subHe...
1377  [{'heading': 'Engine and Transmission', 'subHe...
1378  [{'heading': 'Engine and Transmission', 'subHe...
1379  [{'heading': 'Engine and Transmission', 'subHe...
1380  [{'heading': 'Engine and Transmission', 'subHe...

[1381 rows x 4 columns]

In [168]:
import pandas as pd

# Assume df1, df2, df3, and df4 are your four DataFrames

# Concatenate the DataFrames column-wise
combined_df = pd.concat([unwound_df, unwound_df1, unwound_df2, unwound_df3], axis=1)

# Optional: Display the combined DataFrame
print(combined_df)

# Save the combined DataFrame to a new Excel file if needed
combined_df.to_excel('combined_data_column_wise_kolkata.xlsx', index=False)

      it      ft         bt        km transmission  ownerNo      owner  \
0      0  Petrol      Sedan    70,000    Automatic        3  3rd Owner
1      0  Petrol  Hatchback    23,981       Manual        1  1st Owner
2      0  Petrol        SUV     7,100    Automatic        1  1st Owner
3      0  Petrol  Hatchback    71,574       Manual        2  2nd Owner
4      0  Diesel        SUV    50,000    Automatic        2  2nd Owner
...   ..     ...        ...       ...          ...      ...        ...
1376   0  Petrol  Hatchback    10,000       Manual        1  1st Owner
1377   0  Petrol  Hatchback  1,20,000       Manual        1  1st Owner
1378   0  Petrol      Sedan    50,000    Automatic        3  3rd Owner
1379   0  Petrol  Hatchback    40,000       Manual        1  1st Owner
1380   0  Diesel        SUV  1,20,000       Manual        2  2nd Owner

                oem                  model  modelYear  ...  \
0            Toyota           Toyota Camry       2014  ...
1            Datsun          Datsun RediGO       2017  ...
2           Renault          Renault Kiger       2021  ...
3           Hyundai            Hyundai i20       2011  ...
4              Audi                Audi Q3       2014  ...
...             ...                    ...        ...  ...
1376         Maruti         Maruti Celerio       2022  ...
1377         Maruti        Maruti Alto 800       2014  ...
1378  Mercedes-Benz  Mercedes-Benz C-Class       2011  ...
1379         Maruti            Maruti Ritz       2012  ...
1380        Renault         Renault Duster       2017  ...

                                                    top bottomData   heading  \
0     [{'key': 'Registration Year', 'value': '2014',...       None  Features
1     [{'key': 'Registration Year', 'value': 'Jul 20...       None  Features
2     [{'key': 'Registration Year', 'value': 'Nov 20...       None  Features
3     [{'key': 'Registration Year', 'value': 'Feb 20...       None  Features
4     [{'key': 'Registration Year', 'value': '2014',...       None  Features
...                                                 ...        ...       ...
1376  [{'key': 'Registration Year', 'value': '2022',...       None  Features
1377  [{'key': 'Registration Year', 'value': '2014',...       None  Features
1378  [{'key': 'Registration Year', 'value': '2011',...       None  Features
1379  [{'key': 'Registration Year', 'value': '2012',...       None  Features
1380  [{'key': 'Registration Year', 'value': '2017',...       None  Features

                                                    top  \
0     [{'value': 'Power Steering'}, {'value': 'Power...
1     [{'value': 'Power Steering'}, {'value': 'Power...
2     [{'value': 'Power Steering'}, {'value': 'Power...
3     [{'value': 'Power Steering'}, {'value': 'Power...
4     [{'value': 'Power Steering'}, {'value': 'Power...
...                                                 ...
1376  [{'value': 'Power Steering'}, {'value': 'Power...
1377  [{'value': 'Power Steering'}, {'value': 'Power...
1378  [{'value': 'Power Steering'}, {'value': 'Power...
1379  [{'value': 'Power Steering'}, {'value': 'Power...
1380  [{'value': 'Power Steering'}, {'value': 'Power...

                                                   data  \
0     [{'heading': 'Comfort & Convenience', 'subHead...
1     [{'heading': 'Comfort & Convenience', 'subHead...
2     [{'heading': 'Comfort & Convenience', 'subHead...
3     [{'heading': 'Comfort & Convenience', 'subHead...
4     [{'heading': 'Comfort & Convenience', 'subHead...
...                                                 ...
1376  [{'heading': 'Comfort & Convenience', 'subHead...
1377  [{'heading': 'Comfort & Convenience', 'subHead...
1378  [{'heading': 'Comfort & Convenience', 'subHead...
1379  [{'heading': 'Comfort & Convenience', 'subHead...
1380  [{'heading': 'Comfort & Convenience', 'subHead...

                                             commonIcon         heading  \
0     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
1     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
2     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
3     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
4     https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
...                                                 ...             ...
1376  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
1377  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
1378  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
1379  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications
1380  https://stimg.cardekho.com/pwa/img/vdpN/tickG.svg  Specifications

                                                    top  \
0     [{'key': 'Mileage', 'value': '19.16 kmpl'}, {'...
1     [{'key': 'Mileage', 'value': '22.7 kmpl'}, {'k...
2     [{'key': 'Mileage', 'value': '19.03 kmpl'}, {'...
3     [{'key': 'Mileage', 'value': '17 kmpl'}, {'key...
4     [{'key': 'Mileage', 'value': '15.73 kmpl'}, {'...
...                                                 ...
1376  [{'key': 'Mileage', 'value': '25.24 kmpl'}, {'...
1377  [{'key': 'Mileage', 'value': '22.74 kmpl'}, {'...
1378  [{'key': 'Mileage', 'value': '11.74 kmpl'}, {'...
1379  [{'key': 'Mileage', 'value': '18.5 kmpl'}, {'k...
1380  [{'key': 'Mileage', 'value': '19.72 kmpl'}, {'...

                                                   data commonIcon
0     [{'heading': 'Engine and Transmission', 'subHe...
1     [{'heading': 'Engine and Transmission', 'subHe...
2     [{'heading': 'Engine and Transmission', 'subHe...
3     [{'heading': 'Engine and Transmission', 'subHe...
4     [{'heading': 'Engine and Transmission', 'subHe...
...                                                 ...        ...
1376  [{'heading': 'Engine and Transmission', 'subHe...
1377  [{'heading': 'Engine and Transmission', 'subHe...
1378  [{'heading': 'Engine and Transmission', 'subHe...
1379  [{'heading': 'Engine and Transmission', 'subHe...
1380  [{'heading': 'Engine and Transmission', 'subHe...

[1381 rows x 30 columns]

In [169]:
import pandas as pd

# Example DataFrame with repeating columns (for demonstration purposes)
# combined_df = pd.DataFrame(...)  # Assume this is your existing DataFrame

# Step 1: Get the current column names
original_columns = combined_df.columns

# Step 2: Create a new list to hold unique column names
new_columns = []
column_count = {}

# Step 3: Loop through original columns and create unique names
for col in original_columns:
    if col in column_count:
        column_count[col] += 1
        new_columns.append(f"{col}_{column_count[col]}")  # Append count as suffix
    else:
        column_count[col] = 1
        new_columns.append(col)  # Keep original name for the first occurrence

# Step 4: Assign the new column names to the DataFrame
combined_df.columns = new_columns

# Optional: Display the updated DataFrame columns
print(combined_df.columns)

Index(['it', 'ft', 'bt', 'km', 'transmission', 'ownerNo', 'owner', 'oem',
       'model', 'modelYear', 'centralVariantId', 'variantName', 'price',
       'priceActual', 'priceSaving', 'priceFixedText', 'trendingText.imgUrl',
       'trendingText.heading', 'trendingText.desc', 'heading', 'top',
       'bottomData', 'heading_2', 'top_2', 'data', 'commonIcon', 'heading_3',
       'top_3', 'data_2', 'commonIcon_2'],
      dtype='object')

In [170]:
import pandas as pd

# Function to extract and convert 'top1' into a DataFrame
def extract_top_to_dataframe(main_df):
    rows = []  # To hold the extracted data
    
    # Loop through each row in the main DataFrame
    for _, row in main_df.iterrows():
        top3_data = row['top_3']  # Access the list directly
        
        # Check if the top1_data is a list
        if isinstance(top3_data, list):
            # Create a dictionary from the extracted key-value pairs
            row_dict = {item['key']: item['value'] for item in top3_data if 'key' in item and 'value' in item}
            rows.append(row_dict)  # Add the dictionary to the rows list
        else:
            print(f"Unexpected format for row: {row}. Expected a list but got {type(top3_data)}")
    
    # Create a new DataFrame from the rows list
    top3_df = pd.DataFrame(rows)
    return top3_df

# Extracting the DataFrame from 'top1'
top3_df = extract_top_to_dataframe(combined_df)

# Display the new DataFrame
print(top3_df)

         Mileage   Engine          Max Power                 Torque  \
0     19.16 kmpl  2494 CC           158.2bhp                  213Nm
1      22.7 kmpl   799 CC           53.64bhp                   72Nm
2     19.03 kmpl   999 CC           71.01bhp                   96Nm
3        17 kmpl  1197 CC  80 PS at 5200 rpm  11.4 kgm at 4,000 rpm
4     15.73 kmpl  1968 CC          174.33bhp                  380Nm
...          ...      ...                ...                    ...
1376  25.24 kmpl   998 CC           65.71bhp                   89Nm
1377  22.74 kmpl   796 CC            47.3bhp                   69Nm
1378  11.74 kmpl  1796 CC             186bhp                  285Nm
1379   18.5 kmpl  1197 CC           85.80bhp                  114Nm
1380  19.72 kmpl  1461 CC          108.45bhp                  245Nm

     Wheel Size Seats
0            17     5
1           NaN     5
2           NaN     5
3            14     5
4            16     5
...         ...   ...
1376        NaN     5
1377        NaN     5
1378         17     5
1379         14     5
1380         16     5

[1381 rows x 6 columns]

In [171]:
import pandas as pd

# Assuming combined_df is your existing DataFrame with a column named 'top_2'
# combined_df = ...  # Your existing DataFrame

def extract_list_of_dicts_to_dataframe(main_df, column_name):
    # Initialize a list to store the extracted data
    extracted_data = []

    for index, row in main_df.iterrows():
        # Check if the cell is a list and not empty
        if isinstance(row[column_name], list) and row[column_name]:
            # Create a dictionary from the extracted values
            row_dict = {item['value']: True for item in row[column_name]}
        else:
            row_dict = {}

        extracted_data.append(row_dict)

    # Create a DataFrame from the extracted data
    extracted_df = pd.DataFrame(extracted_data)

    return extracted_df

# Extract DataFrame for top_2
top_2_df = extract_list_of_dicts_to_dataframe(combined_df, 'top_2')

# Display the DataFrame
print("DataFrame for top_2:")
print(top_2_df)

DataFrame for top_2:
     Power Steering Power Windows Front Air Conditioner Heater  \
0              True                True            True   True
1              True                True            True   True
2              True                True            True   True
3              True                True            True   True
4              True                True            True   True
...             ...                 ...             ...    ...
1376           True                True            True   True
1377           True                True            True   True
1378           True                True            True   True
1379           True                True            True   True
1380           True                True            True   True

     Adjustable Head Lights Fog Lights Front Anti Lock Braking System  \
0                      True             True                     True
1                      True              NaN                     True
2                      True              NaN                     True
3                       NaN              NaN                      NaN
4                      True             True                     True
...                     ...              ...                      ...
1376                   True              NaN                     True
1377                   True              NaN                      NaN
1378                   True             True                     True
1379                   True             True                     True
1380                   True             True                     True

     Brake Assist Cd Player Manually Adjustable Exterior Rear View Mirror  \
0            True      True                                           NaN
1             NaN       NaN                                          True
2             NaN       NaN                                           NaN
3             NaN      True                                           NaN
4            True      True                                           NaN
...           ...       ...                                           ...
1376          NaN       NaN                                           NaN
1377          NaN       NaN                                          True
1378         True      True                                           NaN
1379          NaN      True                                           NaN
1380         True      True                                           NaN

      ... LEDDRLs Anti Theft Alarm Cassette Player Air Quality Control  \
0     ...     NaN              NaN             NaN                 NaN
1     ...     NaN              NaN             NaN                 NaN
2     ...     NaN              NaN             NaN                 NaN
3     ...     NaN              NaN             NaN                 NaN
4     ...     NaN              NaN             NaN                 NaN
...   ...     ...              ...             ...                 ...
1376  ...     NaN              NaN             NaN                 NaN
1377  ...     NaN              NaN             NaN                 NaN
1378  ...     NaN              NaN             NaN                 NaN
1379  ...     NaN              NaN             NaN                 NaN
1380  ...     NaN              NaN             NaN                 NaN

     Adjustable Steering Digital Odometer Integrated2Din Audio Bluetooth  \
0                    NaN              NaN                  NaN       NaN
1                    NaN              NaN                  NaN       NaN
2                    NaN              NaN                  NaN       NaN
3                    NaN              NaN                  NaN       NaN
4                    NaN              NaN                  NaN       NaN
...                  ...              ...                  ...       ...
1376                 NaN              NaN                  NaN       NaN
1377                 NaN              NaN                  NaN       NaN
1378                 NaN              NaN                  NaN       NaN
1379                 NaN              NaN                  NaN       NaN
1380                 NaN              NaN                  NaN       NaN

     Rear Seat Belts Accessory Power Outlet
0                NaN                    NaN
1                NaN                    NaN
2                NaN                    NaN
3                NaN                    NaN
4                NaN                    NaN
...              ...                    ...
1376             NaN                    NaN
1377             NaN                    NaN
1378             NaN                    NaN
1379             NaN                    NaN
1380             NaN                    NaN

[1381 rows x 51 columns]

In [172]:
import pandas as pd

# Function to extract and convert 'top1' into a DataFrame
def extract_top_to_dataframe(main_df):
    rows = []  # To hold the extracted data
    
    # Loop through each row in the main DataFrame
    for _, row in main_df.iterrows():
        top_data = row['top']  # Access the list directly
        
        # Check if the top1_data is a list
        if isinstance(top_data, list):
            # Create a dictionary from the extracted key-value pairs
            row_dict = {item['key']: item['value'] for item in top_data if 'key' in item and 'value' in item}
            rows.append(row_dict)  # Add the dictionary to the rows list
        else:
            print(f"Unexpected format for row: {row}. Expected a list but got {type(top_data)}")
    
    # Create a new DataFrame from the rows list
    top_df = pd.DataFrame(rows)
    return top_df

# Extracting the DataFrame from 'top1'
top_df = extract_top_to_dataframe(combined_df)

# Display the new DataFrame
print(top_df)

     Registration Year     Insurance Validity Fuel Type    Seats  \
0                 2014  Third Party insurance    Petrol  5 Seats
1             Jul 2017          Comprehensive    Petrol  5 Seats
2             Nov 2021          Comprehensive    Petrol  5 Seats
3             Feb 2012            Third Party    Petrol  5 Seats
4                 2014  Third Party insurance    Diesel  5 Seats
...                ...                    ...       ...      ...
1376              2022  Third Party insurance    Petrol  5 Seats
1377              2014  Third Party insurance    Petrol  5 Seats
1378              2011  Third Party insurance    Petrol  5 Seats
1379              2012  Third Party insurance    Petrol  5 Seats
1380              2017  Third Party insurance    Diesel  5 Seats

        Kms Driven   RTO     Ownership Engine Displacement Transmission  \
0       70,000 Kms  WB02   Third Owner             2494 cc    Automatic
1       23,981 Kms  WB24   First Owner              799 cc       Manual
2        7,100 Kms  WB06   First Owner              999 cc    Automatic
3       71,574 Kms  WB06  Second Owner             1197 cc       Manual
4       50,000 Kms  WB02  Second Owner             1968 cc    Automatic
...            ...   ...           ...                 ...          ...
1376    10,000 Kms   NaN   First Owner              998 cc       Manual
1377  1,20,000 Kms   NaN   First Owner              796 cc       Manual
1378    50,000 Kms  WB06   Third Owner             1796 cc    Automatic
1379    40,000 Kms   NaN   First Owner             1197 cc       Manual
1380  1,20,000 Kms   NaN  Second Owner             1461 cc       Manual

      Year of Manufacture
0                  2014.0
1                  2017.0
2                  2021.0
3                  2011.0
4                  2014.0
...                   ...
1376               2022.0
1377               2014.0
1378               2011.0
1379               2012.0
1380               2017.0

[1381 rows x 10 columns]

In [173]:
import pandas as pd

def extract_data_to_dataframe(main_df, column_name):
    # Create a list to hold the rows for the new DataFrame
    data_rows = []
    
    # Iterate over each row in the main DataFrame
    for index, row in main_df.iterrows():
        # Check if the cell is a list and contains dictionaries
        if isinstance(row[column_name], list) and row[column_name]:
            # Extract the 'list' field from the first dictionary in the row
            list_values = row[column_name][0].get('list', [])
            # Create a dictionary to hold values for this row
            row_dict = {item['value']: True for item in list_values}
            # Append the dictionary to the rows list
            data_rows.append(row_dict)
        else:
            # If there's no data, append an empty dictionary
            data_rows.append({})

    # Create a DataFrame from the list of dictionaries
    data_df = pd.DataFrame(data_rows)

    return data_df

# Extract DataFrame for the 'data' column
data_df = extract_data_to_dataframe(combined_df, 'data')

# Display the DataFrame
print("DataFrame for data:")
print(data_df)

DataFrame for data:
     Power Steering Power Windows Front Power Windows Rear  \
0              True                True               True
1              True                True                NaN
2              True                True               True
3              True                True               True
4              True                True               True
...             ...                 ...                ...
1376           True                True               True
1377           True                True                NaN
1378           True                True               True
1379           True                True               True
1380           True                True               True

     Air Quality Control Remote Trunk Opener Low Fuel Warning Light  \
0                   True                True                   True
1                    NaN                True                   True
2                   True                 NaN                   True
3                    NaN                True                   True
4                   True                True                   True
...                  ...                 ...                    ...
1376                 NaN                 NaN                   True
1377                 NaN                True                   True
1378                True                True                   True
1379                 NaN                True                   True
1380                 NaN                True                   True

     Accessory Power Outlet Trunk Light Vanity Mirror Rear Seat Headrest  ...  \
0                      True        True          True               True  ...
1                      True         NaN           NaN               True  ...
2                      True         NaN          True               True  ...
3                      True        True          True               True  ...
4                      True        True          True               True  ...
...                     ...         ...           ...                ...  ...
1376                   True         NaN          True               True  ...
1377                    NaN         NaN           NaN               True  ...
1378                   True        True          True               True  ...
1379                   True         NaN          True               True  ...
1380                   True        True          True               True  ...

     Battery Saver Find My Car Location Steering Mounted Tripmeter  \
0              NaN                  NaN                        NaN
1              NaN                  NaN                        NaN
2              NaN                  NaN                        NaN
3              NaN                  NaN                        NaN
4              NaN                  NaN                        NaN
...            ...                  ...                        ...
1376           NaN                  NaN                        NaN
1377           NaN                  NaN                        NaN
1378           NaN                  NaN                        NaN
1379           NaN                  NaN                        NaN
1380           NaN                  NaN                        NaN

     Remote Climate Control Leather Seats Remote Engine Start Stop  \
0                       NaN           NaN                      NaN
1                       NaN           NaN                      NaN
2                       NaN           NaN                      NaN
3                       NaN           NaN                      NaN
4                       NaN           NaN                      NaN
...                     ...           ...                      ...
1376                    NaN           NaN                      NaN
1377                    NaN           NaN                      NaN
1378                    NaN           NaN                      NaN
1379                    NaN           NaN                      NaN
1380                    NaN           NaN                      NaN

     Remote Horn Light Control Active Noise Cancellation Smart Key Band  \
0                          NaN                       NaN            NaN
1                          NaN                       NaN            NaN
2                          NaN                       NaN            NaN
3                          NaN                       NaN            NaN
4                          NaN                       NaN            NaN
...                        ...                       ...            ...
1376                       NaN                       NaN            NaN
1377                       NaN                       NaN            NaN
1378                       NaN                       NaN            NaN
1379                       NaN                       NaN            NaN
1380                       NaN                       NaN            NaN

     Real Time Vehicle Tracking
0                           NaN
1                           NaN
2                           NaN
3                           NaN
4                           NaN
...                         ...
1376                        NaN
1377                        NaN
1378                        NaN
1379                        NaN
1380                        NaN

[1381 rows x 44 columns]

In [174]:
import pandas as pd

def extract_data2_to_dataframe(main_df, column_name):
    # Create a list to hold the rows for the new DataFrame
    data_rows = []
    
    # Iterate over each row in the main DataFrame
    for index, row in main_df.iterrows():
        # Check if the cell is a list and contains dictionaries
        if isinstance(row[column_name], list) and row[column_name]:
            # Create a dictionary to hold values for this row
            row_dict = {}
            for section in row[column_name]:
                # Extract the 'list' field from each section
                for item in section.get('list', []):
                    # Use the 'key' as the column name and 'value' as the value
                    row_dict[item['key']] = item['value']
            # Append the dictionary to the rows list
            data_rows.append(row_dict)
        else:
            # If there's no data, append an empty dictionary
            data_rows.append({})

    # Create a DataFrame from the list of dictionaries
    data2_df = pd.DataFrame(data_rows)

    return data2_df

# Extract DataFrame for the 'data_2' column
data2_df = extract_data2_to_dataframe(combined_df, 'data_2')

# Display the DataFrame
print("DataFrame for data_2:")
print(data2_df)

DataFrame for data_2:
       Color             Engine Type Displacement          Max Power  \
0      White  2AR FXE Petrol Engine          2494   158.2bhp@5700rpm
1        Red      0.8L Petrol Engine          799   53.64bhp@5678rpm
2       Blue             1.0L energy          999   71.01bhp@6250rpm
3        Red          In-Line Engine         1197  80 PS at 5200 rpm
4      White       TDI Diesel Engine         1968  174.33bhp@4200rpm
...      ...                     ...          ...                ...
1376  Others                    K10C          998   65.71bhp@5500rpm
1377  Others       F8D Petrol Engine          796    47.3bhp@6000rpm
1378  Others  Blue Efficiency Engine         1796     186bhp@5600rpm
1379  Others  K Series Petrol Engine         1197   85.80bhp@6000rpm
1380  Others   dCi THP Diesel Engine         1461  108.45bhp@4000rpm

                 Max Torque  No of Cylinder  Values per Cylinder  \
0             213Nm@4500rpm             4.0                  4.0
1              72Nm@4386rpm             3.0                  4.0
2              96Nm@3500rpm             3.0                  4.0
3     11.4 kgm at 4,000 rpm             4.0                  4.0
4        380Nm@1750-2500rpm             4.0                  4.0
...                     ...             ...                  ...
1376           89Nm@3500rpm             3.0                  4.0
1377           69Nm@3500rpm             3.0                  4.0
1378     285Nm@2400-4000rpm             4.0                  4.0
1379          114Nm@4000rpm             4.0                  4.0
1380          245Nm@1750rpm             4.0                  4.0

     Value Configuration               Fuel Suppy System BoreX Stroke  ...  \
0                   DOHC  Electronic Fuel Injection(EFI)   90 X 98 mm  ...
1                   DOHC                            MPFi          NaN  ...
2                    NaN                            MPFi          NaN  ...
3                   DOHC                            MPFI          NaN  ...
4                   DOHC                            CRDI          NaN  ...
...                  ...                             ...          ...  ...
1376                 NaN                             NaN          NaN  ...
1377                DOHC                            MPFi          NaN  ...
1378                 NaN                            Mpfi          NaN  ...
1379                DOHC                            MPFI          NaN  ...
1380                DOHC                            CRDi          NaN  ...

     Front Brake Type Rear Brake Type         Tyre Type Alloy Wheel Size  \
0     Ventilated Disc      Solid Disc   Tubeless,Radial               17
1                Disc            Drum               NaN              NaN
2                Disc            Drum  Tubeless, Radial              NaN
3                Disc            Drum   Tubeless,Radial               14
4     Ventilated Disc            Drum   Tubeless,Radial               16
...               ...             ...               ...              ...
1376  Ventilated Disc            Drum  Tubeless, Radial              NaN
1377       Solid Disc            Drum    Tubeless Tyres              NaN
1378  Ventilated Disc      Solid Disc   Tubeless,Radial               17
1379  Ventilated Disc            Drum   Tubeless,Radial               14
1380             Disc            Drum   Tubeless,Radial               16

     No Door Numbers Ground Clearance Unladen Cargo Volumn Compression Ratio  \
0                  4                      NaN          NaN               NaN
1                  5                    185mm          222               NaN
2                  5                      NaN          405               NaN
3                  5                      NaN      295 Lit                :1
4                  5                      NaN   460-litres               NaN
...              ...                      ...          ...               ...
1376               5                      NaN          313               NaN
1377               5                      NaN   177-litres               NaN
1378               4                      NaN   475-litres             9.3:1
1379               5                      NaN   236-liters               NaN
1380               5                      NaN   410-litres               NaN

       Acceleration Top Speed
0               NaN       NaN
1               NaN       NaN
2               NaN       NaN
3         12.96 Sec       NaN
4       8.2 Seconds  212 Kmph
...             ...       ...
1376            NaN       NaN
1377     19 Seconds  140 kmph
1378    8.8 Seconds  230km/hr
1379     15 Seconds  156 Kmph
1380  14.20 Seconds  168 Kmph

[1381 rows x 35 columns]

In [175]:
import pandas as pd

# Assuming combined_df, top_df, top3_df, data2_df, top_2_df, data_df are already defined

# Concatenate the DataFrames column-wise
final_df_kolkata = pd.concat([combined_df, top_df, top3_df, data2_df, top_2_df, data_df], axis=1)

# Display the final DataFrame
print("Final DataFrame (final_df_kolkata):")
print(final_df_kolkata)

Final DataFrame (final_df_kolkata):
      it      ft         bt        km transmission  ownerNo      owner  \
0      0  Petrol      Sedan    70,000    Automatic        3  3rd Owner
1      0  Petrol  Hatchback    23,981       Manual        1  1st Owner
2      0  Petrol        SUV     7,100    Automatic        1  1st Owner
3      0  Petrol  Hatchback    71,574       Manual        2  2nd Owner
4      0  Diesel        SUV    50,000    Automatic        2  2nd Owner
...   ..     ...        ...       ...          ...      ...        ...
1376   0  Petrol  Hatchback    10,000       Manual        1  1st Owner
1377   0  Petrol  Hatchback  1,20,000       Manual        1  1st Owner
1378   0  Petrol      Sedan    50,000    Automatic        3  3rd Owner
1379   0  Petrol  Hatchback    40,000       Manual        1  1st Owner
1380   0  Diesel        SUV  1,20,000       Manual        2  2nd Owner

                oem                  model  modelYear  ...  Battery Saver  \
0            Toyota           Toyota Camry       2014  ...            NaN
1            Datsun          Datsun RediGO       2017  ...            NaN
2           Renault          Renault Kiger       2021  ...            NaN
3           Hyundai            Hyundai i20       2011  ...            NaN
4              Audi                Audi Q3       2014  ...            NaN
...             ...                    ...        ...  ...            ...
1376         Maruti         Maruti Celerio       2022  ...            NaN
1377         Maruti        Maruti Alto 800       2014  ...            NaN
1378  Mercedes-Benz  Mercedes-Benz C-Class       2011  ...            NaN
1379         Maruti            Maruti Ritz       2012  ...            NaN
1380        Renault         Renault Duster       2017  ...            NaN

     Find My Car Location Steering Mounted Tripmeter Remote Climate Control  \
0                     NaN                        NaN                    NaN
1                     NaN                        NaN                    NaN
2                     NaN                        NaN                    NaN
3                     NaN                        NaN                    NaN
4                     NaN                        NaN                    NaN
...                   ...                        ...                    ...
1376                  NaN                        NaN                    NaN
1377                  NaN                        NaN                    NaN
1378                  NaN                        NaN                    NaN
1379                  NaN                        NaN                    NaN
1380                  NaN                        NaN                    NaN

     Leather Seats Remote Engine Start Stop Remote Horn Light Control  \
0              NaN                      NaN                       NaN
1              NaN                      NaN                       NaN
2              NaN                      NaN                       NaN
3              NaN                      NaN                       NaN
4              NaN                      NaN                       NaN
...            ...                      ...                       ...
1376           NaN                      NaN                       NaN
1377           NaN                      NaN                       NaN
1378           NaN                      NaN                       NaN
1379           NaN                      NaN                       NaN
1380           NaN                      NaN                       NaN

     Active Noise Cancellation Smart Key Band Real Time Vehicle Tracking
0                          NaN            NaN                        NaN
1                          NaN            NaN                        NaN
2                          NaN            NaN                        NaN
3                          NaN            NaN                        NaN
4                          NaN            NaN                        NaN
...                        ...            ...                        ...
1376                       NaN            NaN                        NaN
1377                       NaN            NaN                        NaN
1378                       NaN            NaN                        NaN
1379                       NaN            NaN                        NaN
1380                       NaN            NaN                        NaN

[1381 rows x 176 columns]

In [176]:
## # Assuming final_df_chennai is already defined

# Specify the file name
file_name = "final_df_kolkata.xlsx"

# Save the DataFrame to an Excel file
final_df_kolkata.to_excel(file_name, index=False)

print(f"DataFrame has been saved to {file_name}")

DataFrame has been saved to final_df_kolkata.xlsx

## FULL DATA:

In [178]:
import pandas as pd

# Function to identify duplicate columns
def find_duplicate_columns(df):
    return df.columns[df.columns.duplicated()].unique()

# Check for duplicate columns in each DataFrame
duplicates_chennai = find_duplicate_columns(final_df_chennai)
duplicates_bangalore = find_duplicate_columns(final_df_bangalore)
duplicates_delhi = find_duplicate_columns(final_df_delhi)
duplicates_hyderabad = find_duplicate_columns(final_df_hyderabad)
duplicates_jaipur = find_duplicate_columns(final_df_jaipur)
duplicates_kolkata = find_duplicate_columns(final_df_kolkata)

# Print duplicate columns for each DataFrame
print("Duplicate columns in final_df_chennai:", duplicates_chennai)
print("Duplicate columns in final_df_bangalore:", duplicates_bangalore)
print("Duplicate columns in final_df_delhi:", duplicates_delhi)
print("Duplicate columns in final_df_hyderabad:", duplicates_hyderabad)
print("Duplicate columns in final_df_jaipur:", duplicates_jaipur)
print("Duplicate columns in final_df_kolkata:", duplicates_kolkata)

# Example: Renaming duplicate columns in one of the DataFrames (customize as needed)
def rename_duplicate_columns(df):
    cols = pd.Series(df.columns)
    for dup in cols[cols.duplicated()].unique():
        cols[cols[cols == dup].index.values.tolist()] = [dup + '_' + str(i) if i != 0 else dup for i in range(sum(cols == dup))]
    df.columns = cols
    return df

# Renaming duplicate columns
final_df_chennai = rename_duplicate_columns(final_df_chennai)
final_df_bangalore = rename_duplicate_columns(final_df_bangalore)
final_df_delhi = rename_duplicate_columns(final_df_delhi)
final_df_hyderabad = rename_duplicate_columns(final_df_hyderabad)
final_df_jaipur = rename_duplicate_columns(final_df_jaipur)
final_df_kolkata = rename_duplicate_columns(final_df_kolkata)

# Now you can safely reindex and concatenate the DataFrames as before
# Step 1: Get the columns from the DataFrame with the maximum number of columns (Hyderabad)
columns_hyderabad = final_df_hyderabad.columns

# Step 2: Reindex each DataFrame to have the same columns as Hyderabad, filling missing columns with NaN
final_df_chennai_reindexed = final_df_chennai.reindex(columns=columns_hyderabad)
final_df_bangalore_reindexed = final_df_bangalore.reindex(columns=columns_hyderabad)
final_df_delhi_reindexed = final_df_delhi.reindex(columns=columns_hyderabad)
final_df_hyderabad_reindexed = final_df_hyderabad  # Already has the full set of columns
final_df_jaipur_reindexed = final_df_jaipur.reindex(columns=columns_hyderabad)
final_df_kolkata_reindexed = final_df_kolkata.reindex(columns=columns_hyderabad)

# Step 3: Concatenate all DataFrames into a single DataFrame
full_data = pd.concat(
    [
        final_df_chennai_reindexed,
        final_df_bangalore_reindexed,
        final_df_delhi_reindexed,
        final_df_hyderabad_reindexed,
        final_df_jaipur_reindexed,
        final_df_kolkata_reindexed,
    ],
    ignore_index=True,  # Reset the index after concatenation
)

# Verify the shape of the full_data DataFrame
print(f'Shape of full_data: {full_data.shape}')  # Should print (8369, 200)

Duplicate columns in final_df_chennai: Index(['Seats', 'Max Power', 'Power Steering', 'Power Windows Front',
       'Power Windows Rear', 'Low Fuel Warning Light',
       'Accessory Power Outlet', 'Trunk Light', 'Rear Seat Headrest',
       'Remote Fuel Lid Opener', 'Vanity Mirror', 'Air Quality Control',
       'Remote Trunk Opener'],
      dtype='object')
Duplicate columns in final_df_bangalore: Index(['Seats', 'Max Power', 'Power Steering', 'Power Windows Front',
       'Power Windows Rear', 'Remote Trunk Opener', 'Remote Fuel Lid Opener',
       'Low Fuel Warning Light', 'Accessory Power Outlet',
       'Rear Seat Headrest', 'Cup Holders Front', 'Navigation System'],
      dtype='object')
Duplicate columns in final_df_delhi: Index(['Seats', 'Max Power', 'Power Steering', 'Power Windows Front',
       'Power Windows Rear', 'Air Quality Control', 'Low Fuel Warning Light',
       'Rear Seat Headrest', 'Multifunction Steering Wheel', 'Cruise Control',
       'Drive Modes', 'Remote Trunk Opener', 'Remote Fuel Lid Opener',
       'Vanity Mirror', 'Cup Holders Front'],
      dtype='object')
Duplicate columns in final_df_hyderabad: Index(['Seats', 'Max Power', 'Power Steering', 'Power Windows Front',
       'Power Windows Rear', 'Remote Trunk Opener', 'Low Fuel Warning Light',
       'Accessory Power Outlet', 'Rear Seat Headrest',
       'Remote Fuel Lid Opener', 'Navigation System', 'Air Quality Control',
       'Adjustable Head Lights', 'Fog Lights Front', 'Fog Lights Rear',
       'Power Adjustable Exterior Rear View Mirror',
       'Manually Adjustable Exterior Rear View Mirror',
       'Electric Folding Rear View Mirror', 'Power Antenna', 'Tinted Glass'],
      dtype='object')
Duplicate columns in final_df_jaipur: Index(['Seats', 'Max Power', 'Power Steering', 'Power Windows Front',
       'Power Windows Rear', 'Air Quality Control', 'Remote Trunk Opener',
       'Remote Fuel Lid Opener', 'Low Fuel Warning Light',
       'Accessory Power Outlet', 'Trunk Light', 'Vanity Mirror',
       'Rear Seat Headrest', 'Cup Holders Front'],
      dtype='object')
Duplicate columns in final_df_kolkata: Index(['Seats', 'Max Power', 'Power Steering', 'Power Windows Front',
       'Power Windows Rear', 'Air Quality Control', 'Remote Trunk Opener',
       'Low Fuel Warning Light', 'Accessory Power Outlet',
       'Rear Seat Headrest', 'Cup Holders Front', 'Remote Fuel Lid Opener',
       'Leather Seats'],
      dtype='object')
Shape of full_data: (8369, 200)

In [179]:
## # Assuming final_df_chennai is already defined

# Specify the file name
file_name = "full_data.xlsx"

# Save the DataFrame to an Excel file
full_data.to_excel(file_name, index=False)

print(f"DataFrame has been saved to {file_name}")

DataFrame has been saved to full_data.xlsx

In [180]:
full_data.columns

Index(['it', 'ft', 'bt', 'km', 'transmission', 'ownerNo', 'owner', 'oem',
       'model', 'modelYear',
       ...
       'Power Antenna_1', 'Integrated Antenna', 'Tinted Glass_1',
       'Rear Spoiler', 'Removable Convertible Top', 'Roof Carrier', 'Sun Roof',
       'Moon Roof', 'Side Stepper',
       'Outside Rear View Mirror Turn Indicators'],
      dtype='object', length=200)